In [2]:
# Import libraries for data cleaning and manipulation
import pandas as pd
import numpy as np
from pathlib import Path

# Display pandas version
print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [3]:


# Specify the folder containing the original datasets
project_path = Path(
    "/Users/isandoval/Desktop/Bellabeat_Case_Study/Original_Data"
)

# Check whether the folder exists
print("Folder exists:", project_path.exists())

# Find all CSV files within the project folder
csv_files = sorted(project_path.rglob("*.csv"))

# Display the number of CSV files found
print("Total CSV files found:", len(csv_files))

# Display their filenames
for file in csv_files:
    print(file.relative_to(project_path))

Folder exists: True
Total CSV files found: 29
Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv
Fitabase Data 3.12.16-4.11.16/heartrate_seconds_merged.csv
Fitabase Data 3.12.16-4.11.16/hourlyCalories_merged.csv
Fitabase Data 3.12.16-4.11.16/hourlyIntensities_merged.csv
Fitabase Data 3.12.16-4.11.16/hourlySteps_merged.csv
Fitabase Data 3.12.16-4.11.16/minuteCaloriesNarrow_merged.csv
Fitabase Data 3.12.16-4.11.16/minuteIntensitiesNarrow_merged.csv
Fitabase Data 3.12.16-4.11.16/minuteMETsNarrow_merged.csv
Fitabase Data 3.12.16-4.11.16/minuteSleep_merged.csv
Fitabase Data 3.12.16-4.11.16/minuteStepsNarrow_merged.csv
Fitabase Data 3.12.16-4.11.16/weightLogInfo_merged.csv
Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv
Fitabase Data 4.12.16-5.12.16/dailyCalories_merged.csv
Fitabase Data 4.12.16-5.12.16/dailyIntensities_merged.csv
Fitabase Data 4.12.16-5.12.16/dailySteps_merged.csv
Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv
Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv
Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv
Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteCaloriesNarrow_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteCaloriesWide_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteIntensitiesNarrow_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteIntensitiesWide_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteMETsNarrow_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteSleep_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteStepsNarrow_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteStepsWide_merged.csv
Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv
Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv

In [8]:
# Define the six selected dataset types
selected_datasets = [
    "dailyActivity_merged",
    "hourlySteps_merged",
    "hourlyIntensities_merged",
    "hourlyCalories_merged",
    "minuteSleep_merged",
    "heartrate_seconds_merged"
]

# Filter the CSV files to include selected datasets
selected_files = [
    file for file in csv_files
    if file.stem in selected_datasets
]

# Check the number of files for each dataset
for name in selected_datasets:
    matches = [
        file for file in selected_files
        if file.stem == name
    ]
    print(f"{name}: {len(matches)} files")

# Display total number of selected files
print("\nTotal selected files:", len(selected_files))

# Display the full list of selected files
print("\nSelected file paths:")
for file in selected_files:
    print(file.relative_to(project_path))

dailyActivity_merged: 2 files
hourlySteps_merged: 2 files
hourlyIntensities_merged: 2 files
hourlyCalories_merged: 2 files
minuteSleep_merged: 2 files
heartrate_seconds_merged: 2 files

Total selected files: 12

Selected file paths:
Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv
Fitabase Data 3.12.16-4.11.16/heartrate_seconds_merged.csv
Fitabase Data 3.12.16-4.11.16/hourlyCalories_merged.csv
Fitabase Data 3.12.16-4.11.16/hourlyIntensities_merged.csv
Fitabase Data 3.12.16-4.11.16/hourlySteps_merged.csv
Fitabase Data 3.12.16-4.11.16/minuteSleep_merged.csv
Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv
Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv
Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv
Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv
Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv
Fitabase Data 4.12.16-5.12.16/minuteSleep_merged.csv

## Step 2: Data Quality Inspection

In [9]:
# Step 2A: Import daily activity datasets

# Identify the two dailyActivity CSV files
daily_files = [
    file for file in selected_files
    if file.stem == "dailyActivity_merged"
]

# Identify each time period using its folder name
period1_path = next(
    file for file in daily_files
    if file.parent.name == "Fitabase Data 3.12.16-4.11.16"
)

period2_path = next(
    file for file in daily_files
    if file.parent.name == "Fitabase Data 4.12.16-5.12.16"
)

# Load the original CSV files into pandas DataFrames
daily_1 = pd.read_csv(period1_path)
daily_2 = pd.read_csv(period2_path)

# Display dataset dimensions
print("Period 1:", daily_1.shape)
print("Period 2:", daily_2.shape)

# Display the first five records from each dataset
print("\nPeriod 1 Preview:")
display(daily_1.head())

print("\nPeriod 2 Preview:")
display(daily_2.head())

Period 1: (457, 15)
Period 2: (940, 15)

Period 1 Preview:

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,3/25/2016,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819
1,1503960366,3/26/2016,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154
2,1503960366,3/27/2016,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944
3,1503960366,3/28/2016,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932
4,1503960366,3/29/2016,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886

Period 2 Preview:

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [10]:
# Step 2B: Inspect column names and data types

# Display column names for each dataset
print("Period 1 Columns:")
print(daily_1.columns.tolist())

print("\nPeriod 2 Columns:")
print(daily_2.columns.tolist())

# Check whether column names match exactly
print("\nColumn names match:",
      daily_1.columns.equals(daily_2.columns))

# Display data types and non-null counts
print("\nPeriod 1 Information:")
daily_1.info()

print("\nPeriod 2 Information:")
daily_2.info()

Period 1 Columns:
['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance', 'LoggedActivitiesDistance', 'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories']

Period 2 Columns:
['Id', 'ActivityDate', 'TotalSteps', 'TotalDistance', 'TrackerDistance', 'LoggedActivitiesDistance', 'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance', 'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes', 'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories']

Column names match: True

Period 1 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        457 non-null    int64
 1   ActivityDate              457 non-null    object
 2   TotalSteps                457 non-null    int64
 3   TotalDistance             457 non-null    float64
 4   TrackerDistance           457 non-null    float64
 5   LoggedActivitiesDistance  457 non-null    float64
 6   VeryActiveDistance        457 non-null    float64
 7   ModeratelyActiveDistance  457 non-null    float64
 8   LightActiveDistance       457 non-null    float64
 9   SedentaryActiveDistance   457 non-null    float64
 10  VeryActiveMinutes         457 non-null    int64
 11  FairlyActiveMinutes       457 non-null    int64
 12  LightlyActiveMinutes      457 non-null    int64
 13  SedentaryMinutes          457 non-null    int64
 14  Calories                  457 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 53.7+ KB

Period 2 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDate              940 non-null    object
 2   TotalSteps                940 non-null    int64
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64
 11  FairlyActiveMinutes       940 non-null    int64
 12  LightlyActiveMinutes      940 non-null    int64
 13  SedentaryMinutes          940 non-null    int64
 14  Calories                  940 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 110.3+ KB

In [11]:
# Step 2C: Check for missing values

# Calculate missing values for Period 1
missing_1 = daily_1.isnull().sum()

# Calculate missing values for Period 2
missing_2 = daily_2.isnull().sum()

# Calculate missing percentages
missing_pct_1 = (missing_1 / len(daily_1)) * 100
missing_pct_2 = (missing_2 / len(daily_2)) * 100

# Create a comparison table
missing_summary = pd.DataFrame({
    "Period 1 Missing": missing_1,
    "Period 1 Missing (%)": missing_pct_1,
    "Period 2 Missing": missing_2,
    "Period 2 Missing (%)": missing_pct_2
})

# Display results
display(missing_summary.round(2))

# Display total missing values
print("Total missing values:")
print("Period 1:", missing_1.sum())
print("Period 2:", missing_2.sum())

,Period 1 Missing,Period 1 Missing (%),Period 2 Missing,Period 2 Missing (%)
Id,0,0.0,0,0.0
ActivityDate,0,0.0,0,0.0
TotalSteps,0,0.0,0,0.0
TotalDistance,0,0.0,0,0.0
TrackerDistance,0,0.0,0,0.0
LoggedActivitiesDistance,0,0.0,0,0.0
VeryActiveDistance,0,0.0,0,0.0
ModeratelyActiveDistance,0,0.0,0,0.0
LightActiveDistance,0,0.0,0,0.0
SedentaryActiveDistance,0,0.0,0,0.0
VeryActiveMinutes,0,0.0,0,0.0
FairlyActiveMinutes,0,0.0,0,0.0
LightlyActiveMinutes,0,0.0,0,0.0
SedentaryMinutes,0,0.0,0,0.0
Calories,0,0.0,0,0.0

Total missing values:
Period 1: 0
Period 2: 0

In [12]:
# Step 2D: Check for duplicate records

# 1. Check for exact duplicate rows
exact_duplicates_1 = daily_1.duplicated().sum()
exact_duplicates_2 = daily_2.duplicated().sum()

print("Exact Duplicate Records:")
print("Period 1:", exact_duplicates_1)
print("Period 2:", exact_duplicates_2)

# 2. Check for duplicate participant-date combinations
key_columns = ["Id", "ActivityDate"]

duplicate_keys_1 = daily_1.duplicated(
    subset=key_columns
).sum()

duplicate_keys_2 = daily_2.duplicated(
    subset=key_columns
).sum()

print("\nDuplicate Participant-Date Records:")
print("Period 1:", duplicate_keys_1)
print("Period 2:", duplicate_keys_2)

# 3. Display repeated participant-date records
print("\nPeriod 1 Duplicate Details:")
display(
    daily_1[
        daily_1.duplicated(
            subset=key_columns, keep=False
        )
    ]
)

print("\nPeriod 2 Duplicate Details:")
display(
    daily_2[
        daily_2.duplicated(
            subset=key_columns, keep=False
        )
    ]
)

Exact Duplicate Records:
Period 1: 0
Period 2: 0

Duplicate Participant-Date Records:
Period 1: 0
Period 2: 0

Period 1 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityDate, TotalSteps, TotalDistance, TrackerDistance, LoggedActivitiesDistance, VeryActiveDistance, ModeratelyActiveDistance, LightActiveDistance, SedentaryActiveDistance, VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, SedentaryMinutes, Calories]
Index: []

Period 2 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityDate, TotalSteps, TotalDistance, TrackerDistance, LoggedActivitiesDistance, VeryActiveDistance, ModeratelyActiveDistance, LightActiveDistance, SedentaryActiveDistance, VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, SedentaryMinutes, Calories]
Index: []

In [13]:
# Step 2E: Inspect date ranges

# Create copies to preserve the original imported data
daily_check_1 = daily_1.copy()
daily_check_2 = daily_2.copy()

# Convert ActivityDate to datetime
for df in [daily_check_1, daily_check_2]:
    df["ActivityDate"] = pd.to_datetime(
        df["ActivityDate"],
        format="%m/%d/%Y",
        errors="coerce"
    )

# Check for dates that could not be converted
print("Invalid or missing dates:")
print("Period 1:", daily_check_1["ActivityDate"].isna().sum())
print("Period 2:", daily_check_2["ActivityDate"].isna().sum())

# Display date ranges
print("\nPeriod 1 Date Range:")
print("Earliest:", daily_check_1["ActivityDate"].min())
print("Latest:", daily_check_1["ActivityDate"].max())

print("\nPeriod 2 Date Range:")
print("Earliest:", daily_check_2["ActivityDate"].min())
print("Latest:", daily_check_2["ActivityDate"].max())

# Count unique participants and recorded dates
print("\nPeriod 1:")
print("Unique participants:", daily_check_1["Id"].nunique())
print("Unique dates:", daily_check_1["ActivityDate"].nunique())

print("\nPeriod 2:")
print("Unique participants:", daily_check_2["Id"].nunique())
print("Unique dates:", daily_check_2["ActivityDate"].nunique())

Invalid or missing dates:
Period 1: 0
Period 2: 0

Period 1 Date Range:
Earliest: 2016-03-12 00:00:00
Latest: 2016-04-12 00:00:00

Period 2 Date Range:
Earliest: 2016-04-12 00:00:00
Latest: 2016-05-12 00:00:00

Period 1:
Unique participants: 35
Unique dates: 32

Period 2:
Unique participants: 33
Unique dates: 31

In [14]:
# Check overlapping calendar dates
dates_1 = set(daily_check_1["ActivityDate"].dropna())
dates_2 = set(daily_check_2["ActivityDate"].dropna())

overlapping_dates = dates_1.intersection(dates_2)

print("Overlapping calendar dates:", len(overlapping_dates))
print("Dates:", sorted(overlapping_dates))

# Check overlapping participant-date records
keys = ["Id", "ActivityDate"]

overlapping_records = daily_check_1[keys].merge(
    daily_check_2[keys],
    on=keys,
    how="inner",
    validate="one_to_one"
)

print("\nOverlapping participant-date records:",
      len(overlapping_records))

display(overlapping_records.head(10))

Overlapping calendar dates: 1
Dates: [Timestamp('2016-04-12 00:00:00')]

Overlapping participant-date records: 24

           Id ActivityDate
0  1503960366   2016-04-12
1  1624580081   2016-04-12
2  1844505072   2016-04-12
3  1927972279   2016-04-12
4  2022484408   2016-04-12
5  2026352035   2016-04-12
6  2320127002   2016-04-12
7  2347167796   2016-04-12
8  2873212765   2016-04-12
9  3977333714   2016-04-12

In [15]:
# Step 2E.3: Compare overlapping participant-date records

# Identify the columns containing activity measurements
measurement_columns = [
    col for col in daily_check_1.columns
    if col not in ["Id", "ActivityDate"]
]

# Join records from both periods using participant and date
overlap_comparison = daily_check_1.merge(
    daily_check_2,
    on=["Id", "ActivityDate"],
    how="inner",
    suffixes=("_p1", "_p2"),
    validate="one_to_one"
)

# Compare measurements across the two periods
# np.isclose accounts for minor floating-point differences
match_results = pd.DataFrame({
    col: np.isclose(
        overlap_comparison[f"{col}_p1"],
        overlap_comparison[f"{col}_p2"],
        equal_nan=True
    )
    for col in measurement_columns
})

# Identify records whose measurements all match
overlap_comparison["All_Measurements_Match"] = (
    match_results.all(axis=1)
)

# Display comparison results
print("Total overlapping records:", len(overlap_comparison))

print("Records with matching measurements:",
      overlap_comparison["All_Measurements_Match"].sum())

print("Records with different measurements:",
      (~overlap_comparison["All_Measurements_Match"]).sum())

# Show which measurement columns differ
print("\nNumber of differences by column:")
display((~match_results).sum().sort_values(ascending=False))

# Preview records with conflicting measurements
print("\nPreview of conflicting records:")
display(
    overlap_comparison.loc[
        ~overlap_comparison["All_Measurements_Match"],
        [
            "Id",
            "ActivityDate",
            "TotalSteps_p1",
            "TotalSteps_p2",
            "Calories_p1",
            "Calories_p2"
        ]
    ].head(10)
)

Total overlapping records: 24
Records with matching measurements: 0
Records with different measurements: 24

Number of differences by column:

TotalSteps                  24
TotalDistance               24
TrackerDistance             24
LightActiveDistance         24
LightlyActiveMinutes        24
SedentaryMinutes            24
Calories                    24
ModeratelyActiveDistance    15
FairlyActiveMinutes         15
VeryActiveDistance          14
VeryActiveMinutes           14
LoggedActivitiesDistance     0
SedentaryActiveDistance      0
dtype: int64

Preview of conflicting records:

,Id,ActivityDate,TotalSteps_p1,TotalSteps_p2,Calories_p1,Calories_p2
0,1503960366,2016-04-12,224,13162,50,1985
1,1624580081,2016-04-12,6627,8163,706,1432
2,1844505072,2016-04-12,0,6697,399,2030
3,1927972279,2016-04-12,24,678,942,2220
4,2022484408,2016-04-12,6717,11875,1140,2390
5,2026352035,2016-04-12,1019,4414,600,1459
6,2320127002,2016-04-12,2098,10725,790,2124
7,2347167796,2016-04-12,0,10113,399,2344
8,2873212765,2016-04-12,0,8796,0,1982
9,3977333714,2016-04-12,759,8856,182,1450

In [16]:
# Step 2E.4: Evaluate overlapping records

# Select important activity measurements
compare_columns = [
    "TotalSteps",
    "TotalDistance",
    "Calories"
]

# Compare Period 1 and Period 2 values
comparison_results = []

for col in compare_columns:

    # Extract measurements from both periods
    p1 = overlap_comparison[f"{col}_p1"]
    p2 = overlap_comparison[f"{col}_p2"]

    # Count how the measurements compare
    comparison_results.append({
        "Measurement": col,
        "Period 2 Higher": (p2 > p1).sum(),
        "Period 1 Higher": (p1 > p2).sum(),
        "Equal Values": (p1 == p2).sum()
    })

# Create a summary table
comparison_summary = pd.DataFrame(
    comparison_results
)

print("Comparison of 24 Overlapping Records:")
display(comparison_summary)

# Display all 24 participants for closer inspection
print("\nDetailed Step and Calorie Comparison:")

display(
    overlap_comparison[
        [
            "Id",
            "ActivityDate",
            "TotalSteps_p1",
            "TotalSteps_p2",
            "Calories_p1",
            "Calories_p2"
        ]
    ]
)

Comparison of 24 Overlapping Records:

     Measurement  Period 2 Higher  Period 1 Higher  Equal Values
0     TotalSteps               24                0             0
1  TotalDistance               24                0             0
2       Calories               24                0             0

Detailed Step and Calorie Comparison:

,Id,ActivityDate,TotalSteps_p1,TotalSteps_p2,Calories_p1,Calories_p2
0,1503960366,2016-04-12,224,13162,50,1985
1,1624580081,2016-04-12,6627,8163,706,1432
2,1844505072,2016-04-12,0,6697,399,2030
3,1927972279,2016-04-12,24,678,942,2220
4,2022484408,2016-04-12,6717,11875,1140,2390
5,2026352035,2016-04-12,1019,4414,600,1459
6,2320127002,2016-04-12,2098,10725,790,2124
7,2347167796,2016-04-12,0,10113,399,2344
8,2873212765,2016-04-12,0,8796,0,1982
9,3977333714,2016-04-12,759,8856,182,1450
10,4020332650,2016-04-12,8,8539,446,3654
11,4057192912,2016-04-12,187,5394,538,2286
12,4445114986,2016-04-12,278,3276,745,2113
13,4558609924,2016-04-12,1260,5135,722,1909
14,4702921684,2016-04-12,0,7213,0,2947
15,5553957443,2016-04-12,3436,11596,633,2026
16,6962181067,2016-04-12,5893,10199,917,1994
17,7007744171,2016-04-12,7413,14172,1023,2937
18,7086361926,2016-04-12,430,11317,625,2772
19,8053475328,2016-04-12,290,18060,791,3186
20,8253242879,2016-04-12,0,9033,0,2044
21,8378563200,2016-04-12,3246,7626,1882,3635
22,8792009665,2016-04-12,20,2564,728,2044
23,8877689391,2016-04-12,2350,23186,938,3921

In [17]:
# Step 2E.5: Resolve overlapping daily activity records

# Create copies and label their source periods
daily_p1 = daily_check_1.copy()
daily_p2 = daily_check_2.copy()

daily_p1["SourcePeriod"] = "Period 1"
daily_p2["SourcePeriod"] = "Period 2"

# Combine both datasets
daily_combined = pd.concat(
    [daily_p1, daily_p2],
    ignore_index=True
)

# Record the number of observations before cleaning
rows_before = len(daily_combined)

# Retain Period 2 for overlapping participant-date records
# Period 2 was appended last, so keep='last' gives it priority
daily_combined = daily_combined.drop_duplicates(
    subset=["Id", "ActivityDate"],
    keep="last"
).reset_index(drop=True)

# Record the number of observations after cleaning
rows_after = len(daily_combined)

# Validate the results
remaining_duplicates = daily_combined.duplicated(
    subset=["Id", "ActivityDate"]
).sum()

print("Records before cleaning:", rows_before)
print("Records after cleaning:", rows_after)
print("Overlapping records resolved:", rows_before - rows_after)
print("Remaining participant-date duplicates:", remaining_duplicates)

# Confirm the source retained for overlapping records
retained = daily_combined.merge(
    overlapping_records,
    on=["Id", "ActivityDate"],
    how="inner"
)

print("\nSource of retained overlapping records:")
print(retained["SourcePeriod"].value_counts())

# Ensure no participant-date duplicates remain
assert remaining_duplicates == 0

Records before cleaning: 1397
Records after cleaning: 1373
Overlapping records resolved: 24
Remaining participant-date duplicates: 0

Source of retained overlapping records:
SourcePeriod
Period 2    24
Name: count, dtype: int64

**Overlapping Records:** The two daily activity datasets contained 24 overlapping participant-date observations on April 12, 2016. All 24 Period 2 records reported higher total steps, distance, and calories than their Period 1 counterparts. This pattern suggests that Period 1 contains incomplete daily measurements for the overlapping date. Therefore, Period 2 was prioritized when resolving overlapping records. The original datasets were preserved, and the decision was documented for transparency.

In [18]:
# Step 2F.1: Inspect invalid and unexpected values

# Identify activity measurement columns
# Exclude participant IDs, dates, and source labels
measurement_columns = daily_combined.select_dtypes(
    include="number"
).columns.drop("Id")

# Create a numeric quality summary
numeric_summary = pd.DataFrame({
    "Minimum": daily_combined[measurement_columns].min(),
    "Maximum": daily_combined[measurement_columns].max(),
    "Zero Values": (
        daily_combined[measurement_columns] == 0
    ).sum(),
    "Negative Values": (
        daily_combined[measurement_columns] < 0
    ).sum()
})

# Display results
print("Daily Activity Numeric Quality Summary:")
display(numeric_summary)

# Check whether recorded activity minutes exceed 24 hours
minute_columns = [
    "VeryActiveMinutes",
    "FairlyActiveMinutes",
    "LightlyActiveMinutes",
    "SedentaryMinutes"
]

# Calculate total recorded minutes per participant-day
total_minutes = daily_combined[minute_columns].sum(axis=1)

print("\nActivity Minute Validation:")
print("Days exceeding 1440 minutes:",
      (total_minutes > 1440).sum())

print("Days with zero recorded minutes:",
      (total_minutes == 0).sum())

# Check zero steps and calories
print("\nAdditional Checks:")
print("Days with zero steps:",
      (daily_combined["TotalSteps"] == 0).sum())

print("Days with zero calories:",
      (daily_combined["Calories"] == 0).sum())

Daily Activity Numeric Quality Summary:

                          Minimum       Maximum  Zero Values  Negative Values
TotalSteps                    0.0  36019.000000          133                0
TotalDistance                 0.0     28.030001          136                0
TrackerDistance               0.0     28.030001          139                0
LoggedActivitiesDistance      0.0      6.727057         1319                0
VeryActiveDistance            0.0     21.920000          639                0
ModeratelyActiveDistance      0.0      6.480000          595                0
LightActiveDistance           0.0     12.510000          154                0
SedentaryActiveDistance       0.0      0.110000         1253                0
VeryActiveMinutes             0.0    210.000000          631                0
FairlyActiveMinutes           0.0    660.000000          592                0
LightlyActiveMinutes          0.0    720.000000          151                0
SedentaryMinutes              0.0   1440.000000            1                0
Calories                      0.0   4900.000000            6                0

Activity Minute Validation:
Days exceeding 1440 minutes: 0
Days with zero recorded minutes: 0

Additional Checks:
Days with zero steps: 133
Days with zero calories: 6

In [19]:

# Step 2F.2: Investigate zero-calorie observations

# Create a copy for further investigation
daily_inspection = daily_combined.copy()

# Calculate total recorded activity minutes
daily_inspection["TotalRecordedMinutes"] = (
    daily_inspection[
        [
            "VeryActiveMinutes",
            "FairlyActiveMinutes",
            "LightlyActiveMinutes",
            "SedentaryMinutes"
        ]
    ].sum(axis=1)
)

# Identify records with zero calories
zero_calories = daily_inspection[
    daily_inspection["Calories"] == 0
]

# Display relevant measurements
print("Records with Zero Calories:")

display(
    zero_calories[
        [
            "Id",
            "ActivityDate",
            "TotalSteps",
            "TotalDistance",
            "VeryActiveMinutes",
            "FairlyActiveMinutes",
            "LightlyActiveMinutes",
            "SedentaryMinutes",
            "TotalRecordedMinutes",
            "Calories",
            "SourcePeriod"
        ]
    ]
)

# Check whether these records also have zero steps
print("\nZero-calorie records with zero steps:",
      (zero_calories["TotalSteps"] == 0).sum())

print("Zero-calorie records with positive steps:",
      (zero_calories["TotalSteps"] > 0).sum())

# Check days with zero steps but positive calories
print("\nZero-step records with positive calories:",
      (
          (daily_inspection["TotalSteps"] == 0) &
          (daily_inspection["Calories"] > 0)
      ).sum())

Records with Zero Calories:

,Id,ActivityDate,TotalSteps,TotalDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,TotalRecordedMinutes,Calories,SourcePeriod
228,4319703577,2016-04-09,0,0.0,0,0,0,1440,1440,0,Period 1
307,6117666160,2016-04-10,0,0.0,0,0,0,1440,1440,0,Period 1
463,1503960366,2016-05-12,0,0.0,0,0,0,1440,1440,0,Period 2
1086,6290855005,2016-05-10,0,0.0,0,0,0,1440,1440,0,Period 2
1250,8253242879,2016-04-30,0,0.0,0,0,0,1440,1440,0,Period 2
1312,8583815059,2016-05-12,0,0.0,0,0,0,1440,1440,0,Period 2

Zero-calorie records with zero steps: 6
Zero-calorie records with positive steps: 0

Zero-step records with positive calories: 127

In [21]:
# Step 2F.3: Investigate zero-step records
# with positive calories

# Identify zero-step records with positive calories
zero_step_positive = daily_inspection[
    (daily_inspection["TotalSteps"] == 0) &
    (daily_inspection["Calories"] > 0)
].copy()

# Display total observations
print("Zero-step records with positive calories:",
      len(zero_step_positive))

# Summarize calorie measurements
print("\nCalorie Summary:")
display(
    zero_step_positive["Calories"].describe().round(2)
)

# Examine recorded activity minutes
print("\nRecorded Activity Minutes:")
display(
    zero_step_positive["TotalRecordedMinutes"]
    .describe().round(2)
)

# Check how many records contain 1440 sedentary minutes
print("\nRecords with 1440 sedentary minutes:",
      (zero_step_positive["SedentaryMinutes"] == 1440).sum())

# Count unique participants
print("Unique participants:",
      zero_step_positive["Id"].nunique())

# Compare the two collection periods
print("\nRecords by Source Period:")
display(
    zero_step_positive["SourcePeriod"].value_counts()
)

# Preview selected records
print("\nPreview of Zero-Step Records:")
display(
    zero_step_positive[
        [
            "Id",
            "ActivityDate",
            "TotalSteps",
            "SedentaryMinutes",
            "TotalRecordedMinutes",
            "Calories",
            "SourcePeriod"
        ]
    ].head(15)
)

Zero-step records with positive calories: 127

Calorie Summary:

count     127.00
mean     1754.91
std       460.61
min        57.00
25%      1496.50
50%      1820.00
75%      1980.00
max      4562.00
Name: Calories, dtype: float64

Recorded Activity Minutes:

count     127.00
mean     1382.45
std       239.59
min        48.00
25%      1440.00
50%      1440.00
75%      1440.00
max      1440.00
Name: TotalRecordedMinutes, dtype: float64

Records with 1440 sedentary minutes: 116
Unique participants: 17

Records by Source Period:

SourcePeriod
Period 2    73
Period 1    54
Name: count, dtype: int64

Preview of Zero-Step Records:

,Id,ActivityDate,TotalSteps,SedentaryMinutes,TotalRecordedMinutes,Calories,SourcePeriod
49,1844505072,2016-04-04,0,669,669,1347,Period 1
50,1844505072,2016-04-05,0,1440,1440,1347,Period 1
90,2320127002,2016-04-01,0,1440,1440,1324,Period 1
91,2320127002,2016-04-02,0,1440,1440,1324,Period 1
92,2320127002,2016-04-03,0,1440,1440,1324,Period 1
93,2320127002,2016-04-04,0,1440,1440,1324,Period 1
126,2891001357,2016-03-29,0,1440,1440,1920,Period 1
127,2891001357,2016-03-30,0,1440,1440,1920,Period 1
128,2891001357,2016-03-31,0,1440,1440,1920,Period 1
129,2891001357,2016-04-01,0,780,1440,4562,Period 1
131,2891001357,2016-04-03,0,1440,1440,1920,Period 1
132,2891001357,2016-04-04,0,1440,1440,1920,Period 1
186,4057192912,2016-03-12,0,1440,1440,1777,Period 1
187,4057192912,2016-03-13,0,1440,1440,1777,Period 1
189,4057192912,2016-03-15,0,1440,1440,1776,Period 1

In [22]:
# Step 2F.4: Investigate unusual zero-step records

# Identify records with fewer than 1440 sedentary minutes
unusual_zero_steps = zero_step_positive[
    zero_step_positive["SedentaryMinutes"] < 1440
].copy()

# Display number of unusual records
print("Zero-step records with fewer than 1440 sedentary minutes:",
      len(unusual_zero_steps))

# Display the relevant measurements
display(
    unusual_zero_steps[
        [
            "Id",
            "ActivityDate",
            "TotalSteps",
            "TotalDistance",
            "VeryActiveMinutes",
            "FairlyActiveMinutes",
            "LightlyActiveMinutes",
            "SedentaryMinutes",
            "TotalRecordedMinutes",
            "Calories",
            "SourcePeriod"
        ]
    ]
)

# Identify zero-step records with positive active minutes
active_columns = [
    "VeryActiveMinutes",
    "FairlyActiveMinutes",
    "LightlyActiveMinutes"
]

active_with_zero_steps = (
    zero_step_positive[active_columns].sum(axis=1) > 0
)

print("\nZero-step records with positive active minutes:",
      active_with_zero_steps.sum())

# Count zero-step records with fewer than 1440 total minutes
print("Zero-step records with fewer than 1440 recorded minutes:",
      (zero_step_positive["TotalRecordedMinutes"] < 1440).sum())

# Identify unusually low calorie values
print("Zero-step records with fewer than 500 calories:",
      (zero_step_positive["Calories"] < 500).sum())

Zero-step records with fewer than 1440 sedentary minutes: 11

,Id,ActivityDate,TotalSteps,TotalDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,TotalRecordedMinutes,Calories,SourcePeriod
49,1844505072,2016-04-04,0,0.0,0,0,0,669,669,1347,Period 1
129,2891001357,2016-04-01,0,0.0,0,660,0,780,1440,4562,Period 1
236,4388161847,2016-04-05,0,0.0,0,0,0,994,994,1296,Period 1
310,6290855005,2016-04-03,0,0.0,33,0,0,1407,1440,2664,Period 1
317,6290855005,2016-04-10,0,0.0,20,0,0,494,514,735,Period 1
326,6391747486,2016-04-09,0,0.0,0,0,0,198,198,251,Period 1
555,1844505072,2016-05-12,0,0.0,0,0,0,711,711,665,Period 2
586,1927972279,2016-05-12,0,0.0,0,0,0,966,966,1383,Period 2
1069,6290855005,2016-04-23,0,0.0,33,0,0,1407,1440,2664,Period 2
1169,7007744171,2016-05-07,0,0.0,0,0,0,111,111,120,Period 2
1341,8792009665,2016-05-10,0,0.0,0,0,0,48,48,57,Period 2

Zero-step records with positive active minutes: 4
Zero-step records with fewer than 1440 recorded minutes: 8
Zero-step records with fewer than 500 calories: 3

In [24]:
# Step 2F.5: Create data quality flags

# Preserve all consolidated records
daily_final = daily_inspection.copy()

# Flag observations with zero calories
daily_final["FlagZeroCalories"] = (
    daily_final["Calories"] == 0
)

# Flag observations with zero steps
daily_final["FlagZeroSteps"] = (
    daily_final["TotalSteps"] == 0
)

# Flag days with fewer than 1440 recorded minutes
daily_final["FlagIncompleteMinutes"] = (
    daily_final["TotalRecordedMinutes"] < 1440
)

# Flag records with zero steps but positive active minutes
active_columns = [
    "VeryActiveMinutes",
    "FairlyActiveMinutes",
    "LightlyActiveMinutes"
]

daily_final["FlagActivityWithoutSteps"] = (
    (daily_final["TotalSteps"] == 0) &
    (daily_final[active_columns].sum(axis=1) > 0)
)

# Create a separate dataset for calorie analysis
# Exclude zero-calorie observations only
daily_calorie_analysis = daily_final[
    ~daily_final["FlagZeroCalories"]
].copy()

# Display record counts
print("Consolidated records:", len(daily_final))

print("Records for primary calorie analysis:",
      len(daily_calorie_analysis))

print("\nQuality Flag Summary:")

flag_columns = [
    "FlagZeroCalories",
    "FlagZeroSteps",
    "FlagIncompleteMinutes",
    "FlagActivityWithoutSteps"
]

display(
    daily_final[flag_columns]
    .sum()
    .to_frame(name="Flagged Records")
)

# Validate that original records are preserved
assert len(daily_final) == 1373

# Validate the primary calorie-analysis subset
assert len(daily_calorie_analysis) == 1367

Consolidated records: 1373
Records for primary calorie analysis: 1367

Quality Flag Summary:

                          Flagged Records
FlagZeroCalories                        6
FlagZeroSteps                         133
FlagIncompleteMinutes                 665
FlagActivityWithoutSteps                4

**Data Quality — Daily Activity Measurements**

The consolidated daily activity dataset contained 1,373 unique participant-date observations after resolving overlapping records between the two collection periods.

Data-quality inspections identified 133 observations with zero steps, including six observations with zero calories. The remaining 127 zero-step observations contained positive calorie estimates.

Further examination of these 127 observations identified 11 records with fewer than 1,440 sedentary minutes, eight with fewer than 1,440 total recorded activity-category minutes, four with positive active minutes despite zero steps, and three with calorie estimates below 500.

Quality flags were created to identify potentially incomplete or inconsistent observations without permanently removing them from the consolidated dataset. The six zero-calorie records were excluded from the primary calorie-analysis subset, while the original consolidated observations were retained for additional analysis and validation.

In [25]:
# Step 2G: Final validation of daily activity data

# Rename the flag to avoid assuming incomplete tracking
daily_final = daily_final.rename(
    columns={
        "FlagIncompleteMinutes": "FlagMinutesBelow1440"
    }
)

# Update the calorie-analysis subset
daily_calorie_analysis = daily_final[
    ~daily_final["FlagZeroCalories"]
].copy()

# Check total records
print("Total consolidated records:", len(daily_final))

print("Calorie-analysis records:",
      len(daily_calorie_analysis))

# Check duplicate participant-date combinations
duplicates = daily_final.duplicated(
    subset=["Id", "ActivityDate"]
).sum()

print("\nRemaining participant-date duplicates:",
      duplicates)

# Check for missing dates
missing_dates = daily_final["ActivityDate"].isna().sum()

print("Missing or invalid dates:", missing_dates)

# Check date format
print("ActivityDate data type:",
      daily_final["ActivityDate"].dtype)

# Summarize quality flags by source period
print("\nQuality Flags by Source Period:")

display(
    daily_final.groupby("SourcePeriod").agg(
        TotalRecords=("Id", "size"),
        ZeroCalories=("FlagZeroCalories", "sum"),
        ZeroSteps=("FlagZeroSteps", "sum"),
        MinutesBelow1440=("FlagMinutesBelow1440", "sum"),
        ActivityWithoutSteps=("FlagActivityWithoutSteps", "sum")
    )
)

# Validate our cleaning results
assert len(daily_final) == 1373
assert len(daily_calorie_analysis) == 1367
assert duplicates == 0
assert missing_dates == 0
assert daily_final["FlagZeroCalories"].sum() == 6
assert daily_final["FlagZeroSteps"].sum() == 133
assert daily_final["FlagMinutesBelow1440"].sum() == 665
assert daily_final["FlagActivityWithoutSteps"].sum() == 4

print("\nAll validation checks passed!")

Total consolidated records: 1373
Calorie-analysis records: 1367

Remaining participant-date duplicates: 0
Missing or invalid dates: 0
ActivityDate data type: datetime64[ns]

Quality Flags by Source Period:

,TotalRecords,ZeroCalories,ZeroSteps,MinutesBelow1440,ActivityWithoutSteps
SourcePeriod,,,,,
Period 1,433,2,56,203,3
Period 2,940,4,77,462,1

All validation checks passed!

In [26]:
# Step 2H.1: Create a folder for cleaned datasets

# Locate the main Bellabeat project folder
project_root = project_path.parent

# Define the cleaned data folder
cleaned_path = project_root / "Cleaned_Data"

# Create the folder if it does not already exist
cleaned_path.mkdir(parents=True, exist_ok=True)

# Verify the folder was created
print("Cleaned Data Folder:", cleaned_path)
print("Folder exists:", cleaned_path.exists())

Cleaned Data Folder: /Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data
Folder exists: True

In [27]:
# Step 2H.2: Export cleaned daily activity datasets

# Create export copies to preserve working DataFrames
daily_export = daily_final.copy()
calorie_export = daily_calorie_analysis.copy()

# Sort records by participant and activity date
daily_export = daily_export.sort_values(
    ["Id", "ActivityDate"]
)

calorie_export = calorie_export.sort_values(
    ["Id", "ActivityDate"]
)

# Define output file paths
daily_output = cleaned_path / "dailyActivity_clean.csv"

calorie_output = (
    cleaned_path / "dailyActivity_calorie_analysis.csv"
)

# Save datasets as CSV files
daily_export.to_csv(daily_output, index=False)

calorie_export.to_csv(calorie_output, index=False)

# Confirm the files were saved
print("Files successfully exported:\n")

print("Daily Activity:", daily_output)
print("Calorie Analysis:", calorie_output)

print("\nExported record counts:")
print("Daily Activity:", len(daily_export))
print("Calorie Analysis:", len(calorie_export))

Files successfully exported:

Daily Activity: /Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/dailyActivity_clean.csv
Calorie Analysis: /Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/dailyActivity_calorie_analysis.csv

Exported record counts:
Daily Activity: 1373
Calorie Analysis: 1367

In [28]:
# Step 2H.3: Verify exported CSV files

# Reload the exported datasets
verify_daily = pd.read_csv(
    daily_output,
    parse_dates=["ActivityDate"]
)

verify_calorie = pd.read_csv(
    calorie_output,
    parse_dates=["ActivityDate"]
)

# Verify row counts
assert len(verify_daily) == 1373
assert len(verify_calorie) == 1367

# Verify participant-date uniqueness
assert not verify_daily.duplicated(
    subset=["Id", "ActivityDate"]
).any()

# Verify date values
assert verify_daily["ActivityDate"].notna().all()

# Verify quality flag counts
assert verify_daily["FlagZeroCalories"].sum() == 6

print("Export verification successful!")

print("\nDaily Activity Shape:", verify_daily.shape)
print("Calorie Analysis Shape:", verify_calorie.shape)

Export verification successful!

Daily Activity Shape: (1373, 21)
Calorie Analysis Shape: (1367, 21)

## Step 3: Hourly Steps Data Processing

In [29]:
# Step 3A: Import hourly steps datasets

# Identify the two hourlySteps CSV files
hourly_files = [
    file for file in selected_files
    if file.stem == "hourlySteps_merged"
]

# Identify each collection period
hourly_period1_path = next(
    file for file in hourly_files
    if file.parent.name == "Fitabase Data 3.12.16-4.11.16"
)

hourly_period2_path = next(
    file for file in hourly_files
    if file.parent.name == "Fitabase Data 4.12.16-5.12.16"
)

# Import the CSV files into pandas
hourly_1 = pd.read_csv(hourly_period1_path)
hourly_2 = pd.read_csv(hourly_period2_path)

# Display dataset dimensions
print("Period 1 Shape:", hourly_1.shape)
print("Period 2 Shape:", hourly_2.shape)

# Preview the first five records
print("\nPeriod 1 Preview:")
display(hourly_1.head())

print("\nPeriod 2 Preview:")
display(hourly_2.head())

# Check whether column names match
print("\nColumn names match:",
      hourly_1.columns.equals(hourly_2.columns))

Period 1 Shape: (24084, 3)
Period 2 Shape: (22099, 3)

Period 1 Preview:

           Id           ActivityHour  StepTotal
0  1503960366  3/12/2016 12:00:00 AM          0
1  1503960366   3/12/2016 1:00:00 AM          0
2  1503960366   3/12/2016 2:00:00 AM          0
3  1503960366   3/12/2016 3:00:00 AM          0
4  1503960366   3/12/2016 4:00:00 AM          0

Period 2 Preview:

           Id           ActivityHour  StepTotal
0  1503960366  4/12/2016 12:00:00 AM        373
1  1503960366   4/12/2016 1:00:00 AM        160
2  1503960366   4/12/2016 2:00:00 AM        151
3  1503960366   4/12/2016 3:00:00 AM          0
4  1503960366   4/12/2016 4:00:00 AM          0

Column names match: True

In [30]:
# Step 3B: Inspect data types and missing values

# Display dataset information
print("Period 1 Information:")
hourly_1.info()

print("\nPeriod 2 Information:")
hourly_2.info()

# Calculate missing values for each dataset
missing_hourly_1 = hourly_1.isna().sum()
missing_hourly_2 = hourly_2.isna().sum()

# Calculate missing percentages
missing_pct_1 = (
    missing_hourly_1 / len(hourly_1)
) * 100

missing_pct_2 = (
    missing_hourly_2 / len(hourly_2)
) * 100

# Create a missing-value comparison table
hourly_missing_summary = pd.DataFrame({
    "Period 1 Missing": missing_hourly_1,
    "Period 1 Missing (%)": missing_pct_1,
    "Period 2 Missing": missing_hourly_2,
    "Period 2 Missing (%)": missing_pct_2
})

# Display results
print("\nMissing Value Summary:")
display(hourly_missing_summary.round(2))

# Display total missing values
print("\nTotal Missing Values:")
print("Period 1:", missing_hourly_1.sum())
print("Period 2:", missing_hourly_2.sum())

Period 1 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24084 entries, 0 to 24083
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            24084 non-null  int64
 1   ActivityHour  24084 non-null  object
 2   StepTotal     24084 non-null  int64
dtypes: int64(2), object(1)
memory usage: 564.6+ KB

Period 2 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            22099 non-null  int64
 1   ActivityHour  22099 non-null  object
 2   StepTotal     22099 non-null  int64
dtypes: int64(2), object(1)
memory usage: 518.1+ KB

Missing Value Summary:

,Period 1 Missing,Period 1 Missing (%),Period 2 Missing,Period 2 Missing (%)
Id,0,0.0,0,0.0
ActivityHour,0,0.0,0,0.0
StepTotal,0,0.0,0,0.0

Total Missing Values:
Period 1: 0
Period 2: 0

In [31]:
# Step 3C: Identify duplicate hourly step records

# Create copies to preserve the original imported datasets
hourly_check_1 = hourly_1.copy()
hourly_check_2 = hourly_2.copy()

# Convert ActivityHour from text to datetime
for df in [hourly_check_1, hourly_check_2]:
    df["ActivityHour"] = pd.to_datetime(
        df["ActivityHour"],
        format="%m/%d/%Y %I:%M:%S %p",
        errors="coerce"
    )

# Check for invalid timestamp conversions
print("Invalid or Missing Timestamps:")
print("Period 1:",
      hourly_check_1["ActivityHour"].isna().sum())
print("Period 2:",
      hourly_check_2["ActivityHour"].isna().sum())

# Stop if any timestamps could not be converted
assert hourly_check_1["ActivityHour"].notna().all()
assert hourly_check_2["ActivityHour"].notna().all()

# Define participant-hour identifier
key_columns = ["Id", "ActivityHour"]

# Check exact duplicate rows
print("\nExact Duplicate Records:")
print("Period 1:", hourly_check_1.duplicated().sum())
print("Period 2:", hourly_check_2.duplicated().sum())

# Check duplicate participant-hour combinations
print("\nDuplicate Participant-Hour Records:")
print("Period 1:",
      hourly_check_1.duplicated(subset=key_columns).sum())
print("Period 2:",
      hourly_check_2.duplicated(subset=key_columns).sum())

# Display duplicate records, if any
for label, df in [
    ("Period 1", hourly_check_1),
    ("Period 2", hourly_check_2)
]:
    print(f"\n{label} Duplicate Details:")

    duplicates = df[
        df.duplicated(
            subset=key_columns,
            keep=False
        )
    ].sort_values(key_columns)

    display(duplicates.head(20))

Invalid or Missing Timestamps:
Period 1: 0
Period 2: 0

Exact Duplicate Records:
Period 1: 0
Period 2: 0

Duplicate Participant-Hour Records:
Period 1: 0
Period 2: 0

Period 1 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityHour, StepTotal]
Index: []

Period 2 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityHour, StepTotal]
Index: []

In [32]:
# Step 3D.1: Inspect hourly dataset date ranges

# Display earliest and latest timestamps
print("Period 1 Date Range:")
print("Earliest:", hourly_check_1["ActivityHour"].min())
print("Latest:", hourly_check_1["ActivityHour"].max())

print("\nPeriod 2 Date Range:")
print("Earliest:", hourly_check_2["ActivityHour"].min())
print("Latest:", hourly_check_2["ActivityHour"].max())

# Count unique participants
print("\nUnique Participants:")
print("Period 1:", hourly_check_1["Id"].nunique())
print("Period 2:", hourly_check_2["Id"].nunique())

# Count unique calendar dates
print("\nUnique Calendar Dates:")
print("Period 1:",
      hourly_check_1["ActivityHour"].dt.date.nunique())

print("Period 2:",
      hourly_check_2["ActivityHour"].dt.date.nunique())

Period 1 Date Range:
Earliest: 2016-03-12 00:00:00
Latest: 2016-04-12 10:00:00

Period 2 Date Range:
Earliest: 2016-04-12 00:00:00
Latest: 2016-05-12 15:00:00

Unique Participants:
Period 1: 34
Period 2: 33

Unique Calendar Dates:
Period 1: 32
Period 2: 31

In [33]:
# Step 3D.2: Identify overlapping hourly observations

# Define the participant-hour identifier
hourly_keys = ["Id", "ActivityHour"]

# Find participant-hour combinations in both datasets
hourly_overlap = hourly_check_1.merge(
    hourly_check_2,
    on=hourly_keys,
    how="inner",
    suffixes=("_p1", "_p2"),
    validate="one_to_one"
)

# Count overlapping observations
print("Total overlapping participant-hour records:",
      len(hourly_overlap))

# Compare hourly step counts
matching_steps = (
    hourly_overlap["StepTotal_p1"] ==
    hourly_overlap["StepTotal_p2"]
)

print("\nOverlapping records with matching steps:",
      matching_steps.sum())

print("Overlapping records with different steps:",
      (~matching_steps).sum())

# Display sample overlapping observations
print("\nPreview of Overlapping Records:")
display(hourly_overlap.head(15))

# Display which calendar dates contain overlaps
print("\nOverlapping Calendar Dates:")
print(
    hourly_overlap["ActivityHour"]
    .dt.date
    .value_counts()
    .sort_index()
)

Total overlapping participant-hour records: 175

Overlapping records with matching steps: 175
Overlapping records with different steps: 0

Preview of Overlapping Records:

            Id        ActivityHour  StepTotal_p1  StepTotal_p2
0   1624580081 2016-04-12 00:00:00            31            31
1   1624580081 2016-04-12 01:00:00             0             0
2   1624580081 2016-04-12 02:00:00             0             0
3   1624580081 2016-04-12 03:00:00             7             7
4   1624580081 2016-04-12 04:00:00             0             0
5   1624580081 2016-04-12 05:00:00             0             0
6   1624580081 2016-04-12 06:00:00             0             0
7   1624580081 2016-04-12 07:00:00             0             0
8   1624580081 2016-04-12 08:00:00             0             0
9   1624580081 2016-04-12 09:00:00          1085          1085
10  1624580081 2016-04-12 10:00:00          5375          5375
11  1844505072 2016-04-12 00:00:00             0             0
12  1844505072 2016-04-12 01:00:00             0             0
13  1844505072 2016-04-12 02:00:00             0             0
14  1844505072 2016-04-12 03:00:00             0             0

Overlapping Calendar Dates:
ActivityHour
2016-04-12    175
Name: count, dtype: int64

In [34]:
# Step 3D.3: Combine hourly steps datasets

# Create copies to preserve the original DataFrames
hourly_p1 = hourly_check_1.copy()
hourly_p2 = hourly_check_2.copy()

# Label the source period
hourly_p1["SourcePeriod"] = "Period 1"
hourly_p2["SourcePeriod"] = "Period 2"

# Combine both datasets
hourly_combined = pd.concat(
    [hourly_p1, hourly_p2],
    ignore_index=True
)

# Record the number of observations before cleaning
rows_before = len(hourly_combined)

# Remove overlapping participant-hour observations
# Period 2 is appended last, so it takes priority
hourly_combined = hourly_combined.drop_duplicates(
    subset=["Id", "ActivityHour"],
    keep="last"
)

# Sort observations by participant and timestamp
hourly_combined = hourly_combined.sort_values(
    ["Id", "ActivityHour"]
).reset_index(drop=True)

# Record the number of observations after cleaning
rows_after = len(hourly_combined)

# Check for remaining duplicate observations
remaining_duplicates = hourly_combined.duplicated(
    subset=["Id", "ActivityHour"]
).sum()

# Display cleaning results
print("Records before cleaning:", rows_before)
print("Records after cleaning:", rows_after)
print("Overlapping records removed:", rows_before - rows_after)
print("Remaining participant-hour duplicates:", remaining_duplicates)

# Display retained records by source period
print("\nRecords by Source Period:")
print(hourly_combined["SourcePeriod"].value_counts())

# Verify that overlapping records came from Period 2
retained_overlap = hourly_combined.merge(
    hourly_overlap[["Id", "ActivityHour"]],
    on=["Id", "ActivityHour"],
    how="inner",
    validate="one_to_one"
)

print("\nSource of retained overlapping records:")
print(retained_overlap["SourcePeriod"].value_counts())

# Validate record counts and uniqueness
assert rows_after == 46008
assert remaining_duplicates == 0
assert (retained_overlap["SourcePeriod"] == "Period 2").all()

print("\nOverlap resolution successful!")

Records before cleaning: 46183
Records after cleaning: 46008
Overlapping records removed: 175
Remaining participant-hour duplicates: 0

Records by Source Period:
SourcePeriod
Period 1    23909
Period 2    22099
Name: count, dtype: int64

Source of retained overlapping records:
SourcePeriod
Period 2    175
Name: count, dtype: int64

Overlap resolution successful!

**Overlapping Records — Hourly Steps**

The two hourly steps datasets contained 175 overlapping participant-hour observations on April 12, 2016. All overlapping observations reported identical step counts across both collection periods.

To prevent duplicate counting, Period 2 was prioritized when consolidating the datasets. One copy of each overlapping participant-hour observation was retained, while all nonoverlapping records were preserved.

This procedure reduced the combined dataset from 46,183 to 46,008 records without removing any unique participant-hour observations.

In [36]:
# Step 3E.1: Inspect invalid and unusual hourly step values

# Create a copy for data quality inspection
hourly_inspection = hourly_combined.copy()

# Calculate summary statistics
print("Hourly Step Summary Statistics:")

display(
    hourly_inspection["StepTotal"]
    .describe()
    .round(2)
)

# Identify negative step counts
negative_steps = (
    hourly_inspection["StepTotal"] < 0
).sum()

# Identify zero-step hours
zero_steps = (
    hourly_inspection["StepTotal"] == 0
).sum()

# Calculate percentage of zero-step hours
zero_pct = (
    zero_steps / len(hourly_inspection)
) * 100

# Flag unusually high hourly step counts
# 5000 is an exploratory threshold, not a validity limit
high_steps = (
    hourly_inspection["StepTotal"] > 5000
).sum()

# Display quality summary
print("\nHourly Step Quality Checks:")

print("Negative step records:", negative_steps)
print("Zero-step records:", zero_steps)
print("Zero-step percentage:", round(zero_pct, 2), "%")
print("Records exceeding 5000 steps:", high_steps)

# Display the 10 highest hourly step counts
print("\nTop 10 Highest Hourly Step Counts:")

display(
    hourly_inspection[
        ["Id", "ActivityHour", "StepTotal", "SourcePeriod"]
    ]
    .sort_values(
        "StepTotal",
        ascending=False
    )
    .head(10)
)

Hourly Step Summary Statistics:

count    46008.00
mean       302.87
std        677.30
min          0.00
25%          0.00
50%         21.00
75%        323.00
max      10565.00
Name: StepTotal, dtype: float64

Hourly Step Quality Checks:
Negative step records: 0
Zero-step records: 20478
Zero-step percentage: 44.51 %
Records exceeding 5000 steps: 134

Top 10 Highest Hourly Step Counts:

               Id        ActivityHour  StepTotal SourcePeriod
45236  8877689391 2016-04-10 11:00:00      10565     Period 1
45719  8877689391 2016-04-30 14:00:00      10554     Period 2
44904  8877689391 2016-03-27 15:00:00      10141     Period 1
44811  8877689391 2016-03-23 18:00:00      10076     Period 1
44905  8877689391 2016-03-27 16:00:00      10018     Period 1
45863  8877689391 2016-05-06 14:00:00       9769     Period 2
45100  8877689391 2016-04-04 19:00:00       9557     Period 1
45457  8877689391 2016-04-19 16:00:00       9392     Period 2
45049  8877689391 2016-04-02 16:00:00       9292     Period 1
44543  8877689391 2016-03-12 14:00:00       9149     Period 1

In [37]:
# Step 3E.2: Identify gaps in hourly observations

# Create a copy and sort by participant and timestamp
hourly_gap_check = hourly_combined.sort_values(
    ["Id", "ActivityHour"]
).copy()

# Identify each participant's previous recorded hour
hourly_gap_check["PreviousHour"] = (
    hourly_gap_check.groupby("Id")["ActivityHour"].shift()
)

# Calculate the time difference between consecutive records
hourly_gap_check["HourDifference"] = (
    (
        hourly_gap_check["ActivityHour"] -
        hourly_gap_check["PreviousHour"]
    ).dt.total_seconds() / 3600
)

# Identify gaps greater than one hour
hourly_gaps = hourly_gap_check[
    hourly_gap_check["HourDifference"] > 1
].copy()

# Calculate missing hourly slots between observations
hourly_gaps["MissingHoursBetween"] = (
    hourly_gaps["HourDifference"] - 1
).astype(int)

# Display summary results
print("Hourly Observation Gap Summary:")

print("Total gaps detected:", len(hourly_gaps))

print("Missing hourly slots between recorded observations:",
      hourly_gaps["MissingHoursBetween"].sum())

print("Participants with gaps:",
      hourly_gaps["Id"].nunique())

print("Total unique participants:",
      hourly_combined["Id"].nunique())

# Display the ten largest gaps
print("\nTop 10 Largest Gaps:")

display(
    hourly_gaps[
        [
            "Id",
            "PreviousHour",
            "ActivityHour",
            "MissingHoursBetween"
        ]
    ]
    .sort_values(
        "MissingHoursBetween",
        ascending=False
    )
    .head(10)
)

Hourly Observation Gap Summary:
Total gaps detected: 11
Missing hourly slots between recorded observations: 586
Participants with gaps: 11
Total unique participants: 35

Top 10 Largest Gaps:

               Id        PreviousHour ActivityHour  MissingHoursBetween
30670  6290855005 2016-04-02 16:00:00   2016-04-12                  223
42395  8583815059 2016-04-08 17:00:00   2016-04-12                   78
19991  4319703577 2016-04-08 22:00:00   2016-04-12                   73
32692  6775888955 2016-04-09 09:00:00   2016-04-12                   62
29489  6117666160 2016-04-09 22:00:00   2016-04-12                   49
3641   1644430081 2016-04-10 03:00:00   2016-04-12                   44
15100  3372868164 2016-04-10 14:00:00   2016-04-12                   33
28086  5577150313 2016-04-11 09:00:00   2016-04-12                   14
13641  2873212765 2016-04-11 19:00:00   2016-04-12                    4
39819  8253242879 2016-04-11 19:00:00   2016-04-12                    4

In [38]:
# Step 3E.2.2: Examine the dates of hourly gaps

# Create a copy of the identified gaps
gap_details = hourly_gaps.copy()

# Extract the calendar date where recording resumes
gap_details["ResumeDate"] = (
    gap_details["ActivityHour"].dt.date
)

# Summarize gaps by the date recording resumes
gap_summary = gap_details.groupby(
    "ResumeDate"
).agg(
    NumberOfGaps=("Id", "size"),
    MissingHourlySlots=("MissingHoursBetween", "sum")
).reset_index()

# Display gap summary
print("Hourly Gaps by Resume Date:")
display(gap_summary)

# Display all 11 gaps
print("\nComplete List of Hourly Gaps:")

display(
    gap_details[
        [
            "Id",
            "PreviousHour",
            "ActivityHour",
            "MissingHoursBetween",
            "SourcePeriod"
        ]
    ].sort_values(
        "MissingHoursBetween",
        ascending=False
    )
)

# Verify the total number of gaps and missing hours
print("\nFinal Gap Verification:")
print("Total gaps:", len(gap_details))
print(
    "Total missing hourly slots:",
    gap_details["MissingHoursBetween"].sum()
)

Hourly Gaps by Resume Date:

   ResumeDate  NumberOfGaps  MissingHourlySlots
0  2016-04-12            11                 586

Complete List of Hourly Gaps:

,Id,PreviousHour,ActivityHour,MissingHoursBetween,SourcePeriod
30670,6290855005,2016-04-02 16:00:00,2016-04-12,223,Period 2
42395,8583815059,2016-04-08 17:00:00,2016-04-12,78,Period 2
19991,4319703577,2016-04-08 22:00:00,2016-04-12,73,Period 2
32692,6775888955,2016-04-09 09:00:00,2016-04-12,62,Period 2
29489,6117666160,2016-04-09 22:00:00,2016-04-12,49,Period 2
3641,1644430081,2016-04-10 03:00:00,2016-04-12,44,Period 2
15100,3372868164,2016-04-10 14:00:00,2016-04-12,33,Period 2
28086,5577150313,2016-04-11 09:00:00,2016-04-12,14,Period 2
13641,2873212765,2016-04-11 19:00:00,2016-04-12,4,Period 2
39819,8253242879,2016-04-11 19:00:00,2016-04-12,4,Period 2
25151,4702921684,2016-04-11 21:00:00,2016-04-12,2,Period 2

Final Gap Verification:
Total gaps: 11
Total missing hourly slots: 586

In [39]:
# Step 3F.1: Create hourly steps quality flags

# Preserve the consolidated hourly steps dataset
hourly_final = hourly_combined.copy()

# Flag observations with zero steps
hourly_final["FlagZeroSteps"] = (
    hourly_final["StepTotal"] == 0
)

# Flag unusually high hourly step counts
# 5000 is a screening threshold, not an invalidity rule
hourly_final["FlagHighHourlySteps"] = (
    hourly_final["StepTotal"] > 5000
)

# Add information about previously identified gaps
hourly_final = hourly_final.merge(
    hourly_gaps[
        ["Id", "ActivityHour", "MissingHoursBetween"]
    ],
    on=["Id", "ActivityHour"],
    how="left",
    validate="one_to_one"
)

# Replace missing gap counts with zero
# This means no gap was detected before that row
hourly_final["MissingHoursBetween"] = (
    hourly_final["MissingHoursBetween"]
    .fillna(0)
    .astype(int)
)

# Flag observations immediately following a gap
hourly_final["FlagAfterGap"] = (
    hourly_final["MissingHoursBetween"] > 0
)

# Rename the gap column for clarity
hourly_final = hourly_final.rename(
    columns={
        "MissingHoursBetween": "MissingHoursBefore"
    }
)

# Extract the date and hour for future analysis
hourly_final["ActivityDate"] = (
    hourly_final["ActivityHour"].dt.normalize()
)

hourly_final["HourOfDay"] = (
    hourly_final["ActivityHour"].dt.hour
)

# Display quality flag summary
print("Hourly Steps Quality Flag Summary:")

flag_columns = [
    "FlagZeroSteps",
    "FlagHighHourlySteps",
    "FlagAfterGap"
]

display(
    hourly_final[flag_columns]
    .sum()
    .to_frame(name="Flagged Records")
)

# Display missing hourly slots
print("\nMissing hourly slots:",
      hourly_final["MissingHoursBefore"].sum())

# Display final dimensions
print("\nFinal dataset shape:", hourly_final.shape)

Hourly Steps Quality Flag Summary:

                     Flagged Records
FlagZeroSteps                  20478
FlagHighHourlySteps              134
FlagAfterGap                      11

Missing hourly slots: 586

Final dataset shape: (46008, 10)

In [40]:
# Step 3G: Final validation of hourly steps data

# 1. Verify record counts
print("Total records:", len(hourly_final))
print("Total columns:", hourly_final.shape[1])

# 2. Check for duplicate participant-hour records
duplicates = hourly_final.duplicated(
    subset=["Id", "ActivityHour"]
).sum()

print("\nRemaining participant-hour duplicates:",
      duplicates)

# 3. Check missing values in essential columns
essential_columns = [
    "Id",
    "ActivityHour",
    "StepTotal"
]

missing_values = (
    hourly_final[essential_columns].isna().sum()
)

print("\nMissing Values:")
print(missing_values)

# 4. Verify datetime format
print("\nActivityHour data type:",
      hourly_final["ActivityHour"].dtype)

# 5. Verify negative step counts
negative_steps = (
    hourly_final["StepTotal"] < 0
).sum()

print("\nNegative step records:", negative_steps)

# 6. Validate quality flag counts
print("\nQuality Flag Totals:")

print("Zero-step records:",
      hourly_final["FlagZeroSteps"].sum())

print("High hourly-step records:",
      hourly_final["FlagHighHourlySteps"].sum())

print("Records following gaps:",
      hourly_final["FlagAfterGap"].sum())

print("Missing hourly slots:",
      hourly_final["MissingHoursBefore"].sum())

# 7. Summarize quality flags by period
print("\nQuality Flags by Source Period:")

display(
    hourly_final.groupby("SourcePeriod").agg(
        TotalRecords=("Id", "size"),
        ZeroSteps=("FlagZeroSteps", "sum"),
        HighHourlySteps=("FlagHighHourlySteps", "sum"),
        AfterGap=("FlagAfterGap", "sum")
    )
)

# 8. Validate final dataset
assert len(hourly_final) == 46008
assert hourly_final.shape[1] == 10
assert duplicates == 0
assert missing_values.sum() == 0
assert pd.api.types.is_datetime64_any_dtype(
    hourly_final["ActivityHour"]
)
assert negative_steps == 0

# Verify quality flag counts
assert hourly_final["FlagZeroSteps"].sum() == 20478
assert hourly_final["FlagHighHourlySteps"].sum() == 134
assert hourly_final["FlagAfterGap"].sum() == 11
assert hourly_final["MissingHoursBefore"].sum() == 586

# Verify that flags match their conditions
assert (
    hourly_final["FlagZeroSteps"] ==
    (hourly_final["StepTotal"] == 0)
).all()

assert (
    hourly_final["FlagHighHourlySteps"] ==
    (hourly_final["StepTotal"] > 5000)
).all()

assert (
    hourly_final["FlagAfterGap"] ==
    (hourly_final["MissingHoursBefore"] > 0)
).all()

# Verify derived date and hour columns
assert (
    hourly_final["ActivityDate"] ==
    hourly_final["ActivityHour"].dt.normalize()
).all()

assert (
    hourly_final["HourOfDay"] ==
    hourly_final["ActivityHour"].dt.hour
).all()

print("\nAll hourly steps validation checks passed!")

Total records: 46008
Total columns: 10

Remaining participant-hour duplicates: 0

Missing Values:
Id              0
ActivityHour    0
StepTotal       0
dtype: int64

ActivityHour data type: datetime64[ns]

Negative step records: 0

Quality Flag Totals:
Zero-step records: 20478
High hourly-step records: 134
Records following gaps: 11
Missing hourly slots: 586

Quality Flags by Source Period:

              TotalRecords  ZeroSteps  HighHourlySteps  AfterGap
SourcePeriod
Period 1             23909      11181               67         0
Period 2             22099       9297               67        11

All hourly steps validation checks passed!

In [41]:
# Step 3H.1: Export cleaned hourly steps dataset

# Create a copy for exporting
hourly_export = hourly_final.copy()

# Sort observations by participant and timestamp
hourly_export = hourly_export.sort_values(
    ["Id", "ActivityHour"]
).reset_index(drop=True)

# Define the output file path
hourly_output = cleaned_path / "hourlySteps_clean.csv"

# Export the dataset as a CSV file
hourly_export.to_csv(
    hourly_output,
    index=False
)

# Confirm the export
print("Hourly Steps Dataset Exported Successfully!")

print("\nFile Location:")
print(hourly_output)

print("\nExported Dataset Dimensions:")
print("Rows:", len(hourly_export))
print("Columns:", hourly_export.shape[1])

Hourly Steps Dataset Exported Successfully!

File Location:
/Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/hourlySteps_clean.csv

Exported Dataset Dimensions:
Rows: 46008
Columns: 10

In [42]:
# Step 3H.2: Verify exported hourly steps dataset

# Reload the exported CSV
verify_hourly = pd.read_csv(
    hourly_output,
    parse_dates=["ActivityHour", "ActivityDate"]
)

# Verify record and column counts
assert verify_hourly.shape == (46008, 10)

# Verify participant-hour uniqueness
assert not verify_hourly.duplicated(
    subset=["Id", "ActivityHour"]
).any()

# Verify essential columns have no missing values
assert verify_hourly[
    ["Id", "ActivityHour", "StepTotal"]
].notna().all().all()

# Verify no negative step counts
assert (verify_hourly["StepTotal"] >= 0).all()

# Verify quality flag counts
assert verify_hourly["FlagZeroSteps"].sum() == 20478
assert verify_hourly["FlagHighHourlySteps"].sum() == 134
assert verify_hourly["FlagAfterGap"].sum() == 11

# Verify missing hourly slots
assert verify_hourly["MissingHoursBefore"].sum() == 586

# Verify derived hour values
assert (
    verify_hourly["HourOfDay"] ==
    verify_hourly["ActivityHour"].dt.hour
).all()

# Confirm successful verification
print("Export Verification Successful!")

print("\nDataset Shape:", verify_hourly.shape)

print("\nQuality Flag Summary:")
print(
    verify_hourly[
        [
            "FlagZeroSteps",
            "FlagHighHourlySteps",
            "FlagAfterGap"
        ]
    ].sum()
)

Export Verification Successful!

Dataset Shape: (46008, 10)

Quality Flag Summary:
FlagZeroSteps          20478
FlagHighHourlySteps      134
FlagAfterGap              11
dtype: int64

**Data Cleaning and Validation — Hourly Steps**

The two hourly steps datasets initially contained 46,183 observations across both collection periods. Data-quality checks identified 175 overlapping participant-hour records on April 12, 2016, all of which contained identical step counts. Duplicate observations were resolved by prioritizing Period 2, resulting in 46,008 unique participant-hour records.

Further inspection identified 20,478 observations with zero steps and 134 observations exceeding 5,000 steps per hour. These observations were retained and flagged rather than automatically removed.

An examination of hourly continuity identified 11 gaps affecting 11 participants, representing 586 missing hourly slots. All detected gaps ended on April 12, 2016. Missing observations were documented but not imputed with zero values.

The processed dataset was validated for duplicate records, missing essential values, invalid timestamps, negative step counts, and quality-flag consistency before being exported for further analysis.

## Step 4: Hourly Intensities Data Processing

In [43]:
# Step 4A: Import hourly intensities datasets

# Identify the two hourlyIntensities CSV files
intensity_files = [
    file for file in selected_files
    if file.stem == "hourlyIntensities_merged"
]

# Identify each collection period
intensity_period1_path = next(
    file for file in intensity_files
    if file.parent.name == "Fitabase Data 3.12.16-4.11.16"
)

intensity_period2_path = next(
    file for file in intensity_files
    if file.parent.name == "Fitabase Data 4.12.16-5.12.16"
)

# Import both CSV files into pandas
intensity_1 = pd.read_csv(intensity_period1_path)
intensity_2 = pd.read_csv(intensity_period2_path)

# Display dataset dimensions
print("Period 1 Shape:", intensity_1.shape)
print("Period 2 Shape:", intensity_2.shape)

# Preview the first five observations
print("\nPeriod 1 Preview:")
display(intensity_1.head())

print("\nPeriod 2 Preview:")
display(intensity_2.head())

# Check whether column names match
print("\nColumn names match:",
      intensity_1.columns.equals(intensity_2.columns))

# Display column names
print("\nDataset Columns:")
print(intensity_1.columns.tolist())

Period 1 Shape: (24084, 4)
Period 2 Shape: (22099, 4)

Period 1 Preview:

           Id           ActivityHour  TotalIntensity  AverageIntensity
0  1503960366  3/12/2016 12:00:00 AM               0               0.0
1  1503960366   3/12/2016 1:00:00 AM               0               0.0
2  1503960366   3/12/2016 2:00:00 AM               0               0.0
3  1503960366   3/12/2016 3:00:00 AM               0               0.0
4  1503960366   3/12/2016 4:00:00 AM               0               0.0

Period 2 Preview:

           Id           ActivityHour  TotalIntensity  AverageIntensity
0  1503960366  4/12/2016 12:00:00 AM              20          0.333333
1  1503960366   4/12/2016 1:00:00 AM               8          0.133333
2  1503960366   4/12/2016 2:00:00 AM               7          0.116667
3  1503960366   4/12/2016 3:00:00 AM               0          0.000000
4  1503960366   4/12/2016 4:00:00 AM               0          0.000000

Column names match: True

Dataset Columns:
['Id', 'ActivityHour', 'TotalIntensity', 'AverageIntensity']

In [44]:
# Step 4B: Inspect data types and missing values

# Display information about Period 1
print("Period 1 Information:")
intensity_1.info()

# Display information about Period 2
print("\nPeriod 2 Information:")
intensity_2.info()

# Calculate missing values for each period
missing_intensity_1 = intensity_1.isna().sum()
missing_intensity_2 = intensity_2.isna().sum()

# Calculate missing percentages
missing_intensity_pct_1 = (
    missing_intensity_1 / len(intensity_1)
) * 100

missing_intensity_pct_2 = (
    missing_intensity_2 / len(intensity_2)
) * 100

# Create a comparison table
intensity_missing_summary = pd.DataFrame({
    "Period 1 Missing": missing_intensity_1,
    "Period 1 Missing (%)": missing_intensity_pct_1,
    "Period 2 Missing": missing_intensity_2,
    "Period 2 Missing (%)": missing_intensity_pct_2
})

# Display missing value summary
print("\nMissing Value Summary:")
display(intensity_missing_summary.round(2))

# Display total missing values
print("\nTotal Missing Values:")
print("Period 1:", missing_intensity_1.sum())
print("Period 2:", missing_intensity_2.sum())

Period 1 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24084 entries, 0 to 24083
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                24084 non-null  int64
 1   ActivityHour      24084 non-null  object
 2   TotalIntensity    24084 non-null  int64
 3   AverageIntensity  24084 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 752.8+ KB

Period 2 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                22099 non-null  int64
 1   ActivityHour      22099 non-null  object
 2   TotalIntensity    22099 non-null  int64
 3   AverageIntensity  22099 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 690.7+ KB

Missing Value Summary:

,Period 1 Missing,Period 1 Missing (%),Period 2 Missing,Period 2 Missing (%)
Id,0,0.0,0,0.0
ActivityHour,0,0.0,0,0.0
TotalIntensity,0,0.0,0,0.0
AverageIntensity,0,0.0,0,0.0

Total Missing Values:
Period 1: 0
Period 2: 0

In [45]:
# Step 4C: Identify duplicate hourly intensity records

# Create copies to preserve the original datasets
intensity_check_1 = intensity_1.copy()
intensity_check_2 = intensity_2.copy()

# Convert ActivityHour to datetime
for df in [intensity_check_1, intensity_check_2]:
    df["ActivityHour"] = pd.to_datetime(
        df["ActivityHour"],
        format="%m/%d/%Y %I:%M:%S %p",
        errors="coerce"
    )

# Check for invalid or missing timestamps
print("Invalid or Missing Timestamps:")
print("Period 1:",
      intensity_check_1["ActivityHour"].isna().sum())
print("Period 2:",
      intensity_check_2["ActivityHour"].isna().sum())

# Verify successful timestamp conversion
assert intensity_check_1["ActivityHour"].notna().all()
assert intensity_check_2["ActivityHour"].notna().all()

# Define participant-hour identifier
intensity_keys = ["Id", "ActivityHour"]

# Check for exact duplicate rows
print("\nExact Duplicate Records:")
print("Period 1:",
      intensity_check_1.duplicated().sum())
print("Period 2:",
      intensity_check_2.duplicated().sum())

# Check for duplicate participant-hour combinations
print("\nDuplicate Participant-Hour Records:")
print("Period 1:",
      intensity_check_1.duplicated(
          subset=intensity_keys
      ).sum())

print("Period 2:",
      intensity_check_2.duplicated(
          subset=intensity_keys
      ).sum())

# Display duplicate records for closer inspection
for label, df in [
    ("Period 1", intensity_check_1),
    ("Period 2", intensity_check_2)
]:
    print(f"\n{label} Duplicate Details:")

    duplicates = df[
        df.duplicated(
            subset=intensity_keys,
            keep=False
        )
    ].sort_values(intensity_keys)

    display(duplicates.head(20))

Invalid or Missing Timestamps:
Period 1: 0
Period 2: 0

Exact Duplicate Records:
Period 1: 0
Period 2: 0

Duplicate Participant-Hour Records:
Period 1: 0
Period 2: 0

Period 1 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityHour, TotalIntensity, AverageIntensity]
Index: []

Period 2 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityHour, TotalIntensity, AverageIntensity]
Index: []

In [46]:
# Step 4D.1: Inspect hourly intensity date ranges

# Display earliest and latest timestamps
print("Period 1 Date Range:")
print("Earliest:", intensity_check_1["ActivityHour"].min())
print("Latest:", intensity_check_1["ActivityHour"].max())

print("\nPeriod 2 Date Range:")
print("Earliest:", intensity_check_2["ActivityHour"].min())
print("Latest:", intensity_check_2["ActivityHour"].max())

# Count unique participants
print("\nUnique Participants:")
print("Period 1:", intensity_check_1["Id"].nunique())
print("Period 2:", intensity_check_2["Id"].nunique())

# Count unique calendar dates
print("\nUnique Calendar Dates:")
print("Period 1:",
      intensity_check_1["ActivityHour"].dt.date.nunique())

print("Period 2:",
      intensity_check_2["ActivityHour"].dt.date.nunique())

Period 1 Date Range:
Earliest: 2016-03-12 00:00:00
Latest: 2016-04-12 10:00:00

Period 2 Date Range:
Earliest: 2016-04-12 00:00:00
Latest: 2016-05-12 15:00:00

Unique Participants:
Period 1: 34
Period 2: 33

Unique Calendar Dates:
Period 1: 32
Period 2: 31

In [47]:
# Step 4D.2: Identify overlapping hourly intensity records

# Define participant-hour identifier
intensity_keys = ["Id", "ActivityHour"]

# Find participant-hour observations present in both periods
intensity_overlap = intensity_check_1.merge(
    intensity_check_2,
    on=intensity_keys,
    how="inner",
    suffixes=("_p1", "_p2"),
    validate="one_to_one"
)

# Compare the two intensity measurements
total_match = (
    intensity_overlap["TotalIntensity_p1"] ==
    intensity_overlap["TotalIntensity_p2"]
)

average_match = np.isclose(
    intensity_overlap["AverageIntensity_p1"],
    intensity_overlap["AverageIntensity_p2"],
    rtol=1e-7,
    atol=1e-7
)

# Identify records where both measurements match
all_match = total_match & average_match

# Display overlap results
print("Total overlapping participant-hour records:",
      len(intensity_overlap))

print("\nRecords with matching measurements:",
      all_match.sum())

print("Records with different measurements:",
      (~all_match).sum())

# Identify differences in each measurement
print("\nMeasurement Differences:")
print("TotalIntensity differences:", (~total_match).sum())
print("AverageIntensity differences:", (~average_match).sum())

# Preview overlapping observations
print("\nPreview of Overlapping Records:")
display(intensity_overlap.head(15))

# Identify overlapping calendar dates
print("\nOverlapping Calendar Dates:")
print(
    intensity_overlap["ActivityHour"]
    .dt.date
    .value_counts()
    .sort_index()
)

Total overlapping participant-hour records: 175

Records with matching measurements: 175
Records with different measurements: 0

Measurement Differences:
TotalIntensity differences: 0
AverageIntensity differences: 0

Preview of Overlapping Records:

,Id,ActivityHour,TotalIntensity_p1,AverageIntensity_p1,TotalIntensity_p2,AverageIntensity_p2
0,1624580081,2016-04-12 00:00:00,4,0.066667,4,0.066667
1,1624580081,2016-04-12 01:00:00,1,0.016667,1,0.016667
2,1624580081,2016-04-12 02:00:00,0,0.000000,0,0.000000
3,1624580081,2016-04-12 03:00:00,1,0.016667,1,0.016667
4,1624580081,2016-04-12 04:00:00,0,0.000000,0,0.000000
5,1624580081,2016-04-12 05:00:00,0,0.000000,0,0.000000
6,1624580081,2016-04-12 06:00:00,0,0.000000,0,0.000000
7,1624580081,2016-04-12 07:00:00,0,0.000000,0,0.000000
8,1624580081,2016-04-12 08:00:00,1,0.016667,1,0.016667
9,1624580081,2016-04-12 09:00:00,18,0.300000,18,0.300000
10,1624580081,2016-04-12 10:00:00,60,1.000000,60,1.000000
11,1844505072,2016-04-12 00:00:00,0,0.000000,0,0.000000
12,1844505072,2016-04-12 01:00:00,0,0.000000,0,0.000000
13,1844505072,2016-04-12 02:00:00,0,0.000000,0,0.000000
14,1844505072,2016-04-12 03:00:00,0,0.000000,0,0.000000

Overlapping Calendar Dates:
ActivityHour
2016-04-12    175
Name: count, dtype: int64

In [48]:
# Step 4D.3: Combine hourly intensity datasets

# Create copies to preserve original imported datasets
intensity_p1 = intensity_check_1.copy()
intensity_p2 = intensity_check_2.copy()

# Label each dataset by its collection period
intensity_p1["SourcePeriod"] = "Period 1"
intensity_p2["SourcePeriod"] = "Period 2"

# Combine both collection periods
intensity_combined = pd.concat(
    [intensity_p1, intensity_p2],
    ignore_index=True
)

# Count records before removing overlaps
rows_before = len(intensity_combined)

# Remove overlapping participant-hour records
# Keep Period 2 since it was appended last
intensity_combined = intensity_combined.drop_duplicates(
    subset=["Id", "ActivityHour"],
    keep="last"
)

# Sort records by participant and timestamp
intensity_combined = intensity_combined.sort_values(
    ["Id", "ActivityHour"]
).reset_index(drop=True)

# Count records after removing overlaps
rows_after = len(intensity_combined)

# Check for remaining duplicate participant-hour records
remaining_duplicates = intensity_combined.duplicated(
    subset=["Id", "ActivityHour"]
).sum()

# Display cleaning results
print("Records before cleaning:", rows_before)
print("Records after cleaning:", rows_after)
print("Overlapping records resolved:",
      rows_before - rows_after)
print("Remaining participant-hour duplicates:",
      remaining_duplicates)

# Display retained records by collection period
print("\nRecords by Source Period:")
print(intensity_combined["SourcePeriod"].value_counts())

# Verify the source of retained overlapping records
retained_overlap = intensity_combined.merge(
    intensity_overlap[["Id", "ActivityHour"]],
    on=["Id", "ActivityHour"],
    how="inner",
    validate="one_to_one"
)

print("\nSource of Retained Overlapping Records:")
print(retained_overlap["SourcePeriod"].value_counts())

# Validate consolidation
assert rows_after == 46008
assert remaining_duplicates == 0
assert len(retained_overlap) == 175
assert (retained_overlap["SourcePeriod"] == "Period 2").all()

print("\nHourly intensity overlap resolution successful!")

Records before cleaning: 46183
Records after cleaning: 46008
Overlapping records resolved: 175
Remaining participant-hour duplicates: 0

Records by Source Period:
SourcePeriod
Period 1    23909
Period 2    22099
Name: count, dtype: int64

Source of Retained Overlapping Records:
SourcePeriod
Period 2    175
Name: count, dtype: int64

Hourly intensity overlap resolution successful!

**Overlapping Records — Hourly Intensities**

The two hourly intensity datasets initially contained 46,183 observations across both collection periods. Data-quality inspections identified 175 overlapping participant-hour records on April 12, 2016.

All overlapping observations contained matching TotalIntensity and AverageIntensity measurements within the comparison tolerance. To prevent duplicate counting, Period 2 was prioritized when consolidating the datasets.

The resulting dataset contained 46,008 unique participant-hour observations, with all nonoverlapping records preserved. The original CSV files remained unchanged.

In [49]:
# Step 4E.1: Inspect hourly intensity measurements

# Create a copy for data quality inspection
intensity_inspection = intensity_combined.copy()

# Calculate summary statistics
print("Hourly Intensity Summary Statistics:")

display(
    intensity_inspection[
        ["TotalIntensity", "AverageIntensity"]
    ].describe().round(4)
)

# Check for negative measurements
print("\nNegative Intensity Measurements:")

print("Negative TotalIntensity:",
      (intensity_inspection["TotalIntensity"] < 0).sum())

print("Negative AverageIntensity:",
      (intensity_inspection["AverageIntensity"] < 0).sum())

# Check for zero intensity measurements
print("\nZero Intensity Measurements:")

print("Zero TotalIntensity:",
      (intensity_inspection["TotalIntensity"] == 0).sum())

print("Zero AverageIntensity:",
      (intensity_inspection["AverageIntensity"] == 0).sum())

# Calculate percentage of zero-intensity hours
zero_intensity_pct = (
    (intensity_inspection["TotalIntensity"] == 0).mean()
    * 100
)

print("Zero-intensity percentage:",
      round(zero_intensity_pct, 2), "%")

# Display the ten highest intensity observations
print("\nTop 10 Highest Intensity Observations:")

display(
    intensity_inspection[
        [
            "Id",
            "ActivityHour",
            "TotalIntensity",
            "AverageIntensity",
            "SourcePeriod"
        ]
    ]
    .sort_values(
        "TotalIntensity",
        ascending=False
    )
    .head(10)
)

Hourly Intensity Summary Statistics:

       TotalIntensity  AverageIntensity
count      46008.0000        46008.0000
mean          11.4225            0.1904
std           20.7168            0.3453
min            0.0000            0.0000
25%            0.0000            0.0000
50%            2.0000            0.0333
75%           15.0000            0.2500
max          180.0000            3.0000

Negative Intensity Measurements:
Negative TotalIntensity: 0
Negative AverageIntensity: 0

Zero Intensity Measurements:
Zero TotalIntensity: 20027
Zero AverageIntensity: 20027
Zero-intensity percentage: 43.53 %

Top 10 Highest Intensity Observations:

,Id,ActivityHour,TotalIntensity,AverageIntensity,SourcePeriod
44811,8877689391,2016-03-23 18:00:00,180,3.0,Period 1
45719,8877689391,2016-04-30 14:00:00,180,3.0,Period 2
45886,8877689391,2016-05-07 13:00:00,180,3.0,Period 2
28196,5577150313,2016-04-16 14:00:00,180,3.0,Period 2
44667,8877689391,2016-03-17 18:00:00,180,3.0,Period 1
27871,5577150313,2016-04-02 11:00:00,180,3.0,Period 1
37644,8053475328,2016-03-13 20:00:00,180,3.0,Period 1
44904,8877689391,2016-03-27 15:00:00,180,3.0,Period 1
37646,8053475328,2016-03-13 22:00:00,180,3.0,Period 1
38339,8053475328,2016-04-11 19:00:00,180,3.0,Period 1

In [50]:
# Step 4E.2: Validate the relationship between
# TotalIntensity and AverageIntensity

# Calculate expected average intensity
intensity_inspection["ExpectedAverageIntensity"] = (
    intensity_inspection["TotalIntensity"] / 60
)

# Calculate absolute differences
intensity_inspection["IntensityDifference"] = (
    intensity_inspection["AverageIntensity"] -
    intensity_inspection["ExpectedAverageIntensity"]
).abs()

# Compare actual and expected values
# Allow a small tolerance for decimal rounding
intensity_inspection["IntensityMatch"] = np.isclose(
    intensity_inspection["AverageIntensity"],
    intensity_inspection["ExpectedAverageIntensity"],
    rtol=0,
    atol=1e-5
)

# Count matching and inconsistent observations
print("Intensity Consistency Check:")

print("Total observations:",
      len(intensity_inspection))

print("Matching observations:",
      intensity_inspection["IntensityMatch"].sum())

print("Inconsistent observations:",
      (~intensity_inspection["IntensityMatch"]).sum())

# Identify the largest difference
print("\nMaximum absolute difference:",
      intensity_inspection["IntensityDifference"].max())

# Display records with inconsistent measurements
print("\nInconsistent Records:")

display(
    intensity_inspection.loc[
        ~intensity_inspection["IntensityMatch"],
        [
            "Id",
            "ActivityHour",
            "TotalIntensity",
            "AverageIntensity",
            "ExpectedAverageIntensity",
            "IntensityDifference"
        ]
    ].head(20)
)

Intensity Consistency Check:
Total observations: 46008
Matching observations: 46008
Inconsistent observations: 0

Maximum absolute difference: 3.33333333379926e-07

Inconsistent Records:

Empty DataFrame
Columns: [Id, ActivityHour, TotalIntensity, AverageIntensity, ExpectedAverageIntensity, IntensityDifference]
Index: []

In [51]:
# Step 4E.3: Compare hourly intensity and step records

# Define participant-hour identifier
comparison_keys = ["Id", "ActivityHour"]

# Select participant-hour identifiers from intensity data
intensity_records = intensity_combined[
    ["Id", "ActivityHour", "SourcePeriod"]
].rename(
    columns={"SourcePeriod": "IntensitySource"}
)

# Select participant-hour identifiers from steps data
steps_records = hourly_final[
    ["Id", "ActivityHour", "SourcePeriod"]
].rename(
    columns={"SourcePeriod": "StepsSource"}
)

# Compare participant-hour records across datasets
hourly_alignment = intensity_records.merge(
    steps_records,
    on=comparison_keys,
    how="outer",
    indicator=True,
    validate="one_to_one"
)

# Summarize matching and unmatched records
print("Hourly Dataset Alignment:")

print("Intensity records:", len(intensity_records))
print("Steps records:", len(steps_records))

print("\nParticipant-Hour Match Summary:")
print(hourly_alignment["_merge"].value_counts())

# Identify records appearing in only one dataset
unmatched_records = hourly_alignment[
    hourly_alignment["_merge"] != "both"
]

print("\nUnmatched participant-hour records:",
      len(unmatched_records))

# Verify source period consistency for matched records
matched_records = hourly_alignment[
    hourly_alignment["_merge"] == "both"
]

source_mismatches = (
    matched_records["IntensitySource"] !=
    matched_records["StepsSource"]
).sum()

print("Source period mismatches:", source_mismatches)

# Display unmatched records, if any
print("\nPreview of Unmatched Records:")
display(unmatched_records.head(10))

Hourly Dataset Alignment:
Intensity records: 46008
Steps records: 46008

Participant-Hour Match Summary:
_merge
both          46008
left_only         0
right_only        0
Name: count, dtype: int64

Unmatched participant-hour records: 0
Source period mismatches: 0

Preview of Unmatched Records:

Empty DataFrame
Columns: [Id, ActivityHour, IntensitySource, StepsSource, _merge]
Index: []

In [52]:
# Step 4F.1: Create hourly intensity quality flags

# Preserve the consolidated hourly intensity dataset
intensity_final = intensity_combined.copy()

# Flag observations with zero total intensity
intensity_final["FlagZeroIntensity"] = (
    intensity_final["TotalIntensity"] == 0
)

# Select existing gap information from hourly steps
gap_reference = hourly_final[
    [
        "Id",
        "ActivityHour",
        "MissingHoursBefore",
        "FlagAfterGap"
    ]
].copy()

# Transfer gap information using participant-hour identifiers
intensity_final = intensity_final.merge(
    gap_reference,
    on=["Id", "ActivityHour"],
    how="left",
    validate="one_to_one",
    indicator=True
)

# Verify every intensity record matched an hourly steps record
assert (intensity_final["_merge"] == "both").all()

# Remove the temporary merge indicator
intensity_final = intensity_final.drop(columns=["_merge"])

# Extract calendar date
intensity_final["ActivityDate"] = (
    intensity_final["ActivityHour"].dt.normalize()
)

# Extract hour of day (0-23)
intensity_final["HourOfDay"] = (
    intensity_final["ActivityHour"].dt.hour
)

# Display quality flag summary
print("Hourly Intensity Quality Flag Summary:")

flag_columns = [
    "FlagZeroIntensity",
    "FlagAfterGap"
]

display(
    intensity_final[flag_columns]
    .sum()
    .to_frame(name="Flagged Records")
)

# Display missing hourly slots
print("\nMissing hourly slots:",
      intensity_final["MissingHoursBefore"].sum())

# Display dataset dimensions
print("\nFinal dataset shape:", intensity_final.shape)

# Verify expected results
assert len(intensity_final) == 46008
assert intensity_final["FlagZeroIntensity"].sum() == 20027
assert intensity_final["FlagAfterGap"].sum() == 11
assert intensity_final["MissingHoursBefore"].sum() == 586

print("\nQuality flags created successfully!")

Hourly Intensity Quality Flag Summary:

                   Flagged Records
FlagZeroIntensity            20027
FlagAfterGap                    11

Missing hourly slots: 586

Final dataset shape: (46008, 10)

Quality flags created successfully!

In [53]:
# Step 4G: Final validation of hourly intensity data

# 1. Verify dataset dimensions
print("Total records:", len(intensity_final))
print("Total columns:", intensity_final.shape[1])

# 2. Check for duplicate participant-hour records
duplicates = intensity_final.duplicated(
    subset=["Id", "ActivityHour"]
).sum()

print("\nRemaining participant-hour duplicates:",
      duplicates)

# 3. Check missing values in essential columns
essential_columns = [
    "Id",
    "ActivityHour",
    "TotalIntensity",
    "AverageIntensity"
]

missing_values = (
    intensity_final[essential_columns].isna().sum()
)

print("\nMissing Values:")
print(missing_values)

# 4. Verify datetime format
print("\nActivityHour data type:",
      intensity_final["ActivityHour"].dtype)

# 5. Check negative intensity measurements
negative_total = (
    intensity_final["TotalIntensity"] < 0
).sum()

negative_average = (
    intensity_final["AverageIntensity"] < 0
).sum()

print("\nNegative Intensity Measurements:")
print("TotalIntensity:", negative_total)
print("AverageIntensity:", negative_average)

# 6. Verify mathematical consistency
intensity_matches = np.isclose(
    intensity_final["AverageIntensity"],
    intensity_final["TotalIntensity"] / 60,
    rtol=0,
    atol=1e-5
)

print("\nIntensity Calculation Validation:")
print("Matching records:", intensity_matches.sum())
print("Inconsistent records:", (~intensity_matches).sum())

# 7. Verify quality flags
print("\nQuality Flag Totals:")

print("Zero-intensity records:",
      intensity_final["FlagZeroIntensity"].sum())

print("Records following gaps:",
      intensity_final["FlagAfterGap"].sum())

print("Missing hourly slots:",
      intensity_final["MissingHoursBefore"].sum())

# 8. Summarize quality flags by source period
print("\nQuality Flags by Source Period:")

display(
    intensity_final.groupby("SourcePeriod").agg(
        TotalRecords=("Id", "size"),
        ZeroIntensity=("FlagZeroIntensity", "sum"),
        AfterGap=("FlagAfterGap", "sum")
    )
)

# 9. Validate dataset structure
assert intensity_final.shape == (46008, 10)
assert duplicates == 0
assert missing_values.sum() == 0
assert pd.api.types.is_datetime64_any_dtype(
    intensity_final["ActivityHour"]
)
assert negative_total == 0
assert negative_average == 0

# 10. Validate intensity calculations
assert intensity_matches.all()

# 11. Validate quality flag counts
assert intensity_final["FlagZeroIntensity"].sum() == 20027
assert intensity_final["FlagAfterGap"].sum() == 11
assert intensity_final["MissingHoursBefore"].sum() == 586

# 12. Verify individual flag assignments
assert (
    intensity_final["FlagZeroIntensity"] ==
    (intensity_final["TotalIntensity"] == 0)
).all()

assert (
    intensity_final["FlagAfterGap"] ==
    (intensity_final["MissingHoursBefore"] > 0)
).all()

# 13. Verify derived date and hour columns
assert (
    intensity_final["ActivityDate"] ==
    intensity_final["ActivityHour"].dt.normalize()
).all()

assert (
    intensity_final["HourOfDay"] ==
    intensity_final["ActivityHour"].dt.hour
).all()

print("\nAll hourly intensity validation checks passed!")

Total records: 46008
Total columns: 10

Remaining participant-hour duplicates: 0

Missing Values:
Id                  0
ActivityHour        0
TotalIntensity      0
AverageIntensity    0
dtype: int64

ActivityHour data type: datetime64[ns]

Negative Intensity Measurements:
TotalIntensity: 0
AverageIntensity: 0

Intensity Calculation Validation:
Matching records: 46008
Inconsistent records: 0

Quality Flag Totals:
Zero-intensity records: 20027
Records following gaps: 11
Missing hourly slots: 586

Quality Flags by Source Period:

              TotalRecords  ZeroIntensity  AfterGap
SourcePeriod
Period 1             23909          10930         0
Period 2             22099           9097        11

All hourly intensity validation checks passed!

In [54]:
# Step 4H.1: Export cleaned hourly intensities dataset

# Create a copy for exporting
intensity_export = intensity_final.copy()

# Sort observations by participant and timestamp
intensity_export = intensity_export.sort_values(
    ["Id", "ActivityHour"]
).reset_index(drop=True)

# Define the output file path
intensity_output = (
    cleaned_path / "hourlyIntensities_clean.csv"
)

# Export the dataset as a CSV file
intensity_export.to_csv(
    intensity_output,
    index=False
)

# Confirm successful export
print("Hourly Intensities Dataset Exported Successfully!")

print("\nFile Location:")
print(intensity_output)

print("\nExported Dataset Dimensions:")
print("Rows:", len(intensity_export))
print("Columns:", intensity_export.shape[1])

Hourly Intensities Dataset Exported Successfully!

File Location:
/Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/hourlyIntensities_clean.csv

Exported Dataset Dimensions:
Rows: 46008
Columns: 10

In [55]:
# Step 4H.2: Verify exported hourly intensities dataset

# Reload the exported CSV file
verify_intensity = pd.read_csv(
    intensity_output,
    parse_dates=["ActivityHour", "ActivityDate"]
)

# Verify dataset dimensions
assert verify_intensity.shape == (46008, 10)

# Check participant-hour uniqueness
assert not verify_intensity.duplicated(
    subset=["Id", "ActivityHour"]
).any()

# Verify essential columns contain no missing values
essential_columns = [
    "Id",
    "ActivityHour",
    "TotalIntensity",
    "AverageIntensity"
]

assert verify_intensity[essential_columns].notna().all().all()

# Verify nonnegative intensity measurements
assert (verify_intensity["TotalIntensity"] >= 0).all()
assert (verify_intensity["AverageIntensity"] >= 0).all()

# Verify mathematical consistency
assert np.isclose(
    verify_intensity["AverageIntensity"],
    verify_intensity["TotalIntensity"] / 60,
    rtol=0,
    atol=1e-5
).all()

# Verify quality flags
assert verify_intensity["FlagZeroIntensity"].sum() == 20027
assert verify_intensity["FlagAfterGap"].sum() == 11

# Verify missing hourly slots
assert verify_intensity["MissingHoursBefore"].sum() == 586

# Verify derived hour of day
assert (
    verify_intensity["HourOfDay"] ==
    verify_intensity["ActivityHour"].dt.hour
).all()

# Confirm successful verification
print("Export Verification Successful!")

print("\nDataset Shape:", verify_intensity.shape)

print("\nQuality Flag Summary:")
print(
    verify_intensity[
        ["FlagZeroIntensity", "FlagAfterGap"]
    ].sum()
)

print("\nMissing Hourly Slots:",
      verify_intensity["MissingHoursBefore"].sum())

Export Verification Successful!

Dataset Shape: (46008, 10)

Quality Flag Summary:
FlagZeroIntensity    20027
FlagAfterGap            11
dtype: int64

Missing Hourly Slots: 586

**Data Cleaning and Validation — Hourly Intensities**

The two hourly intensity datasets initially contained 46,183 observations across both collection periods. Data-quality checks identified 175 overlapping participant-hour records on April 12, 2016. All overlapping observations contained matching intensity measurements, so Period 2 was prioritized when removing duplicate participant-hour records. The consolidated dataset contained 46,008 observations.

Further inspection identified 20,027 observations with zero recorded intensity and no negative measurements. All 46,008 observations satisfied the expected relationship between TotalIntensity and AverageIntensity within a small numerical tolerance.

A comparison with the cleaned hourly steps dataset confirmed that all participant-hour observations aligned exactly. Therefore, the previously identified 11 recording gaps, representing 586 missing hourly slots, were documented in the hourly intensity dataset.

Quality flags were created to identify zero-intensity observations and recording gaps without removing potentially valid measurements. The processed dataset was validated before export.

## Step 5: Hourly Calories Data Processing

In [56]:
# Step 5A: Import hourly calories datasets

# Identify the two hourlyCalories CSV files
calorie_files = [
    file for file in selected_files
    if file.stem == "hourlyCalories_merged"
]

# Identify each collection period
calorie_period1_path = next(
    file for file in calorie_files
    if file.parent.name == "Fitabase Data 3.12.16-4.11.16"
)

calorie_period2_path = next(
    file for file in calorie_files
    if file.parent.name == "Fitabase Data 4.12.16-5.12.16"
)

# Import both CSV files
calorie_1 = pd.read_csv(calorie_period1_path)
calorie_2 = pd.read_csv(calorie_period2_path)

# Display dataset dimensions
print("Period 1 Shape:", calorie_1.shape)
print("Period 2 Shape:", calorie_2.shape)

# Preview the first five observations
print("\nPeriod 1 Preview:")
display(calorie_1.head())

print("\nPeriod 2 Preview:")
display(calorie_2.head())

# Check whether column names match
print("\nColumn names match:",
      calorie_1.columns.equals(calorie_2.columns))

# Display column names
print("\nDataset Columns:")
print(calorie_1.columns.tolist())

Period 1 Shape: (24084, 3)
Period 2 Shape: (22099, 3)

Period 1 Preview:

           Id           ActivityHour  Calories
0  1503960366  3/12/2016 12:00:00 AM        48
1  1503960366   3/12/2016 1:00:00 AM        48
2  1503960366   3/12/2016 2:00:00 AM        48
3  1503960366   3/12/2016 3:00:00 AM        48
4  1503960366   3/12/2016 4:00:00 AM        48

Period 2 Preview:

           Id           ActivityHour  Calories
0  1503960366  4/12/2016 12:00:00 AM        81
1  1503960366   4/12/2016 1:00:00 AM        61
2  1503960366   4/12/2016 2:00:00 AM        59
3  1503960366   4/12/2016 3:00:00 AM        47
4  1503960366   4/12/2016 4:00:00 AM        48

Column names match: True

Dataset Columns:
['Id', 'ActivityHour', 'Calories']

In [57]:
# Step 5B: Inspect data types and missing values

# Display information about Period 1
print("Period 1 Information:")
calorie_1.info()

# Display information about Period 2
print("\nPeriod 2 Information:")
calorie_2.info()

# Calculate missing values for each period
missing_calorie_1 = calorie_1.isna().sum()
missing_calorie_2 = calorie_2.isna().sum()

# Calculate missing percentages
missing_calorie_pct_1 = (
    missing_calorie_1 / len(calorie_1)
) * 100

missing_calorie_pct_2 = (
    missing_calorie_2 / len(calorie_2)
) * 100

# Create a missing-value comparison table
calorie_missing_summary = pd.DataFrame({
    "Period 1 Missing": missing_calorie_1,
    "Period 1 Missing (%)": missing_calorie_pct_1,
    "Period 2 Missing": missing_calorie_2,
    "Period 2 Missing (%)": missing_calorie_pct_2
})

# Display results
print("\nMissing Value Summary:")
display(calorie_missing_summary.round(2))

# Display total missing values
print("\nTotal Missing Values:")
print("Period 1:", missing_calorie_1.sum())
print("Period 2:", missing_calorie_2.sum())

Period 1 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24084 entries, 0 to 24083
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            24084 non-null  int64
 1   ActivityHour  24084 non-null  object
 2   Calories      24084 non-null  int64
dtypes: int64(2), object(1)
memory usage: 564.6+ KB

Period 2 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22099 entries, 0 to 22098
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            22099 non-null  int64
 1   ActivityHour  22099 non-null  object
 2   Calories      22099 non-null  int64
dtypes: int64(2), object(1)
memory usage: 518.1+ KB

Missing Value Summary:

,Period 1 Missing,Period 1 Missing (%),Period 2 Missing,Period 2 Missing (%)
Id,0,0.0,0,0.0
ActivityHour,0,0.0,0,0.0
Calories,0,0.0,0,0.0

Total Missing Values:
Period 1: 0
Period 2: 0

In [58]:
# Step 5C: Identify duplicate hourly calorie records

# Create copies to preserve the original datasets
calorie_check_1 = calorie_1.copy()
calorie_check_2 = calorie_2.copy()

# Convert ActivityHour from text to datetime
for df in [calorie_check_1, calorie_check_2]:
    df["ActivityHour"] = pd.to_datetime(
        df["ActivityHour"],
        format="%m/%d/%Y %I:%M:%S %p",
        errors="coerce"
    )

# Check for invalid or missing timestamps
print("Invalid or Missing Timestamps:")
print("Period 1:",
      calorie_check_1["ActivityHour"].isna().sum())
print("Period 2:",
      calorie_check_2["ActivityHour"].isna().sum())

# Verify successful timestamp conversion
assert calorie_check_1["ActivityHour"].notna().all()
assert calorie_check_2["ActivityHour"].notna().all()

# Define participant-hour identifier
calorie_keys = ["Id", "ActivityHour"]

# Check for exact duplicate rows
print("\nExact Duplicate Records:")
print("Period 1:",
      calorie_check_1.duplicated().sum())
print("Period 2:",
      calorie_check_2.duplicated().sum())

# Check duplicate participant-hour combinations
print("\nDuplicate Participant-Hour Records:")
print("Period 1:",
      calorie_check_1.duplicated(
          subset=calorie_keys
      ).sum())

print("Period 2:",
      calorie_check_2.duplicated(
          subset=calorie_keys
      ).sum())

# Display duplicate records for closer inspection
for label, df in [
    ("Period 1", calorie_check_1),
    ("Period 2", calorie_check_2)
]:
    print(f"\n{label} Duplicate Details:")

    duplicates = df[
        df.duplicated(
            subset=calorie_keys,
            keep=False
        )
    ].sort_values(calorie_keys)

    display(duplicates.head(20))

Invalid or Missing Timestamps:
Period 1: 0
Period 2: 0

Exact Duplicate Records:
Period 1: 0
Period 2: 0

Duplicate Participant-Hour Records:
Period 1: 0
Period 2: 0

Period 1 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityHour, Calories]
Index: []

Period 2 Duplicate Details:

Empty DataFrame
Columns: [Id, ActivityHour, Calories]
Index: []

In [59]:
# Step 5D.1: Inspect hourly calorie date ranges

# Display earliest and latest timestamps
print("Period 1 Date Range:")
print("Earliest:", calorie_check_1["ActivityHour"].min())
print("Latest:", calorie_check_1["ActivityHour"].max())

print("\nPeriod 2 Date Range:")
print("Earliest:", calorie_check_2["ActivityHour"].min())
print("Latest:", calorie_check_2["ActivityHour"].max())

# Count unique participants
print("\nUnique Participants:")
print("Period 1:", calorie_check_1["Id"].nunique())
print("Period 2:", calorie_check_2["Id"].nunique())

# Count unique calendar dates
print("\nUnique Calendar Dates:")
print("Period 1:",
      calorie_check_1["ActivityHour"].dt.date.nunique())

print("Period 2:",
      calorie_check_2["ActivityHour"].dt.date.nunique())

Period 1 Date Range:
Earliest: 2016-03-12 00:00:00
Latest: 2016-04-12 10:00:00

Period 2 Date Range:
Earliest: 2016-04-12 00:00:00
Latest: 2016-05-12 15:00:00

Unique Participants:
Period 1: 34
Period 2: 33

Unique Calendar Dates:
Period 1: 32
Period 2: 31

In [60]:
# Step 5D.2: Identify overlapping hourly calorie records

# Define participant-hour identifier
calorie_keys = ["Id", "ActivityHour"]

# Find records present in both collection periods
calorie_overlap = calorie_check_1.merge(
    calorie_check_2,
    on=calorie_keys,
    how="inner",
    suffixes=("_p1", "_p2"),
    validate="one_to_one"
)

# Compare calorie measurements across both periods
calorie_match = (
    calorie_overlap["Calories_p1"] ==
    calorie_overlap["Calories_p2"]
)

# Display overlap results
print("Total overlapping participant-hour records:",
      len(calorie_overlap))

print("\nRecords with matching calories:",
      calorie_match.sum())

print("Records with different calories:",
      (~calorie_match).sum())

# Compare which period has higher calorie measurements
print("\nCalorie Measurement Comparison:")

print("Period 2 Higher:",
      (
          calorie_overlap["Calories_p2"] >
          calorie_overlap["Calories_p1"]
      ).sum())

print("Period 1 Higher:",
      (
          calorie_overlap["Calories_p1"] >
          calorie_overlap["Calories_p2"]
      ).sum())

print("Equal Values:", calorie_match.sum())

# Display overlapping observations
print("\nPreview of Overlapping Records:")
display(calorie_overlap.head(15))

# Identify overlapping calendar dates
print("\nOverlapping Calendar Dates:")

print(
    calorie_overlap["ActivityHour"]
    .dt.date
    .value_counts()
    .sort_index()
)

Total overlapping participant-hour records: 175

Records with matching calories: 175
Records with different calories: 0

Calorie Measurement Comparison:
Period 2 Higher: 0
Period 1 Higher: 0
Equal Values: 175

Preview of Overlapping Records:

            Id        ActivityHour  Calories_p1  Calories_p2
0   1624580081 2016-04-12 00:00:00           55           55
1   1624580081 2016-04-12 01:00:00           51           51
2   1624580081 2016-04-12 02:00:00           50           50
3   1624580081 2016-04-12 03:00:00           51           51
4   1624580081 2016-04-12 04:00:00           50           50
5   1624580081 2016-04-12 05:00:00           50           50
6   1624580081 2016-04-12 06:00:00           50           50
7   1624580081 2016-04-12 07:00:00           50           50
8   1624580081 2016-04-12 08:00:00           51           51
9   1624580081 2016-04-12 09:00:00           74           74
10  1624580081 2016-04-12 10:00:00          141          141
11  1844505072 2016-04-12 00:00:00           56           56
12  1844505072 2016-04-12 01:00:00           56           56
13  1844505072 2016-04-12 02:00:00           56           56
14  1844505072 2016-04-12 03:00:00           56           56

Overlapping Calendar Dates:
ActivityHour
2016-04-12    175
Name: count, dtype: int64

In [61]:
# Step 5D.3: Combine hourly calorie datasets

# Create copies to preserve original imported datasets
calorie_p1 = calorie_check_1.copy()
calorie_p2 = calorie_check_2.copy()

# Label each dataset by its collection period
calorie_p1["SourcePeriod"] = "Period 1"
calorie_p2["SourcePeriod"] = "Period 2"

# Combine both collection periods
calorie_combined = pd.concat(
    [calorie_p1, calorie_p2],
    ignore_index=True
)

# Count records before removing overlaps
rows_before = len(calorie_combined)

# Verify overlapping calorie values match
assert (
    calorie_overlap["Calories_p1"] ==
    calorie_overlap["Calories_p2"]
).all()

# Remove overlapping participant-hour records
# Keep Period 2 since it was appended last
calorie_combined = calorie_combined.drop_duplicates(
    subset=["Id", "ActivityHour"],
    keep="last"
)

# Sort records by participant and timestamp
calorie_combined = calorie_combined.sort_values(
    ["Id", "ActivityHour"]
).reset_index(drop=True)

# Count records after removing overlaps
rows_after = len(calorie_combined)

# Check for remaining duplicate participant-hour records
remaining_duplicates = calorie_combined.duplicated(
    subset=["Id", "ActivityHour"]
).sum()

# Display cleaning results
print("Records before cleaning:", rows_before)
print("Records after cleaning:", rows_after)
print("Overlapping records resolved:",
      rows_before - rows_after)
print("Remaining participant-hour duplicates:",
      remaining_duplicates)

# Display retained records by collection period
print("\nRecords by Source Period:")
print(calorie_combined["SourcePeriod"].value_counts())

# Verify the source of retained overlapping records
retained_overlap = calorie_combined.merge(
    calorie_overlap[["Id", "ActivityHour"]],
    on=["Id", "ActivityHour"],
    how="inner",
    validate="one_to_one"
)

print("\nSource of Retained Overlapping Records:")
print(retained_overlap["SourcePeriod"].value_counts())

# Validate consolidation
assert rows_before == 46183
assert rows_after == 46008
assert remaining_duplicates == 0
assert len(retained_overlap) == 175
assert (retained_overlap["SourcePeriod"] == "Period 2").all()

print("\nHourly calorie overlap resolution successful!")

Records before cleaning: 46183
Records after cleaning: 46008
Overlapping records resolved: 175
Remaining participant-hour duplicates: 0

Records by Source Period:
SourcePeriod
Period 1    23909
Period 2    22099
Name: count, dtype: int64

Source of Retained Overlapping Records:
SourcePeriod
Period 2    175
Name: count, dtype: int64

Hourly calorie overlap resolution successful!

**Overlapping Records — Hourly Calories**

The two hourly calorie datasets initially contained 46,183 observations across both collection periods. Data-quality inspections identified 175 overlapping participant-hour records on April 12, 2016.

All overlapping observations contained identical calorie measurements. To prevent duplicate counting, Period 2 was prioritized when consolidating the datasets.

The resulting dataset contained 46,008 unique participant-hour observations, with all nonoverlapping records preserved. The original CSV files remained unchanged.

In [62]:
# Step 5E.1: Inspect hourly calorie measurements

# Create a copy for data quality inspection
calorie_inspection = calorie_combined.copy()

# Calculate summary statistics
print("Hourly Calorie Summary Statistics:")

display(
    calorie_inspection["Calories"]
    .describe()
    .round(2)
)

# Check for negative calorie measurements
negative_calories = (
    calorie_inspection["Calories"] < 0
).sum()

# Check for zero-calorie observations
zero_calories = (
    calorie_inspection["Calories"] == 0
).sum()

# Calculate percentage of zero-calorie hours
zero_calorie_pct = (
    zero_calories / len(calorie_inspection)
) * 100

# Check unusually low positive calorie estimates
low_calories = (
    (calorie_inspection["Calories"] > 0) &
    (calorie_inspection["Calories"] < 20)
).sum()

# Identify unusually high hourly estimates
# 300 calories is an exploratory threshold,
# not a validity limit
high_calories = (
    calorie_inspection["Calories"] > 300
).sum()

# Display data quality summary
print("\nHourly Calorie Quality Checks:")

print("Negative calorie records:", negative_calories)
print("Zero-calorie records:", zero_calories)

print("Zero-calorie percentage:",
      round(zero_calorie_pct, 2), "%")

print("Positive calorie records below 20:",
      low_calories)

print("Records exceeding 300 calories:",
      high_calories)

# Display the ten highest hourly calorie estimates
print("\nTop 10 Highest Hourly Calorie Records:")

display(
    calorie_inspection[
        [
            "Id",
            "ActivityHour",
            "Calories",
            "SourcePeriod"
        ]
    ]
    .sort_values(
        "Calories",
        ascending=False
    )
    .head(10)
)

Hourly Calorie Summary Statistics:

count    46008.00
mean        95.82
std         60.04
min         42.00
25%         62.00
50%         80.00
75%        106.00
max        948.00
Name: Calories, dtype: float64

Hourly Calorie Quality Checks:
Negative calorie records: 0
Zero-calorie records: 0
Zero-calorie percentage: 0.0 %
Positive calorie records below 20: 0
Records exceeding 300 calories: 752

Top 10 Highest Hourly Calorie Records:

               Id        ActivityHour  Calories SourcePeriod
45719  8877689391 2016-04-30 14:00:00       948     Period 2
45236  8877689391 2016-04-10 11:00:00       933     Period 1
44904  8877689391 2016-03-27 15:00:00       916     Period 1
44905  8877689391 2016-03-27 16:00:00       906     Period 1
45457  8877689391 2016-04-19 16:00:00       886     Period 2
44543  8877689391 2016-03-12 14:00:00       856     Period 1
44811  8877689391 2016-03-23 18:00:00       848     Period 1
45863  8877689391 2016-05-06 14:00:00       843     Period 2
45986  8877689391 2016-05-11 17:00:00       835     Period 2
45483  8877689391 2016-04-20 18:00:00       834     Period 2

In [63]:
# Step 5E.2: Investigate high-calorie observations

# Define participant-hour identifiers
comparison_keys = ["Id", "ActivityHour"]

# Match calorie records with hourly steps
calorie_activity_check = calorie_inspection.merge(
    hourly_final[
        ["Id", "ActivityHour", "StepTotal"]
    ],
    on=comparison_keys,
    how="left",
    validate="one_to_one",
    indicator="StepsMatch"
)

# Match the result with hourly intensities
calorie_activity_check = calorie_activity_check.merge(
    intensity_final[
        ["Id", "ActivityHour", "TotalIntensity"]
    ],
    on=comparison_keys,
    how="left",
    validate="one_to_one",
    indicator="IntensityMatch"
)

# Verify participant-hour alignment
print("Hourly Steps Alignment:")
print(calorie_activity_check["StepsMatch"].value_counts())

print("\nHourly Intensity Alignment:")
print(calorie_activity_check["IntensityMatch"].value_counts())

# Identify observations exceeding 300 calories
high_calorie_records = calorie_activity_check[
    calorie_activity_check["Calories"] > 300
].copy()

# Summarize high-calorie observations
print("\nHigh-Calorie Observation Summary:")

print("Records above 300 calories:",
      len(high_calorie_records))

print("Unique participants:",
      high_calorie_records["Id"].nunique())

# Count high-calorie observations by participant
print("\nTop 10 Participants by High-Calorie Hours:")

display(
    high_calorie_records.groupby("Id")
    .size()
    .sort_values(ascending=False)
    .head(10)
    .to_frame(name="HighCalorieHours")
)

# Examine physical activity during high-calorie hours
print("\nHigh-Calorie Hours with Zero Steps:",
      (high_calorie_records["StepTotal"] == 0).sum())

print("High-Calorie Hours with Zero Intensity:",
      (high_calorie_records["TotalIntensity"] == 0).sum())

# Display the highest calorie observations
print("\nTop 10 Highest Calorie Hours with Activity Data:")

display(
    high_calorie_records.sort_values(
        "Calories",
        ascending=False
    )[
        [
            "Id",
            "ActivityHour",
            "Calories",
            "StepTotal",
            "TotalIntensity",
            "SourcePeriod"
        ]
    ].head(10)
)

Hourly Steps Alignment:
StepsMatch
both          46008
left_only         0
right_only        0
Name: count, dtype: int64

Hourly Intensity Alignment:
IntensityMatch
both          46008
left_only         0
right_only        0
Name: count, dtype: int64

High-Calorie Observation Summary:
Records above 300 calories: 752
Unique participants: 28

Top 10 Participants by High-Calorie Hours:

            HighCalorieHours
Id
8053475328               126
5577150313               124
8877689391               100
8378563200                70
7086361926                49
2022484408                49
7007744171                39
1644430081                29
4388161847                26
6775888955                25

High-Calorie Hours with Zero Steps: 36
High-Calorie Hours with Zero Intensity: 0

Top 10 Highest Calorie Hours with Activity Data:

,Id,ActivityHour,Calories,StepTotal,TotalIntensity,SourcePeriod
45719,8877689391,2016-04-30 14:00:00,948,10554,180,Period 2
45236,8877689391,2016-04-10 11:00:00,933,10565,180,Period 1
44904,8877689391,2016-03-27 15:00:00,916,10141,180,Period 1
44905,8877689391,2016-03-27 16:00:00,906,10018,180,Period 1
45457,8877689391,2016-04-19 16:00:00,886,9392,173,Period 2
44543,8877689391,2016-03-12 14:00:00,856,9149,160,Period 1
44811,8877689391,2016-03-23 18:00:00,848,10076,180,Period 1
45863,8877689391,2016-05-06 14:00:00,843,9769,176,Period 2
45986,8877689391,2016-05-11 17:00:00,835,8357,163,Period 2
45483,8877689391,2016-04-20 18:00:00,834,8361,173,Period 2

In [64]:
# Step 5F.1: Create hourly calorie quality flags

# Preserve the consolidated calorie dataset
calorie_final = calorie_combined.copy()

# Define participant-hour identifiers
calorie_keys = ["Id", "ActivityHour"]

# Select existing steps and gap information
steps_reference = hourly_final[
    [
        "Id",
        "ActivityHour",
        "SourcePeriod",
        "StepTotal",
        "MissingHoursBefore",
        "FlagAfterGap"
    ]
].rename(
    columns={"SourcePeriod": "StepsSource"}
)

# Match calorie observations with hourly steps
calorie_final = calorie_final.merge(
    steps_reference,
    on=calorie_keys,
    how="left",
    validate="one_to_one",
    indicator=True
)

# Verify that all observations matched
assert (calorie_final["_merge"] == "both").all()

# Verify collection periods are consistent
assert (
    calorie_final["SourcePeriod"] ==
    calorie_final["StepsSource"]
).all()

# Flag unusually high calorie estimates
# 300 is an exploratory threshold, not a validity limit
calorie_final["FlagHighCalories"] = (
    calorie_final["Calories"] > 300
)

# Flag high-calorie hours with zero recorded steps
calorie_final["FlagHighCaloriesZeroSteps"] = (
    (calorie_final["Calories"] > 300) &
    (calorie_final["StepTotal"] == 0)
)

# Extract calendar date
calorie_final["ActivityDate"] = (
    calorie_final["ActivityHour"].dt.normalize()
)

# Extract hour of day
calorie_final["HourOfDay"] = (
    calorie_final["ActivityHour"].dt.hour
)

# Remove temporary comparison columns
# StepTotal remains available in hourlySteps_clean
calorie_final = calorie_final.drop(
    columns=[
        "StepsSource",
        "StepTotal",
        "_merge"
    ]
)

# Display quality flag summary
print("Hourly Calorie Quality Flag Summary:")

flag_columns = [
    "FlagHighCalories",
    "FlagHighCaloriesZeroSteps",
    "FlagAfterGap"
]

display(
    calorie_final[flag_columns]
    .sum()
    .to_frame(name="Flagged Records")
)

# Display missing hourly slots
print("\nMissing hourly slots:",
      calorie_final["MissingHoursBefore"].sum())

# Display final dataset dimensions
print("\nFinal dataset shape:", calorie_final.shape)

# Verify expected results
assert len(calorie_final) == 46008
assert calorie_final.shape[1] == 10
assert calorie_final["FlagHighCalories"].sum() == 752
assert calorie_final["FlagHighCaloriesZeroSteps"].sum() == 36
assert calorie_final["FlagAfterGap"].sum() == 11
assert calorie_final["MissingHoursBefore"].sum() == 586

print("\nQuality flags created successfully!")

Hourly Calorie Quality Flag Summary:

                           Flagged Records
FlagHighCalories                       752
FlagHighCaloriesZeroSteps               36
FlagAfterGap                            11

Missing hourly slots: 586

Final dataset shape: (46008, 10)

Quality flags created successfully!

In [65]:
# Step 5G: Final validation of hourly calorie data

# 1. Verify dataset dimensions
print("Total records:", len(calorie_final))
print("Total columns:", calorie_final.shape[1])

# 2. Check duplicate participant-hour records
duplicates = calorie_final.duplicated(
    subset=["Id", "ActivityHour"]
).sum()

print("\nRemaining participant-hour duplicates:",
      duplicates)

# 3. Check missing values in essential columns
essential_columns = [
    "Id",
    "ActivityHour",
    "Calories"
]

missing_values = (
    calorie_final[essential_columns].isna().sum()
)

print("\nMissing Values:")
print(missing_values)

# 4. Verify datetime format
print("\nActivityHour data type:",
      calorie_final["ActivityHour"].dtype)

# 5. Check negative and zero calorie measurements
negative_calories = (
    calorie_final["Calories"] < 0
).sum()

zero_calories = (
    calorie_final["Calories"] == 0
).sum()

print("\nCalorie Measurement Checks:")
print("Negative calories:", negative_calories)
print("Zero calories:", zero_calories)

# 6. Display quality flag totals
print("\nQuality Flag Totals:")

print("High-calorie observations:",
      calorie_final["FlagHighCalories"].sum())

print("High calories with zero steps:",
      calorie_final["FlagHighCaloriesZeroSteps"].sum())

print("Records following gaps:",
      calorie_final["FlagAfterGap"].sum())

print("Missing hourly slots:",
      calorie_final["MissingHoursBefore"].sum())

# 7. Summarize quality flags by collection period
print("\nQuality Flags by Source Period:")

display(
    calorie_final.groupby("SourcePeriod").agg(
        TotalRecords=("Id", "size"),
        HighCalories=("FlagHighCalories", "sum"),
        HighCaloriesZeroSteps=(
            "FlagHighCaloriesZeroSteps", "sum"
        ),
        AfterGap=("FlagAfterGap", "sum")
    )
)

# 8. Verify high-calorie zero-step flags
# Rejoin steps for independent validation
calorie_validation = calorie_final.merge(
    hourly_final[
        ["Id", "ActivityHour", "StepTotal"]
    ],
    on=["Id", "ActivityHour"],
    how="left",
    validate="one_to_one"
)

# 9. Validate dataset structure
assert calorie_final.shape == (46008, 10)
assert duplicates == 0
assert missing_values.sum() == 0

assert pd.api.types.is_datetime64_any_dtype(
    calorie_final["ActivityHour"]
)

assert negative_calories == 0
assert zero_calories == 0
assert calorie_validation["StepTotal"].notna().all()

# 10. Validate quality flag counts
assert calorie_final["FlagHighCalories"].sum() == 752

assert (
    calorie_final["FlagHighCaloriesZeroSteps"].sum()
    == 36
)

assert calorie_final["FlagAfterGap"].sum() == 11
assert calorie_final["MissingHoursBefore"].sum() == 586

# 11. Verify individual flag assignments
assert (
    calorie_final["FlagHighCalories"] ==
    (calorie_final["Calories"] > 300)
).all()

assert (
    calorie_validation["FlagHighCaloriesZeroSteps"] ==
    (
        (calorie_validation["Calories"] > 300) &
        (calorie_validation["StepTotal"] == 0)
    )
).all()

assert (
    calorie_final["FlagAfterGap"] ==
    (calorie_final["MissingHoursBefore"] > 0)
).all()

# 12. Verify derived date and hour columns
assert (
    calorie_final["ActivityDate"] ==
    calorie_final["ActivityHour"].dt.normalize()
).all()

assert (
    calorie_final["HourOfDay"] ==
    calorie_final["ActivityHour"].dt.hour
).all()

print("\nAll hourly calorie validation checks passed!")

Total records: 46008
Total columns: 10

Remaining participant-hour duplicates: 0

Missing Values:
Id              0
ActivityHour    0
Calories        0
dtype: int64

ActivityHour data type: datetime64[ns]

Calorie Measurement Checks:
Negative calories: 0
Zero calories: 0

Quality Flag Totals:
High-calorie observations: 752
High calories with zero steps: 36
Records following gaps: 11
Missing hourly slots: 586

Quality Flags by Source Period:

              TotalRecords  HighCalories  HighCaloriesZeroSteps  AfterGap
SourcePeriod
Period 1             23909           377                     16         0
Period 2             22099           375                     20        11

All hourly calorie validation checks passed!

In [66]:
# Step 5H.1: Export cleaned hourly calorie dataset

# Create a copy for exporting
calorie_export = calorie_final.copy()

# Sort observations by participant and timestamp
calorie_export = calorie_export.sort_values(
    ["Id", "ActivityHour"]
).reset_index(drop=True)

# Define the output file path
calorie_output = (
    cleaned_path / "hourlyCalories_clean.csv"
)

# Export the dataset as a CSV file
calorie_export.to_csv(
    calorie_output,
    index=False
)

# Confirm successful export
print("Hourly Calories Dataset Exported Successfully!")

print("\nFile Location:")
print(calorie_output)

print("\nExported Dataset Dimensions:")
print("Rows:", len(calorie_export))
print("Columns:", calorie_export.shape[1])

Hourly Calories Dataset Exported Successfully!

File Location:
/Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/hourlyCalories_clean.csv

Exported Dataset Dimensions:
Rows: 46008
Columns: 10

In [67]:
# Step 5H.2: Verify exported hourly calorie dataset

# Reload the exported CSV file
verify_calorie = pd.read_csv(
    calorie_output,
    parse_dates=["ActivityHour", "ActivityDate"]
)

# Verify dataset dimensions
assert verify_calorie.shape == (46008, 10)

# Check participant-hour uniqueness
assert not verify_calorie.duplicated(
    subset=["Id", "ActivityHour"]
).any()

# Verify essential columns contain no missing values
essential_columns = [
    "Id",
    "ActivityHour",
    "Calories"
]

assert verify_calorie[
    essential_columns
].notna().all().all()

# Verify all calorie measurements are positive
assert (verify_calorie["Calories"] > 0).all()

# Verify quality flag counts
assert verify_calorie["FlagHighCalories"].sum() == 752

assert (
    verify_calorie["FlagHighCaloriesZeroSteps"].sum()
    == 36
)

assert verify_calorie["FlagAfterGap"].sum() == 11

# Verify missing hourly slots
assert verify_calorie["MissingHoursBefore"].sum() == 586

# Verify high-calorie flag assignments
assert (
    verify_calorie["FlagHighCalories"] ==
    (verify_calorie["Calories"] > 300)
).all()

# Verify recording gap flags
assert (
    verify_calorie["FlagAfterGap"] ==
    (verify_calorie["MissingHoursBefore"] > 0)
).all()

# Verify derived date and hour
assert (
    verify_calorie["ActivityDate"] ==
    verify_calorie["ActivityHour"].dt.normalize()
).all()

assert (
    verify_calorie["HourOfDay"] ==
    verify_calorie["ActivityHour"].dt.hour
).all()

# Confirm successful verification
print("Export Verification Successful!")

print("\nDataset Shape:", verify_calorie.shape)

print("\nQuality Flag Summary:")
print(
    verify_calorie[
        [
            "FlagHighCalories",
            "FlagHighCaloriesZeroSteps",
            "FlagAfterGap"
        ]
    ].sum()
)

print("\nMissing Hourly Slots:",
      verify_calorie["MissingHoursBefore"].sum())

Export Verification Successful!

Dataset Shape: (46008, 10)

Quality Flag Summary:
FlagHighCalories             752
FlagHighCaloriesZeroSteps     36
FlagAfterGap                  11
dtype: int64

Missing Hourly Slots: 586

**Data Cleaning and Validation — Hourly Calories**

The two hourly calorie datasets initially contained 46,183 observations across both collection periods. Data-quality checks identified 175 overlapping participant-hour records on April 12, 2016. All overlapping observations contained identical calorie measurements, so Period 2 was prioritized when consolidating the datasets. The resulting dataset contained 46,008 unique participant-hour observations.

Further inspection identified no negative or zero-calorie measurements. However, 752 observations exceeded 300 estimated calories per hour, including 36 observations with zero recorded steps. These records were retained and flagged for further analysis rather than automatically removed.

A comparison with the cleaned hourly steps and intensity datasets confirmed that all 46,008 participant-hour observations aligned. Therefore, the previously identified 11 recording gaps, representing 586 missing hourly slots, were documented in the hourly calorie dataset.

Quality flags were created to identify high-calorie observations, high-calorie hours with zero steps, and recording gaps. The processed dataset was validated for duplicate records, missing essential values, valid timestamps, positive calorie measurements, and quality-flag consistency before export.

## Step 6: Minute Sleep Data Processing

In [68]:
# Step 6A: Import minute sleep datasets

# Identify the two minuteSleep CSV files
sleep_files = [
    file for file in selected_files
    if file.stem == "minuteSleep_merged"
]

# Identify each collection period
sleep_period1_path = next(
    file for file in sleep_files
    if file.parent.name == "Fitabase Data 3.12.16-4.11.16"
)

sleep_period2_path = next(
    file for file in sleep_files
    if file.parent.name == "Fitabase Data 4.12.16-5.12.16"
)

# Import both CSV files
sleep_1 = pd.read_csv(sleep_period1_path)
sleep_2 = pd.read_csv(sleep_period2_path)

# Display dataset dimensions
print("Period 1 Shape:", sleep_1.shape)
print("Period 2 Shape:", sleep_2.shape)

# Preview the first five observations
print("\nPeriod 1 Preview:")
display(sleep_1.head())

print("\nPeriod 2 Preview:")
display(sleep_2.head())

# Check whether column names match
print("\nColumn names match:",
      sleep_1.columns.equals(sleep_2.columns))

# Display column names
print("\nDataset Columns:")
print(sleep_1.columns.tolist())

Period 1 Shape: (198559, 4)
Period 2 Shape: (188521, 4)

Period 1 Preview:

           Id                  date  value        logId
0  1503960366  3/13/2016 2:39:30 AM      1  11114919637
1  1503960366  3/13/2016 2:40:30 AM      1  11114919637
2  1503960366  3/13/2016 2:41:30 AM      1  11114919637
3  1503960366  3/13/2016 2:42:30 AM      1  11114919637
4  1503960366  3/13/2016 2:43:30 AM      1  11114919637

Period 2 Preview:

           Id                  date  value        logId
0  1503960366  4/12/2016 2:47:30 AM      3  11380564589
1  1503960366  4/12/2016 2:48:30 AM      2  11380564589
2  1503960366  4/12/2016 2:49:30 AM      1  11380564589
3  1503960366  4/12/2016 2:50:30 AM      1  11380564589
4  1503960366  4/12/2016 2:51:30 AM      1  11380564589

Column names match: True

Dataset Columns:
['Id', 'date', 'value', 'logId']

In [69]:
# Step 6B: Inspect minute sleep data types and missing values

# Display information about Period 1
print("Period 1 Information:")
sleep_1.info()

# Display information about Period 2
print("\nPeriod 2 Information:")
sleep_2.info()

# Calculate missing values for each period
missing_sleep_1 = sleep_1.isna().sum()
missing_sleep_2 = sleep_2.isna().sum()

# Calculate missing percentages
missing_sleep_pct_1 = (
    missing_sleep_1 / len(sleep_1)
) * 100

missing_sleep_pct_2 = (
    missing_sleep_2 / len(sleep_2)
) * 100

# Create a comparison table
sleep_missing_summary = pd.DataFrame({
    "Period 1 Missing": missing_sleep_1,
    "Period 1 Missing (%)": missing_sleep_pct_1,
    "Period 2 Missing": missing_sleep_2,
    "Period 2 Missing (%)": missing_sleep_pct_2
})

# Display missing value summary
print("\nMissing Value Summary:")
display(sleep_missing_summary.round(2))

# Display total missing values
print("\nTotal Missing Values:")
print("Period 1:", missing_sleep_1.sum())
print("Period 2:", missing_sleep_2.sum())

Period 1 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198559 entries, 0 to 198558
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Id      198559 non-null  int64
 1   date    198559 non-null  object
 2   value   198559 non-null  int64
 3   logId   198559 non-null  int64
dtypes: int64(3), object(1)
memory usage: 6.1+ MB

Period 2 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188521 entries, 0 to 188520
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Id      188521 non-null  int64
 1   date    188521 non-null  object
 2   value   188521 non-null  int64
 3   logId   188521 non-null  int64
dtypes: int64(3), object(1)
memory usage: 5.8+ MB

Missing Value Summary:

,Period 1 Missing,Period 1 Missing (%),Period 2 Missing,Period 2 Missing (%)
Id,0,0.0,0,0.0
date,0,0.0,0,0.0
value,0,0.0,0,0.0
logId,0,0.0,0,0.0

Total Missing Values:
Period 1: 0
Period 2: 0

In [70]:
# Step 6C.1: Examine sleep-state values and sleep logs

# Create copies to preserve the original datasets
sleep_check_1 = sleep_1.copy()
sleep_check_2 = sleep_2.copy()

# 1. Identify unique sleep-state values
print("Unique Sleep-State Values:")

print("Period 1:",
      sorted(sleep_check_1["value"].unique()))

print("Period 2:",
      sorted(sleep_check_2["value"].unique()))

# 2. Calculate sleep-state frequencies
state_summary = []

for label, df in [
    ("Period 1", sleep_check_1),
    ("Period 2", sleep_check_2)
]:
    counts = df["value"].value_counts().sort_index()

    for state, count in counts.items():
        state_summary.append({
            "SourcePeriod": label,
            "SleepState": state,
            "Records": count,
            "Percentage": (count / len(df)) * 100
        })

# Display sleep-state distribution
print("\nSleep-State Distribution:")

display(
    pd.DataFrame(state_summary)
    .round(2)
)

# 3. Count participants and sleep logs
print("\nParticipants and Sleep Logs:")

for label, df in [
    ("Period 1", sleep_check_1),
    ("Period 2", sleep_check_2)
]:
    print(f"\n{label}:")

    print("Unique participants:",
          df["Id"].nunique())

    print("Unique log IDs:",
          df["logId"].nunique())

    print("Unique participant-log combinations:",
          df[["Id", "logId"]]
          .drop_duplicates()
          .shape[0])

# 4. Examine observations per sleep log
for label, df in [
    ("Period 1", sleep_check_1),
    ("Period 2", sleep_check_2)
]:
    log_counts = (
        df.groupby(["Id", "logId"])
        .size()
    )

    print(f"\n{label} - Observations per Sleep Log:")

    display(log_counts.describe().round(2))

# 5. Display example sleep logs
print("\nSample Sleep Logs from Period 1:")

display(
    sleep_check_1.groupby(["Id", "logId"])
    .size()
    .reset_index(name="RecordedMinutes")
    .head(10)
)

print("\nSample Sleep Logs from Period 2:")

display(
    sleep_check_2.groupby(["Id", "logId"])
    .size()
    .reset_index(name="RecordedMinutes")
    .head(10)
)

Unique Sleep-State Values:
Period 1: [np.int64(1), np.int64(2), np.int64(3)]
Period 2: [np.int64(1), np.int64(2), np.int64(3)]

Sleep-State Distribution:

  SourcePeriod  SleepState  Records  Percentage
0     Period 1           1   183526       92.43
1     Period 1           2    13010        6.55
2     Period 1           3     2023        1.02
3     Period 2           1   172480       91.49
4     Period 2           2    14023        7.44
5     Period 2           3     2018        1.07

Participants and Sleep Logs:

Period 1:
Unique participants: 23
Unique log IDs: 556
Unique participant-log combinations: 556

Period 2:
Unique participants: 24
Unique log IDs: 459
Unique participant-log combinations: 459

Period 1 - Observations per Sleep Log:

count    556.00
mean     357.12
std      175.16
min       60.00
25%      208.50
50%      390.00
75%      487.00
max      961.00
dtype: float64

Period 2 - Observations per Sleep Log:

count     459.00
mean      410.72
std       161.55
min        60.00
25%       346.00
50%       446.00
75%       506.00
max      1086.00
dtype: float64

Sample Sleep Logs from Period 1:

           Id        logId  RecordedMinutes
0  1503960366  11114919637              426
1  1503960366  11126343681              386
2  1503960366  11134971215              335
3  1503960366  11142197163              303
4  1503960366  11142197164               63
5  1503960366  11150938241              437
6  1503960366  11158035737              411
7  1503960366  11162426404              468
8  1503960366  11171977262              476
9  1503960366  11183536407              427

Sample Sleep Logs from Period 2:

           Id        logId  RecordedMinutes
0  1503960366  11380564589              346
1  1503960366  11388770715              313
2  1503960366  11388770716               94
3  1503960366  11402722600              442
4  1503960366  11421831252              289
5  1503960366  11421831253               78
6  1503960366  11421831254              712
7  1503960366  11439580762              320
8  1503960366  11447640793              377
9  1503960366  11455720858              364

In [71]:
# Step 6D.1: Identify duplicate minute sleep records

# Create copies to preserve the original datasets
sleep_duplicate_1 = sleep_check_1.copy()
sleep_duplicate_2 = sleep_check_2.copy()

# Convert date values into datetime format
for df in [sleep_duplicate_1, sleep_duplicate_2]:
    df["date"] = pd.to_datetime(
        df["date"],
        format="%m/%d/%Y %I:%M:%S %p",
        errors="coerce"
    )

# 1. Check invalid or missing timestamps
print("Invalid or Missing Timestamps:")

print("Period 1:",
      sleep_duplicate_1["date"].isna().sum())

print("Period 2:",
      sleep_duplicate_2["date"].isna().sum())

# Verify all timestamps converted successfully
assert sleep_duplicate_1["date"].notna().all()
assert sleep_duplicate_2["date"].notna().all()

# 2. Define identifiers for duplicate detection
log_minute_keys = ["Id", "logId", "date"]
participant_minute_keys = ["Id", "date"]

# 3. Inspect duplicate records in each dataset
for label, df in [
    ("Period 1", sleep_duplicate_1),
    ("Period 2", sleep_duplicate_2)
]:

    print(f"\n{label} Duplicate Summary:")

    # Count exact duplicate rows
    exact_duplicates = df.duplicated().sum()

    # Count repeated timestamps within the same sleep log
    log_minute_duplicates = df.duplicated(
        subset=log_minute_keys
    ).sum()

    # Count repeated participant-minute combinations
    participant_minute_duplicates = df.duplicated(
        subset=participant_minute_keys
    ).sum()

    print("Exact duplicate records:",
          exact_duplicates)

    print("Duplicate participant-log-minute records:",
          log_minute_duplicates)

    print("Duplicate participant-minute records:",
          participant_minute_duplicates)

    # Identify records involved in duplicate groups
    duplicate_details = df[
        df.duplicated(
            subset=participant_minute_keys,
            keep=False
        )
    ].sort_values(
        ["Id", "date", "logId"]
    )

    print("\nPreview of Duplicate Participant-Minute Records:")

    display(duplicate_details.head(20))

Invalid or Missing Timestamps:
Period 1: 0
Period 2: 0

Period 1 Duplicate Summary:
Exact duplicate records: 525
Duplicate participant-log-minute records: 525
Duplicate participant-minute records: 525

Preview of Duplicate Participant-Minute Records:

               Id                date  value        logId
79892  4319703577 2016-04-05 22:50:00      3  11344563687
80158  4319703577 2016-04-05 22:50:00      3  11344563687
79893  4319703577 2016-04-05 22:51:00      3  11344563687
80159  4319703577 2016-04-05 22:51:00      3  11344563687
79894  4319703577 2016-04-05 22:52:00      2  11344563687
80160  4319703577 2016-04-05 22:52:00      2  11344563687
79895  4319703577 2016-04-05 22:53:00      2  11344563687
80161  4319703577 2016-04-05 22:53:00      2  11344563687
79896  4319703577 2016-04-05 22:54:00      2  11344563687
80162  4319703577 2016-04-05 22:54:00      2  11344563687
79897  4319703577 2016-04-05 22:55:00      1  11344563687
80163  4319703577 2016-04-05 22:55:00      1  11344563687
79898  4319703577 2016-04-05 22:56:00      1  11344563687
80164  4319703577 2016-04-05 22:56:00      1  11344563687
79899  4319703577 2016-04-05 22:57:00      2  11344563687
80165  4319703577 2016-04-05 22:57:00      2  11344563687
79900  4319703577 2016-04-05 22:58:00      2  11344563687
80166  4319703577 2016-04-05 22:58:00      2  11344563687
79901  4319703577 2016-04-05 22:59:00      1  11344563687
80167  4319703577 2016-04-05 22:59:00      1  11344563687

Period 2 Duplicate Summary:
Exact duplicate records: 543
Duplicate participant-log-minute records: 543
Duplicate participant-minute records: 543

Preview of Duplicate Participant-Minute Records:

               Id                date  value        logId
99227  4702921684 2016-05-06 21:10:00      3  11573168523
99770  4702921684 2016-05-06 21:10:00      3  11573168523
99228  4702921684 2016-05-06 21:11:00      3  11573168523
99771  4702921684 2016-05-06 21:11:00      3  11573168523
99229  4702921684 2016-05-06 21:12:00      2  11573168523
99772  4702921684 2016-05-06 21:12:00      2  11573168523
99230  4702921684 2016-05-06 21:13:00      1  11573168523
99773  4702921684 2016-05-06 21:13:00      1  11573168523
99231  4702921684 2016-05-06 21:14:00      1  11573168523
99774  4702921684 2016-05-06 21:14:00      1  11573168523
99232  4702921684 2016-05-06 21:15:00      1  11573168523
99775  4702921684 2016-05-06 21:15:00      1  11573168523
99233  4702921684 2016-05-06 21:16:00      1  11573168523
99776  4702921684 2016-05-06 21:16:00      1  11573168523
99234  4702921684 2016-05-06 21:17:00      1  11573168523
99777  4702921684 2016-05-06 21:17:00      1  11573168523
99235  4702921684 2016-05-06 21:18:00      1  11573168523
99778  4702921684 2016-05-06 21:18:00      1  11573168523
99236  4702921684 2016-05-06 21:19:00      1  11573168523
99779  4702921684 2016-05-06 21:19:00      1  11573168523

In [72]:
# Step 6D.2: Remove exact duplicate minute sleep records

# Create copies to preserve original datasets
sleep_clean_1 = sleep_duplicate_1.copy()
sleep_clean_2 = sleep_duplicate_2.copy()

# Record original dataset sizes
rows_before_1 = len(sleep_clean_1)
rows_before_2 = len(sleep_clean_2)

# Remove exact duplicate observations
# Keep the first occurrence of each identical row
sleep_clean_1 = sleep_clean_1.drop_duplicates(
    keep="first"
).reset_index(drop=True)

sleep_clean_2 = sleep_clean_2.drop_duplicates(
    keep="first"
).reset_index(drop=True)

# Record dataset sizes after cleaning
rows_after_1 = len(sleep_clean_1)
rows_after_2 = len(sleep_clean_2)

# Display cleaning results
print("Period 1 Cleaning Results:")
print("Records before:", rows_before_1)
print("Records after:", rows_after_1)
print("Exact duplicates removed:",
      rows_before_1 - rows_after_1)

print("\nPeriod 2 Cleaning Results:")
print("Records before:", rows_before_2)
print("Records after:", rows_after_2)
print("Exact duplicates removed:",
      rows_before_2 - rows_after_2)

# Display combined totals
print("\nCombined Cleaning Summary:")

print("Total records before:",
      rows_before_1 + rows_before_2)

print("Total records after:",
      rows_after_1 + rows_after_2)

print("Total exact duplicates removed:",
      (rows_before_1 - rows_after_1) +
      (rows_before_2 - rows_after_2))

# Verify no duplicates remain within each period
for label, df in [
    ("Period 1", sleep_clean_1),
    ("Period 2", sleep_clean_2)
]:
    print(f"\n{label} Remaining Duplicates:")

    print("Exact duplicates:",
          df.duplicated().sum())

    print("Participant-log-minute duplicates:",
          df.duplicated(
              subset=["Id", "logId", "date"]
          ).sum())

    print("Participant-minute duplicates:",
          df.duplicated(
              subset=["Id", "date"]
          ).sum())

# Verify original sleep logs were preserved
assert (
    sleep_clean_1[["Id", "logId"]]
    .drop_duplicates().shape[0]
    ==
    sleep_duplicate_1[["Id", "logId"]]
    .drop_duplicates().shape[0]
)

assert (
    sleep_clean_2[["Id", "logId"]]
    .drop_duplicates().shape[0]
    ==
    sleep_duplicate_2[["Id", "logId"]]
    .drop_duplicates().shape[0]
)

# Validate expected record counts
assert rows_after_1 == 198034
assert rows_after_2 == 187978

# Verify no participant-minute duplicates remain
assert not sleep_clean_1.duplicated(
    subset=["Id", "date"]
).any()

assert not sleep_clean_2.duplicated(
    subset=["Id", "date"]
).any()

print("\nExact duplicate removal successful!")

Period 1 Cleaning Results:
Records before: 198559
Records after: 198034
Exact duplicates removed: 525

Period 2 Cleaning Results:
Records before: 188521
Records after: 187978
Exact duplicates removed: 543

Combined Cleaning Summary:
Total records before: 387080
Total records after: 386012
Total exact duplicates removed: 1068

Period 1 Remaining Duplicates:
Exact duplicates: 0
Participant-log-minute duplicates: 0
Participant-minute duplicates: 0

Period 2 Remaining Duplicates:
Exact duplicates: 0
Participant-log-minute duplicates: 0
Participant-minute duplicates: 0

Exact duplicate removal successful!

**Exact Duplicate Records — Minute Sleep**

Data-quality inspections identified 525 exact duplicate observations in Period 1 and 543 in Period 2, for a combined total of 1,068 redundant records.

The duplicates contained identical participant identifiers, timestamps, sleep-state values, and sleep-log identifiers. To prevent duplicate counting and inaccurate sleep-duration calculations, the repeated observations were removed while preserving one copy of each unique record.

After cleaning, Period 1 contained 198,034 observations and Period 2 contained 187,978 observations. All original sleep logs were preserved, and the source CSV files remained unchanged.

In [73]:
# Step 6D.3: Identify overlapping sleep records
# between the two collection periods

# Define participant-minute identifiers
sleep_keys = ["Id", "date"]

# Find observations recorded in both periods
sleep_overlap = sleep_clean_1.merge(
    sleep_clean_2,
    on=sleep_keys,
    how="inner",
    suffixes=("_p1", "_p2"),
    validate="one_to_one"
)

# Count overlapping records
print("Total overlapping participant-minute records:",
      len(sleep_overlap))

# Compare sleep-state measurements
state_match = (
    sleep_overlap["value_p1"] ==
    sleep_overlap["value_p2"]
)

print("\nSleep-State Comparison:")
print("Matching sleep states:", state_match.sum())
print("Different sleep states:", (~state_match).sum())

# Compare sleep-log identifiers
log_match = (
    sleep_overlap["logId_p1"] ==
    sleep_overlap["logId_p2"]
)

print("\nSleep-Log Identifier Comparison:")
print("Matching log IDs:", log_match.sum())
print("Different log IDs:", (~log_match).sum())

# Check whether any measurements or log IDs conflict
sleep_conflicts = sleep_overlap.loc[
    (~state_match) | (~log_match)
]

print("\nOverlapping Records Requiring Investigation:",
      len(sleep_conflicts))

# Display overlapping records
print("\nPreview of Overlapping Records:")
display(sleep_overlap.head(15))

# Display records with conflicting states or log IDs
print("\nPreview of Records Requiring Investigation:")
display(sleep_conflicts.head(15))

# Identify calendar dates containing overlaps
print("\nOverlapping Calendar Dates:")

display(
    sleep_overlap["date"]
    .dt.date
    .value_counts()
    .sort_index()
    .to_frame(name="OverlappingMinutes")
)

# Check whether any participant-log combinations
# appear in both periods
common_logs = sleep_clean_1[
    ["Id", "logId"]
].drop_duplicates().merge(
    sleep_clean_2[
        ["Id", "logId"]
    ].drop_duplicates(),
    on=["Id", "logId"],
    how="inner",
    validate="one_to_one"
)

print("\nParticipant-Log Combinations in Both Periods:",
      len(common_logs))

print("\nPreview of Shared Sleep Logs:")
display(common_logs.head(10))

Total overlapping participant-minute records: 3232

Sleep-State Comparison:
Matching sleep states: 3232
Different sleep states: 0

Sleep-Log Identifier Comparison:
Matching log IDs: 3232
Different log IDs: 0

Overlapping Records Requiring Investigation: 0

Preview of Overlapping Records:

,Id,date,value_p1,logId_p1,value_p2,logId_p2
0,1927972279,2016-04-11 21:56:00,1,11372414035,1,11372414035
1,1927972279,2016-04-11 21:57:00,1,11372414035,1,11372414035
2,1927972279,2016-04-11 21:58:00,1,11372414035,1,11372414035
3,1927972279,2016-04-11 21:59:00,1,11372414035,1,11372414035
4,1927972279,2016-04-11 22:00:00,1,11372414035,1,11372414035
5,1927972279,2016-04-11 22:01:00,1,11372414035,1,11372414035
6,1927972279,2016-04-11 22:02:00,1,11372414035,1,11372414035
7,1927972279,2016-04-11 22:03:00,1,11372414035,1,11372414035
8,1927972279,2016-04-11 22:04:00,1,11372414035,1,11372414035
9,1927972279,2016-04-11 22:05:00,1,11372414035,1,11372414035
10,1927972279,2016-04-11 22:06:00,1,11372414035,1,11372414035
11,1927972279,2016-04-11 22:07:00,1,11372414035,1,11372414035
12,1927972279,2016-04-11 22:08:00,1,11372414035,1,11372414035
13,1927972279,2016-04-11 22:09:00,1,11372414035,1,11372414035
14,1927972279,2016-04-11 22:10:00,1,11372414035,1,11372414035

Preview of Records Requiring Investigation:

Empty DataFrame
Columns: [Id, date, value_p1, logId_p1, value_p2, logId_p2]
Index: []

Overlapping Calendar Dates:

            OverlappingMinutes
date
2016-04-11                 626
2016-04-12                2606

Participant-Log Combinations in Both Periods: 8

Preview of Shared Sleep Logs:

           Id        logId
0  1927972279  11372414035
1  1927972279  11374768075
2  2026352035  11372566564
3  4445114986  11374744422
4  5553957443  11372227280
5  6962181067  11372617693
6  7086361926  11374876178
7  8378563200  11373088895

In [74]:
# Step 6D.4: Consolidate minute sleep datasets

# Create copies of both cleaned datasets
sleep_p1 = sleep_clean_1.copy()
sleep_p2 = sleep_clean_2.copy()

# Label the collection periods
sleep_p1["SourcePeriod"] = "Period 1"
sleep_p2["SourcePeriod"] = "Period 2"

# Combine both collection periods
sleep_combined = pd.concat(
    [sleep_p1, sleep_p2],
    ignore_index=True
)

# Record observations before overlap removal
rows_before = len(sleep_combined)

# Verify that overlapping sleep states match
assert (
    sleep_overlap["value_p1"] ==
    sleep_overlap["value_p2"]
).all()

# Verify that overlapping sleep-log IDs match
assert (
    sleep_overlap["logId_p1"] ==
    sleep_overlap["logId_p2"]
).all()

# Remove overlapping participant-minute observations
# Keep Period 2 because it was appended last
sleep_combined = sleep_combined.drop_duplicates(
    subset=["Id", "date"],
    keep="last"
)

# Sort observations by participant, sleep log, and time
sleep_combined = sleep_combined.sort_values(
    ["Id", "logId", "date"]
).reset_index(drop=True)

# Record observations after overlap removal
rows_after = len(sleep_combined)

# Count removed observations
overlaps_removed = rows_before - rows_after

# Check for remaining participant-minute duplicates
remaining_duplicates = sleep_combined.duplicated(
    subset=["Id", "date"]
).sum()

# Count unique participant-log combinations
unique_sleep_logs = (
    sleep_combined[["Id", "logId"]]
    .drop_duplicates()
    .shape[0]
)

# Display consolidation results
print("Minute Sleep Consolidation Summary:")

print("Records before consolidation:", rows_before)
print("Records after consolidation:", rows_after)
print("Overlapping records removed:", overlaps_removed)

print("\nRemaining participant-minute duplicates:",
      remaining_duplicates)

print("Unique sleep logs:", unique_sleep_logs)

# Display retained records by source period
print("\nRecords by Source Period:")
print(sleep_combined["SourcePeriod"].value_counts())

# Verify which period was retained for overlaps
retained_overlap = sleep_combined.merge(
    sleep_overlap[["Id", "date"]],
    on=["Id", "date"],
    how="inner",
    validate="one_to_one"
)

print("\nSource of Retained Overlapping Records:")
print(retained_overlap["SourcePeriod"].value_counts())

# Validate consolidation results
assert rows_before == 386012
assert rows_after == 382780
assert overlaps_removed == 3232
assert remaining_duplicates == 0
assert unique_sleep_logs == 1007
assert len(retained_overlap) == 3232

# Verify all overlapping records came from Period 2
assert (
    retained_overlap["SourcePeriod"] == "Period 2"
).all()

print("\nMinute sleep consolidation successful!")

Minute Sleep Consolidation Summary:
Records before consolidation: 386012
Records after consolidation: 382780
Overlapping records removed: 3232

Remaining participant-minute duplicates: 0
Unique sleep logs: 1007

Records by Source Period:
SourcePeriod
Period 1    194802
Period 2    187978
Name: count, dtype: int64

Source of Retained Overlapping Records:
SourcePeriod
Period 2    3232
Name: count, dtype: int64

Minute sleep consolidation successful!

**Overlapping Records — Minute Sleep**

After removing exact duplicates within each collection period, the two minute sleep datasets contained 386,012 observations.

A comparison between the datasets identified 3,232 overlapping participant-minute observations, including 626 on April 11, 2016, and 2,606 on April 12, 2016. All overlapping observations contained identical sleep-state measurements and sleep-log identifiers.

To prevent duplicate counting, Period 2 was prioritized when consolidating the datasets. One copy of each overlapping participant-minute observation was retained, while all nonoverlapping observations were preserved.

The resulting dataset contained 382,780 unique participant-minute observations across 1,007 distinct participant-log combinations. The original source files remained unchanged.

In [75]:
# Step 6E.1: Inspect minute sleep recording continuity

# Create a copy to preserve the consolidated dataset
sleep_continuity = sleep_combined.copy()

# Sort observations by participant, sleep log, and time
sleep_continuity = sleep_continuity.sort_values(
    ["Id", "logId", "date"]
).reset_index(drop=True)

# Calculate time differences within each sleep log
sleep_continuity["MinutesSincePrevious"] = (
    sleep_continuity.groupby(["Id", "logId"])["date"]
    .diff()
    .dt.total_seconds() / 60
)

# Identify gaps greater than one minute
sleep_continuity["FlagGap"] = (
    sleep_continuity["MinutesSincePrevious"] > 1
)

# Identify unexpected non-minute intervals
intervals = sleep_continuity[
    "MinutesSincePrevious"
].dropna()

non_minute_intervals = (
    intervals.mod(1).round(8) != 0
).sum()

# Count recording gaps
total_gaps = sleep_continuity["FlagGap"].sum()

# Count sleep logs containing at least one gap
logs_with_gaps = (
    sleep_continuity.groupby(["Id", "logId"])["FlagGap"]
    .any()
    .sum()
)

# Count all unique sleep logs
total_logs = (
    sleep_continuity.groupby(["Id", "logId"])
    .ngroups
)

# Display recording continuity summary
print("Sleep Recording Continuity Summary:")

print("Total observations:", len(sleep_continuity))
print("Total unique sleep logs:", total_logs)
print("Total recording gaps:", total_gaps)
print("Sleep logs with gaps:", logs_with_gaps)
print("Sleep logs without gaps:",
      total_logs - logs_with_gaps)

print("Non-minute recording intervals:",
      non_minute_intervals)

# Display records immediately following gaps
sleep_gap_details = sleep_continuity[
    sleep_continuity["FlagGap"]
].copy()

print("\nTop 10 Largest Recording Gaps:")

display(
    sleep_gap_details[
        [
            "Id",
            "logId",
            "date",
            "MinutesSincePrevious",
            "SourcePeriod"
        ]
    ]
    .sort_values(
        "MinutesSincePrevious",
        ascending=False
    )
    .head(10)
)

# Summarize recording continuity by sleep log
sleep_log_summary = (
    sleep_continuity.groupby(["Id", "logId"])
    .agg(
        StartTime=("date", "min"),
        EndTime=("date", "max"),
        RecordedMinutes=("date", "size"),
        RecordingGaps=("FlagGap", "sum")
    )
    .reset_index()
)

# Calculate elapsed time from first to last observation
# Add one minute to include the first recorded minute
sleep_log_summary["ElapsedMinutes"] = (
    (
        sleep_log_summary["EndTime"] -
        sleep_log_summary["StartTime"]
    ).dt.total_seconds() / 60
) + 1

# Display recording duration statistics
print("\nSleep Log Duration Summary:")

display(
    sleep_log_summary[
        [
            "RecordedMinutes",
            "ElapsedMinutes",
            "RecordingGaps"
        ]
    ]
    .describe()
    .round(2)
)

# Verify expected dataset structure
assert len(sleep_continuity) == 382780
assert total_logs == 1007

print("\nSleep continuity inspection completed!")

Sleep Recording Continuity Summary:
Total observations: 382780
Total unique sleep logs: 1007
Total recording gaps: 0
Sleep logs with gaps: 0
Sleep logs without gaps: 1007
Non-minute recording intervals: 0

Top 10 Largest Recording Gaps:

Empty DataFrame
Columns: [Id, logId, date, MinutesSincePrevious, SourcePeriod]
Index: []

Sleep Log Duration Summary:

       RecordedMinutes  ElapsedMinutes  RecordingGaps
count          1007.00         1007.00         1007.0
mean            380.12          380.12            0.0
std             170.03          170.03            0.0
min              60.00           60.00            0.0
25%             266.50          266.50            0.0
50%             417.00          417.00            0.0
75%             496.00          496.00            0.0
max             961.00          961.00            0.0

Sleep continuity inspection completed!

In [76]:
# Step 6E.2: Investigate unusual sleep-log durations

# Create a copy of the sleep-log summary
sleep_duration_check = sleep_log_summary.copy()

# 1. Flag unusually short sleep logs
# Less than 120 minutes (2 hours)
sleep_duration_check["FlagShortLog"] = (
    sleep_duration_check["RecordedMinutes"] < 120
)

# 2. Flag unusually long sleep logs
# More than 840 minutes (14 hours)
sleep_duration_check["FlagLongLog"] = (
    sleep_duration_check["RecordedMinutes"] > 840
)

# 3. Count flagged sleep logs
short_logs = sleep_duration_check["FlagShortLog"].sum()
long_logs = sleep_duration_check["FlagLongLog"].sum()

# 4. Display duration quality summary
print("Sleep Log Duration Quality Summary:")

print("Total sleep logs:", len(sleep_duration_check))
print("Logs shorter than 120 minutes:", short_logs)
print("Logs longer than 840 minutes:", long_logs)

print("Logs between 120 and 840 minutes:",
      (
          (~sleep_duration_check["FlagShortLog"]) &
          (~sleep_duration_check["FlagLongLog"])
      ).sum())

# 5. Display the ten shortest sleep logs
print("\nTop 10 Shortest Sleep Logs:")

display(
    sleep_duration_check[
        [
            "Id",
            "logId",
            "StartTime",
            "EndTime",
            "RecordedMinutes",
            "RecordingGaps"
        ]
    ]
    .sort_values(
        "RecordedMinutes",
        ascending=True
    )
    .head(10)
)

# 6. Display the ten longest sleep logs
print("\nTop 10 Longest Sleep Logs:")

display(
    sleep_duration_check[
        [
            "Id",
            "logId",
            "StartTime",
            "EndTime",
            "RecordedMinutes",
            "RecordingGaps"
        ]
    ]
    .sort_values(
        "RecordedMinutes",
        ascending=False
    )
    .head(10)
)

# 7. Identify participants with unusual sleep logs
print("\nParticipants with Short Sleep Logs:")

print(
    sleep_duration_check.loc[
        sleep_duration_check["FlagShortLog"], "Id"
    ].nunique()
)

print("\nParticipants with Long Sleep Logs:")

print(
    sleep_duration_check.loc[
        sleep_duration_check["FlagLongLog"], "Id"
    ].nunique()
)

# 8. Validate dataset structure and duration flags
assert len(sleep_duration_check) == 1007
assert (sleep_duration_check["RecordingGaps"] == 0).all()

assert (
    sleep_duration_check["FlagShortLog"] ==
    (sleep_duration_check["RecordedMinutes"] < 120)
).all()

assert (
    sleep_duration_check["FlagLongLog"] ==
    (sleep_duration_check["RecordedMinutes"] > 840)
).all()

print("\nSleep duration inspection completed!")

Sleep Log Duration Quality Summary:
Total sleep logs: 1007
Logs shorter than 120 minutes: 123
Logs longer than 840 minutes: 9
Logs between 120 and 840 minutes: 875

Top 10 Shortest Sleep Logs:

,Id,logId,StartTime,EndTime,RecordedMinutes,RecordingGaps
244,3977333714,11446881699,2016-04-20 12:15:30,2016-04-20 13:14:30,60,0
697,6117666160,11210710662,2016-03-24 14:56:00,2016-03-24 15:55:00,60,0
349,4388161847,11438827489,2016-04-16 15:36:00,2016-04-16 16:35:00,60,0
263,3977333714,11583910496,2016-05-08 14:03:30,2016-05-08 15:03:30,61,0
235,3977333714,11389080820,2016-04-13 20:21:30,2016-04-13 21:21:30,61,0
838,7007744171,11536633979,2016-05-01 11:29:30,2016-05-01 12:29:30,61,0
535,5553957443,11156470370,2016-03-17 18:55:00,2016-03-17 19:55:00,61,0
546,5553957443,11260198135,2016-03-27 15:08:30,2016-03-27 16:08:30,61,0
627,5577150313,11281222431,2016-03-28 21:07:30,2016-03-28 22:08:30,62,0
67,1927972279,11109334617,2016-03-12 19:43:00,2016-03-12 20:44:00,62,0

Top 10 Longest Sleep Logs:

,Id,logId,StartTime,EndTime,RecordedMinutes,RecordingGaps
65,1844505072,11530537917,2016-04-30 20:52:00,2016-05-01 12:52:00,961,0
61,1844505072,11307034191,2016-04-03 20:50:00,2016-04-04 12:50:00,961,0
55,1644430081,11247034534,2016-03-27 15:45:00,2016-03-28 07:45:00,961,0
56,1644430081,11263177587,2016-03-29 21:59:00,2016-03-30 13:59:00,961,0
64,1844505072,11523519346,2016-04-29 22:09:00,2016-04-30 14:09:00,961,0
59,1644430081,11548609830,2016-05-01 18:01:00,2016-05-02 10:01:00,961,0
63,1844505072,11403372987,2016-04-14 20:16:00,2016-04-15 12:16:00,961,0
62,1844505072,11355174555,2016-04-09 13:24:00,2016-04-10 05:24:00,961,0
696,6117666160,11210710486,2016-03-23 21:13:48,2016-03-24 11:48:48,876,0
555,5553957443,11295383457,2016-04-03 00:09:00,2016-04-03 12:39:00,751,0

Participants with Short Sleep Logs:
21

Participants with Long Sleep Logs:
3

Sleep duration inspection completed!

In [77]:
# Step 6E.3: Examine sleep-state composition by sleep log

# 1. Count observations in each sleep state for every participant and sleep log
sleep_state_counts = (
    sleep_continuity.groupby(
        ["Id", "logId", "value"]
    )
    .size()
    .unstack(fill_value=0)
    .reindex(columns=[1, 2, 3], fill_value=0)
    .rename(columns={
        1: "State1Minutes",
        2: "State2Minutes",
        3: "State3Minutes"
    })
    .reset_index()
)

# 2. Combine sleep-state counts with log durations
sleep_state_summary = sleep_duration_check.merge(
    sleep_state_counts,
    on=["Id", "logId"],
    how="left",
    validate="one_to_one"
)

# 3. Calculate total state-classified minutes
sleep_state_summary["TotalStateMinutes"] = (
    sleep_state_summary[
        [
            "State1Minutes",
            "State2Minutes",
            "State3Minutes"
        ]
    ].sum(axis=1)
)

# 4. Calculate percentage of time in each state
for state in [1, 2, 3]:
    sleep_state_summary[f"State{state}Pct"] = (
        sleep_state_summary[f"State{state}Minutes"]
        / sleep_state_summary["RecordedMinutes"]
        * 100
    )

# 5. Display overall sleep-state statistics
print("Sleep-State Composition Summary:")

display(
    sleep_state_summary[
        [
            "State1Minutes",
            "State2Minutes",
            "State3Minutes",
            "State1Pct",
            "State2Pct",
            "State3Pct"
        ]
    ]
    .describe()
    .round(2)
)

# 6. Examine the nine unusually long sleep logs
print("\nSleep-State Composition of Long Logs:")

display(
    sleep_state_summary.loc[
        sleep_state_summary["FlagLongLog"],
        [
            "Id",
            "logId",
            "RecordedMinutes",
            "State1Minutes",
            "State2Minutes",
            "State3Minutes",
            "State1Pct",
            "State2Pct",
            "State3Pct"
        ]
    ]
    .sort_values(
        "RecordedMinutes",
        ascending=False
    )
    .round(2)
)

# 7. Examine the ten shortest sleep logs
print("\nSleep-State Composition of Shortest Logs:")

display(
    sleep_state_summary[
        [
            "Id",
            "logId",
            "RecordedMinutes",
            "State1Minutes",
            "State2Minutes",
            "State3Minutes",
            "State1Pct"
        ]
    ]
    .sort_values("RecordedMinutes")
    .head(10)
    .round(2)
)

# 8. Check for logs with no State 1 minutes
print("\nLogs with Zero State 1 Minutes:",
      (sleep_state_summary["State1Minutes"] == 0).sum())

# 9. Count logs at the observed maximum duration
print("Logs with Exactly 961 Minutes:",
      (sleep_state_summary["RecordedMinutes"] == 961).sum())

# 10. Validate state calculations
assert len(sleep_state_summary) == 1007

assert set(sleep_continuity["value"].unique()).issubset(
    {1, 2, 3}
)

assert (
    sleep_state_summary["TotalStateMinutes"] ==
    sleep_state_summary["RecordedMinutes"]
).all()

assert (
    sleep_state_summary[
        ["State1Minutes", "State2Minutes", "State3Minutes"]
    ].sum().sum() == 382780
)

print("\nSleep-state composition validation passed!")

Sleep-State Composition Summary:

,State1Minutes,State2Minutes,State3Minutes,State1Pct,State2Pct,State3Pct
count,1007.00,1007.00,1007.00,1007.00,1007.00,1007.00
mean,349.48,26.66,3.98,92.15,6.82,1.02
std,156.06,35.23,9.16,7.98,7.67,1.37
min,9.00,0.00,0.00,14.75,0.00,0.00
25%,241.50,10.00,1.00,91.20,3.25,0.18
50%,383.00,18.00,3.00,94.20,4.95,0.70
75%,466.00,29.00,5.00,96.06,7.46,1.41
max,940.00,344.00,129.00,100.00,85.25,13.42

Sleep-State Composition of Long Logs:

,Id,logId,RecordedMinutes,State1Minutes,State2Minutes,State3Minutes,State1Pct,State2Pct,State3Pct
55,1644430081,11247034534,961,839,101,21,87.30,10.51,2.19
56,1644430081,11263177587,961,594,279,88,61.81,29.03,9.16
59,1644430081,11548609830,961,796,36,129,82.83,3.75,13.42
61,1844505072,11307034191,961,940,0,21,97.81,0.00,2.19
62,1844505072,11355174555,961,498,344,119,51.82,35.80,12.38
63,1844505072,11403372987,961,644,229,88,67.01,23.83,9.16
64,1844505072,11523519346,961,722,141,98,75.13,14.67,10.20
65,1844505072,11530537917,961,590,254,117,61.39,26.43,12.17
696,6117666160,11210710486,876,758,57,61,86.53,6.51,6.96

Sleep-State Composition of Shortest Logs:

,Id,logId,RecordedMinutes,State1Minutes,State2Minutes,State3Minutes,State1Pct
244,3977333714,11446881699,60,33,27,0,55.00
697,6117666160,11210710662,60,51,8,1,85.00
349,4388161847,11438827489,60,53,6,1,88.33
263,3977333714,11583910496,61,9,52,0,14.75
235,3977333714,11389080820,61,30,31,0,49.18
838,7007744171,11536633979,61,58,3,0,95.08
535,5553957443,11156470370,61,60,1,0,98.36
546,5553957443,11260198135,61,54,6,1,88.52
627,5577150313,11281222431,62,60,2,0,96.77
67,1927972279,11109334617,62,59,3,0,95.16

Logs with Zero State 1 Minutes: 0
Logs with Exactly 961 Minutes: 8

Sleep-state composition validation passed!

In [78]:
# Step 6F.1: Create final minute sleep quality flags

# 1. Create a copy of the sleep-log summary
sleep_logs_final = sleep_state_summary.copy()

# 2. Flag sleep logs containing exactly 961 minutes
# This is an exploratory quality flag, not proof of an error
sleep_logs_final["FlagDuration961"] = (
    sleep_logs_final["RecordedMinutes"] == 961
)

# 3. Define the episode-level quality flags
quality_flags = [
    "FlagShortLog",
    "FlagLongLog",
    "FlagDuration961"
]

# 4. Summarize flagged sleep logs
print("Sleep Log Quality Flag Summary:")

display(
    sleep_logs_final[quality_flags]
    .sum()
    .to_frame(name="Flagged Sleep Logs")
)

# 5. Create a copy of the cleaned minute-level dataset
sleep_final = sleep_continuity.copy()

# 6. Attach sleep-log quality flags to each minute
# Each minute inherits the flags of its sleep log
sleep_final = sleep_final.merge(
    sleep_logs_final[
        ["Id", "logId"] + quality_flags
    ],
    on=["Id", "logId"],
    how="left",
    validate="many_to_one"
)

# 7. Display final dataset dimensions
print("\nFinal Minute Sleep Dataset:")
print("Rows:", len(sleep_final))
print("Columns:", sleep_final.shape[1])

print("\nFinal Sleep Log Summary:")
print("Rows:", len(sleep_logs_final))
print("Columns:", sleep_logs_final.shape[1])

# 8. Verify all original observations were preserved
assert len(sleep_final) == 382780
assert len(sleep_logs_final) == 1007

# 9. Verify quality flags contain no missing values
assert sleep_final[quality_flags].notna().all().all()

# 10. Verify expected quality flag counts
assert sleep_logs_final["FlagShortLog"].sum() == 123
assert sleep_logs_final["FlagLongLog"].sum() == 9
assert sleep_logs_final["FlagDuration961"].sum() == 8

# 11. Verify the sleep-log summary accounts for every minute
assert (
    sleep_logs_final["RecordedMinutes"].sum()
    == len(sleep_final)
)

# 12. Verify no participant-minute duplicates remain
assert not sleep_final.duplicated(
    subset=["Id", "date"]
).any()

# 13. Verify no sleep logs have recording gaps
assert (sleep_logs_final["RecordingGaps"] == 0).all()

# 14. Display sample observations from both datasets
print("\nMinute-Level Dataset Preview:")
display(sleep_final.head())

print("\nSleep-Log Summary Preview:")
display(sleep_logs_final.head())

print("\nSleep quality flag preparation successful!")

Sleep Log Quality Flag Summary:

                 Flagged Sleep Logs
FlagShortLog                    123
FlagLongLog                       9
FlagDuration961                   8

Final Minute Sleep Dataset:
Rows: 382780
Columns: 10

Final Sleep Log Summary:
Rows: 1007
Columns: 17

Minute-Level Dataset Preview:

,Id,date,value,logId,SourcePeriod,MinutesSincePrevious,FlagGap,FlagShortLog,FlagLongLog,FlagDuration961
0,1503960366,2016-03-13 02:39:30,1,11114919637,Period 1,NaN,False,False,False,False
1,1503960366,2016-03-13 02:40:30,1,11114919637,Period 1,1.0,False,False,False,False
2,1503960366,2016-03-13 02:41:30,1,11114919637,Period 1,1.0,False,False,False,False
3,1503960366,2016-03-13 02:42:30,1,11114919637,Period 1,1.0,False,False,False,False
4,1503960366,2016-03-13 02:43:30,1,11114919637,Period 1,1.0,False,False,False,False

Sleep-Log Summary Preview:

,Id,logId,StartTime,EndTime,RecordedMinutes,RecordingGaps,ElapsedMinutes,FlagShortLog,FlagLongLog,State1Minutes,State2Minutes,State3Minutes,TotalStateMinutes,State1Pct,State2Pct,State3Pct,FlagDuration961
0,1503960366,11114919637,2016-03-13 02:39:30,2016-03-13 09:44:30,426,0,426.0,False,False,411,15,0,426,96.478873,3.521127,0.000000,False
1,1503960366,11126343681,2016-03-14 01:32:00,2016-03-14 07:57:00,386,0,386.0,False,False,354,27,5,386,91.709845,6.994819,1.295337,False
2,1503960366,11134971215,2016-03-15 02:36:00,2016-03-15 08:10:00,335,0,335.0,False,False,312,16,7,335,93.134328,4.776119,2.089552,False
3,1503960366,11142197163,2016-03-16 03:12:00,2016-03-16 08:14:00,303,0,303.0,False,False,272,26,5,303,89.768977,8.580858,1.650165,False
4,1503960366,11142197164,2016-03-16 19:43:00,2016-03-16 20:45:00,63,0,63.0,True,False,61,2,0,63,96.825397,3.174603,0.000000,False

Sleep quality flag preparation successful!

In [79]:
# Step 6F.2: Finalize minute sleep dataset structures

# ==========================================
# PART 1: Prepare minute-level observations
# ==========================================

# Select columns needed for future analysis
# Temporary diagnostic columns remain available in sleep_continuity and sleep_final
minute_columns = [
    "Id",
    "date",
    "value",
    "logId",
    "SourcePeriod",
    "FlagShortLog",
    "FlagLongLog",
    "FlagDuration961"
]

# Create the organized minute-level dataset
sleep_minutes_ready = (
    sleep_final[minute_columns]
    .sort_values(["Id", "logId", "date"])
    .reset_index(drop=True)
    .copy()
)

# ==========================================
# PART 2: Prepare sleep-log summary
# ==========================================

# Create a copy of the sleep-log summary
sleep_logs_ready = sleep_logs_final.copy()

# Extract the calendar date when each log ends
# Overnight logs are assigned their ending date
sleep_logs_ready["SleepEndDate"] = (
    sleep_logs_ready["EndTime"].dt.date
)

# Convert recorded minutes to hours
sleep_logs_ready["RecordedHours"] = (
    sleep_logs_ready["RecordedMinutes"] / 60
).round(2)

# Organize columns into a logical order
log_columns = [
    "Id",
    "logId",
    "StartTime",
    "EndTime",
    "SleepEndDate",
    "RecordedMinutes",
    "RecordedHours",
    "ElapsedMinutes",
    "RecordingGaps",
    "State1Minutes",
    "State2Minutes",
    "State3Minutes",
    "TotalStateMinutes",
    "State1Pct",
    "State2Pct",
    "State3Pct",
    "FlagShortLog",
    "FlagLongLog",
    "FlagDuration961"
]

# Select and sort the final sleep-log columns
sleep_logs_ready = (
    sleep_logs_ready[log_columns]
    .sort_values(["Id", "StartTime", "logId"])
    .reset_index(drop=True)
)

# ==========================================
# PART 3: Verify both dataset structures
# ==========================================

# Verify all observations were preserved
assert sleep_minutes_ready.shape == (382780, 8)
assert sleep_logs_ready.shape == (1007, 19)

# Verify participant-minute uniqueness
assert not sleep_minutes_ready.duplicated(
    subset=["Id", "date"]
).any()

# Verify sleep-log uniqueness
assert not sleep_logs_ready.duplicated(
    subset=["Id", "logId"]
).any()

# Verify no recorded minutes were lost
assert (
    sleep_logs_ready["RecordedMinutes"].sum()
    == len(sleep_minutes_ready)
)

# Verify quality flags remain unchanged
assert sleep_logs_ready["FlagShortLog"].sum() == 123
assert sleep_logs_ready["FlagLongLog"].sum() == 9
assert sleep_logs_ready["FlagDuration961"].sum() == 8

# ==========================================
# PART 4: Display the final structures
# ==========================================

print("Final Minute-Level Dataset:")
print("Shape:", sleep_minutes_ready.shape)
print("Columns:", sleep_minutes_ready.columns.tolist())

print("\nFinal Sleep-Log Summary:")
print("Shape:", sleep_logs_ready.shape)
print("Columns:", sleep_logs_ready.columns.tolist())

print("\nMinute-Level Preview:")
display(sleep_minutes_ready.head())

print("\nSleep-Log Summary Preview:")
display(sleep_logs_ready.head())

print("\nSleep dataset structure preparation successful!")

Final Minute-Level Dataset:
Shape: (382780, 8)
Columns: ['Id', 'date', 'value', 'logId', 'SourcePeriod', 'FlagShortLog', 'FlagLongLog', 'FlagDuration961']

Final Sleep-Log Summary:
Shape: (1007, 19)
Columns: ['Id', 'logId', 'StartTime', 'EndTime', 'SleepEndDate', 'RecordedMinutes', 'RecordedHours', 'ElapsedMinutes', 'RecordingGaps', 'State1Minutes', 'State2Minutes', 'State3Minutes', 'TotalStateMinutes', 'State1Pct', 'State2Pct', 'State3Pct', 'FlagShortLog', 'FlagLongLog', 'FlagDuration961']

Minute-Level Preview:

,Id,date,value,logId,SourcePeriod,FlagShortLog,FlagLongLog,FlagDuration961
0,1503960366,2016-03-13 02:39:30,1,11114919637,Period 1,False,False,False
1,1503960366,2016-03-13 02:40:30,1,11114919637,Period 1,False,False,False
2,1503960366,2016-03-13 02:41:30,1,11114919637,Period 1,False,False,False
3,1503960366,2016-03-13 02:42:30,1,11114919637,Period 1,False,False,False
4,1503960366,2016-03-13 02:43:30,1,11114919637,Period 1,False,False,False

Sleep-Log Summary Preview:

,Id,logId,StartTime,EndTime,SleepEndDate,RecordedMinutes,RecordedHours,ElapsedMinutes,RecordingGaps,State1Minutes,State2Minutes,State3Minutes,TotalStateMinutes,State1Pct,State2Pct,State3Pct,FlagShortLog,FlagLongLog,FlagDuration961
0,1503960366,11114919637,2016-03-13 02:39:30,2016-03-13 09:44:30,2016-03-13,426,7.10,426.0,0,411,15,0,426,96.478873,3.521127,0.000000,False,False,False
1,1503960366,11126343681,2016-03-14 01:32:00,2016-03-14 07:57:00,2016-03-14,386,6.43,386.0,0,354,27,5,386,91.709845,6.994819,1.295337,False,False,False
2,1503960366,11134971215,2016-03-15 02:36:00,2016-03-15 08:10:00,2016-03-15,335,5.58,335.0,0,312,16,7,335,93.134328,4.776119,2.089552,False,False,False
3,1503960366,11142197163,2016-03-16 03:12:00,2016-03-16 08:14:00,2016-03-16,303,5.05,303.0,0,272,26,5,303,89.768977,8.580858,1.650165,False,False,False
4,1503960366,11142197164,2016-03-16 19:43:00,2016-03-16 20:45:00,2016-03-16,63,1.05,63.0,0,61,2,0,63,96.825397,3.174603,0.000000,True,False,False

Sleep dataset structure preparation successful!

In [80]:
# Step 6G.1: Final validation of cleaned sleep datasets

# ==========================================
# 1. Validate dataset dimensions
# ==========================================

print("Final Sleep Dataset Validation:")

print("\nMinute-Level Shape:",
      sleep_minutes_ready.shape)

print("Sleep-Log Summary Shape:",
      sleep_logs_ready.shape)

assert sleep_minutes_ready.shape == (382780, 8)
assert sleep_logs_ready.shape == (1007, 19)


# ==========================================
# 2. Check missing values
# ==========================================

print("\nMissing Values — Minute-Level Dataset:")
print(sleep_minutes_ready.isna().sum())

print("\nMissing Values — Sleep-Log Summary:")
print(sleep_logs_ready.isna().sum())

assert sleep_minutes_ready.notna().all().all()
assert sleep_logs_ready.notna().all().all()


# ==========================================
# 3. Validate record uniqueness
# ==========================================

minute_duplicates = sleep_minutes_ready.duplicated(
    subset=["Id", "date"]
).sum()

log_duplicates = sleep_logs_ready.duplicated(
    subset=["Id", "logId"]
).sum()

print("\nDuplicate Validation:")
print("Duplicate participant-minute records:",
      minute_duplicates)

print("Duplicate participant-log records:",
      log_duplicates)

assert minute_duplicates == 0
assert log_duplicates == 0


# ==========================================
# 4. Verify valid sleep-state codes
# ==========================================

print("\nSleep-State Values:")

print(
    sorted(sleep_minutes_ready["value"].unique())
)

assert set(
    sleep_minutes_ready["value"].unique()
) == {1, 2, 3}


# ==========================================
# 5. Recalculate sleep-log measurements
# ==========================================

# Reconstruct episode statistics from minute data
log_recalculated = (
    sleep_minutes_ready.groupby(
        ["Id", "logId"],
        as_index=False
    )
    .agg(
        RecalculatedMinutes=("date", "size"),
        RecalculatedStart=("date", "min"),
        RecalculatedEnd=("date", "max")
    )
)

# Match recalculated statistics to the summary
log_validation = sleep_logs_ready.merge(
    log_recalculated,
    on=["Id", "logId"],
    how="outer",
    indicator=True,
    validate="one_to_one"
)

# Verify all 1,007 sleep logs match
assert len(log_validation) == 1007
assert (log_validation["_merge"] == "both").all()

# Verify recorded minute counts
assert (
    log_validation["RecordedMinutes"] ==
    log_validation["RecalculatedMinutes"]
).all()

# Verify episode timestamps
assert (
    log_validation["StartTime"] ==
    log_validation["RecalculatedStart"]
).all()

assert (
    log_validation["EndTime"] ==
    log_validation["RecalculatedEnd"]
).all()

print("\nSleep-log counts and timestamps match!")


# ==========================================
# 6. Validate sleep-state totals
# ==========================================

state_columns = [
    "State1Minutes",
    "State2Minutes",
    "State3Minutes"
]

# Every recorded minute must belong to one state
assert (
    sleep_logs_ready[state_columns].sum(axis=1)
    == sleep_logs_ready["RecordedMinutes"]
).all()

# Verify overall observation total
assert (
    sleep_logs_ready[state_columns].sum().sum()
    == 382780
)

# Validate percentages sum to approximately 100%
percentage_columns = [
    "State1Pct",
    "State2Pct",
    "State3Pct"
]

assert np.allclose(
    sleep_logs_ready[percentage_columns].sum(axis=1),
    100,
    atol=0.01
)

print("Sleep-state totals and percentages validated!")


# ==========================================
# 7. Validate duration quality flags
# ==========================================

assert sleep_logs_ready["FlagShortLog"].sum() == 123
assert sleep_logs_ready["FlagLongLog"].sum() == 9
assert sleep_logs_ready["FlagDuration961"].sum() == 8

# Verify flags agree between datasets
flags = [
    "FlagShortLog",
    "FlagLongLog",
    "FlagDuration961"
]

flag_validation = sleep_minutes_ready.merge(
    sleep_logs_ready[["Id", "logId"] + flags],
    on=["Id", "logId"],
    how="left",
    suffixes=("_minute", "_log"),
    validate="many_to_one",
    indicator=True
)

assert (flag_validation["_merge"] == "both").all()

for flag in flags:
    assert (
        flag_validation[f"{flag}_minute"] ==
        flag_validation[f"{flag}_log"]
    ).all()

print("All quality flags validated!")


# ==========================================
# 8. Display final validation summary
# ==========================================

print("\nFinal Validation Summary:")

print("Minute-level observations:",
      len(sleep_minutes_ready))

print("Unique sleep logs:",
      len(sleep_logs_ready))

print("Total recorded minutes:",
      sleep_logs_ready["RecordedMinutes"].sum())

print("Duplicate participant-minutes:",
      minute_duplicates)

print("Duplicate participant-logs:",
      log_duplicates)

print("Short sleep logs:",
      sleep_logs_ready["FlagShortLog"].sum())

print("Long sleep logs:",
      sleep_logs_ready["FlagLongLog"].sum())

print("Logs with exactly 961 minutes:",
      sleep_logs_ready["FlagDuration961"].sum())

print("\nAll sleep dataset validation checks passed!")

Final Sleep Dataset Validation:

Minute-Level Shape: (382780, 8)
Sleep-Log Summary Shape: (1007, 19)

Missing Values — Minute-Level Dataset:
Id                 0
date               0
value              0
logId              0
SourcePeriod       0
FlagShortLog       0
FlagLongLog        0
FlagDuration961    0
dtype: int64

Missing Values — Sleep-Log Summary:
Id                   0
logId                0
StartTime            0
EndTime              0
SleepEndDate         0
RecordedMinutes      0
RecordedHours        0
ElapsedMinutes       0
RecordingGaps        0
State1Minutes        0
State2Minutes        0
State3Minutes        0
TotalStateMinutes    0
State1Pct            0
State2Pct            0
State3Pct            0
FlagShortLog         0
FlagLongLog          0
FlagDuration961      0
dtype: int64

Duplicate Validation:
Duplicate participant-minute records: 0
Duplicate participant-log records: 0

Sleep-State Values:
[np.int64(1), np.int64(2), np.int64(3)]

Sleep-log counts and timestamps match!
Sleep-state totals and percentages validated!
All quality flags validated!

Final Validation Summary:
Minute-level observations: 382780
Unique sleep logs: 1007
Total recorded minutes: 382780
Duplicate participant-minutes: 0
Duplicate participant-logs: 0
Short sleep logs: 123
Long sleep logs: 9
Logs with exactly 961 minutes: 8

All sleep dataset validation checks passed!

In [81]:
# Step 6H.1: Export cleaned minute sleep datasets

# Create copies of both finalized datasets
minute_export = sleep_minutes_ready.copy()
logs_export = sleep_logs_ready.copy()

# Standardize the SleepEndDate column for CSV export
logs_export["SleepEndDate"] = pd.to_datetime(
    logs_export["SleepEndDate"]
)

# Define the output folder
# cleaned_path was created earlier in the Process Phase
cleaned_path.mkdir(parents=True, exist_ok=True)

# Define output file paths
minute_output = cleaned_path / "minuteSleep_clean.csv"

logs_output = cleaned_path / "sleepLog_summary_clean.csv"

# Export minute-level dataset
minute_export.to_csv(
    minute_output,
    index=False
)

# Export sleep-log summary dataset
logs_export.to_csv(
    logs_output,
    index=False
)

# Confirm exported files exist
assert minute_output.is_file()
assert logs_output.is_file()

# Display export confirmation
print("Minute Sleep Datasets Exported Successfully!")

print("\nMinute-Level Dataset:")
print("File:", minute_output)
print("Rows:", len(minute_export))
print("Columns:", minute_export.shape[1])

print("\nSleep-Log Summary:")
print("File:", logs_output)
print("Rows:", len(logs_export))
print("Columns:", logs_export.shape[1])

Minute Sleep Datasets Exported Successfully!

Minute-Level Dataset:
File: /Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/minuteSleep_clean.csv
Rows: 382780
Columns: 8

Sleep-Log Summary:
File: /Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/sleepLog_summary_clean.csv
Rows: 1007
Columns: 19

In [82]:
# Step 6H.2: Verify exported minute sleep datasets

# Reload minute-level CSV
verify_minutes = pd.read_csv(
    minute_output,
    parse_dates=["date"],
    float_precision="round_trip"
)

# Reload sleep-log summary CSV
verify_logs = pd.read_csv(
    logs_output,
    parse_dates=[
        "StartTime",
        "EndTime",
        "SleepEndDate"
    ],
    float_precision="round_trip"
)

# ==========================================
# 1. Verify dataset dimensions
# ==========================================

assert verify_minutes.shape == (382780, 8)
assert verify_logs.shape == (1007, 19)

# ==========================================
# 2. Verify column names
# ==========================================

assert verify_minutes.columns.tolist() == (
    minute_export.columns.tolist()
)

assert verify_logs.columns.tolist() == (
    logs_export.columns.tolist()
)

# ==========================================
# 3. Verify exported data against originals
# ==========================================

# Allow only negligible floating-point differences
pd.testing.assert_frame_equal(
    minute_export,
    verify_minutes,
    check_dtype=False,
    check_exact=False,
    rtol=1e-10,
    atol=1e-10
)

pd.testing.assert_frame_equal(
    logs_export,
    verify_logs,
    check_dtype=False,
    check_exact=False,
    rtol=1e-10,
    atol=1e-10
)

# ==========================================
# 4. Verify uniqueness
# ==========================================

assert not verify_minutes.duplicated(
    subset=["Id", "date"]
).any()

assert not verify_logs.duplicated(
    subset=["Id", "logId"]
).any()

# ==========================================
# 5. Verify all minutes are represented
# ==========================================

assert (
    verify_logs["RecordedMinutes"].sum()
    == len(verify_minutes)
)

# ==========================================
# 6. Verify quality flags
# ==========================================

assert verify_logs["FlagShortLog"].sum() == 123
assert verify_logs["FlagLongLog"].sum() == 9
assert verify_logs["FlagDuration961"].sum() == 8

# ==========================================
# 7. Display verification results
# ==========================================

print("Export Verification Successful!")

print("\nMinute-Level Dataset Shape:",
      verify_minutes.shape)

print("Sleep-Log Summary Shape:",
      verify_logs.shape)

print("\nTotal Recorded Minutes:",
      verify_logs["RecordedMinutes"].sum())

print("\nMissing Values:")
print("Minute-Level:", verify_minutes.isna().sum().sum())
print("Sleep-Log Summary:", verify_logs.isna().sum().sum())

print("\nQuality Flag Summary:")
print(
    verify_logs[
        [
            "FlagShortLog",
            "FlagLongLog",
            "FlagDuration961"
        ]
    ].sum()
)

print("\nBoth exported datasets match their originals!")

Export Verification Successful!

Minute-Level Dataset Shape: (382780, 8)
Sleep-Log Summary Shape: (1007, 19)

Total Recorded Minutes: 382780

Missing Values:
Minute-Level: 0
Sleep-Log Summary: 0

Quality Flag Summary:
FlagShortLog       123
FlagLongLog          9
FlagDuration961      8
dtype: int64

Both exported datasets match their originals!

## Heartrate Data Processing

In [83]:

# Step 7A.1: Locate and inspect heart rate datasets

# Find both heart rate CSV files
heart_files = sorted(
    project_path.rglob("heartrate_seconds_merged.csv")
)

# Confirm exactly two files were found
assert len(heart_files) == 2, (
    f"Expected 2 heart rate files, found {len(heart_files)}"
)

# Display the file locations and sizes
print("Heart Rate Dataset Files:")

for i, file in enumerate(heart_files, start=1):
    print(f"\nPeriod {i}:")
    print("File:", file.relative_to(project_path))
    print("File Size (MB):", round(
        file.stat().st_size / (1024 ** 2), 2
    ))

# Preview the first five observations from each file
for i, file in enumerate(heart_files, start=1):

    # Read only the first five records
    preview = pd.read_csv(
        file,
        nrows=5,
        dtype={"Id": "string"}
    )

    print(f"\nPeriod {i} Preview:")
    display(preview)

    # Display column information
    print("Column Names:", preview.columns.tolist())
    print("\nData Types:")
    print(preview.dtypes)
    print("Number of Columns:", preview.shape[1])

print("\nHeart rate file inspection completed!")

Heart Rate Dataset Files:

Period 1:
File: Fitabase Data 3.12.16-4.11.16/heartrate_seconds_merged.csv
File Size (MB): 39.17

Period 2:
File: Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv
File Size (MB): 85.44

Period 1 Preview:

           Id                 Time  Value
0  2022484408  4/1/2016 7:54:00 AM     93
1  2022484408  4/1/2016 7:54:05 AM     91
2  2022484408  4/1/2016 7:54:10 AM     96
3  2022484408  4/1/2016 7:54:15 AM     98
4  2022484408  4/1/2016 7:54:20 AM    100

Column Names: ['Id', 'Time', 'Value']

Data Types:
Id       string[python]
Time             object
Value             int64
dtype: object
Number of Columns: 3

Period 2 Preview:

           Id                  Time  Value
0  2022484408  4/12/2016 7:21:00 AM     97
1  2022484408  4/12/2016 7:21:05 AM    102
2  2022484408  4/12/2016 7:21:10 AM    105
3  2022484408  4/12/2016 7:21:20 AM    103
4  2022484408  4/12/2016 7:21:25 AM    101

Column Names: ['Id', 'Time', 'Value']

Data Types:
Id       string[python]
Time             object
Value             int64
dtype: object
Number of Columns: 3

Heart rate file inspection completed!

In [84]:
# Step 7A.2: Import complete heart rate datasets

# ==========================================
# 1. Load both heart rate datasets
# ==========================================

# Period 1: March 12 - April 11, 2016
heart_1 = pd.read_csv(
    heart_files[0],
    dtype={
        "Id": "category",
        "Value": "Int32"
    },
    parse_dates=["Time"],
    date_format="%m/%d/%Y %I:%M:%S %p"
)

# Period 2: April 12 - May 12, 2016
heart_2 = pd.read_csv(
    heart_files[1],
    dtype={
        "Id": "category",
        "Value": "Int32"
    },
    parse_dates=["Time"],
    date_format="%m/%d/%Y %I:%M:%S %p"
)

# ==========================================
# 2. Display dataset dimensions
# ==========================================

print("Heart Rate Dataset Dimensions:")

print("Period 1:", heart_1.shape)
print("Period 2:", heart_2.shape)

# ==========================================
# 3. Inspect data types
# ==========================================

print("\nPeriod 1 Information:")
heart_1.info()

print("\nPeriod 2 Information:")
heart_2.info()

# ==========================================
# 4. Check memory usage
# ==========================================

print("\nMemory Usage:")

print(
    "Period 1 (MB):",
    round(
        heart_1.memory_usage(deep=True).sum()
        / (1024 ** 2),
        2
    )
)

print(
    "Period 2 (MB):",
    round(
        heart_2.memory_usage(deep=True).sum()
        / (1024 ** 2),
        2
    )
)

# ==========================================
# 5. Check column consistency
# ==========================================

print("\nColumn Names Match:",
      heart_1.columns.equals(heart_2.columns))

# ==========================================
# 6. Preview complete datasets
# ==========================================

print("\nPeriod 1 Preview:")
display(heart_1.head())

print("\nPeriod 2 Preview:")
display(heart_2.head())

print("\nHeart rate datasets imported successfully!")

Heart Rate Dataset Dimensions:
Period 1: (1154681, 3)
Period 2: (2483658, 3)

Period 1 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1154681 entries, 0 to 1154680
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Id      1154681 non-null  category
 1   Time    1154681 non-null  datetime64[ns]
 2   Value   1154681 non-null  Int32
dtypes: Int32(1), category(1), datetime64[ns](1)
memory usage: 15.4 MB

Period 2 Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2483658 entries, 0 to 2483657
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   Id      category
 1   Time    datetime64[ns]
 2   Value   Int32
dtypes: Int32(1), category(1), datetime64[ns](1)
memory usage: 33.2 MB

Memory Usage:
Period 1 (MB): 15.42
Period 2 (MB): 33.16

Column Names Match: True

Period 1 Preview:

           Id                Time  Value
0  2022484408 2016-04-01 07:54:00     93
1  2022484408 2016-04-01 07:54:05     91
2  2022484408 2016-04-01 07:54:10     96
3  2022484408 2016-04-01 07:54:15     98
4  2022484408 2016-04-01 07:54:20    100

Period 2 Preview:

           Id                Time  Value
0  2022484408 2016-04-12 07:21:00     97
1  2022484408 2016-04-12 07:21:05    102
2  2022484408 2016-04-12 07:21:10    105
3  2022484408 2016-04-12 07:21:20    103
4  2022484408 2016-04-12 07:21:25    101

Heart rate datasets imported successfully!

In [85]:
# Step 7A.3: Inspect heart rate structure and coverage

# ==========================================
# 1. Display basic dataset information
# ==========================================

print("Heart Rate Dataset Coverage:")

# Process each collection period separately
for label, df in [
    ("Period 1", heart_1),
    ("Period 2", heart_2)
]:

    print(f"\n===== {label} =====")

    # Total observations
    print("Total observations:", len(df))

    # Count unique participants
    print(
        "Unique participants:",
        df["Id"].nunique()
    )

    # Display earliest and latest timestamps
    print("Earliest timestamp:", df["Time"].min())
    print("Latest timestamp:", df["Time"].max())

    # Count distinct calendar dates
    print(
        "Unique calendar dates:",
        df["Time"].dt.normalize().nunique()
    )

# ======================================
# 2. Inspect heart rate measurements
# ======================================

    print("\nHeart Rate Summary Statistics:")

    # Display descriptive statistics
    display(df["Value"].describe().round(2))

# ======================================
# 3. Display measurement range
# ======================================

    print("Minimum heart rate:", df["Value"].min())

    print("Maximum heart rate:", df["Value"].max())

    print(
        "Median heart rate:",
        df["Value"].median()
    )

# ======================================
# 4. Check participant coverage
# ======================================

    print("\nObservations per Participant:")

    participant_counts = (
        df.groupby("Id", observed=True)
        .size()
        .sort_values(ascending=False)
    )

    # Display participant record counts
    display(
        participant_counts.to_frame(
            name="Observations"
        )
    )

# ==========================================
# 5. Compare participants across periods
# ==========================================

# Retrieve participant identifiers
participants_1 = set(
    heart_1["Id"].astype(str).unique()
)

participants_2 = set(
    heart_2["Id"].astype(str).unique()
)

# Identify participants present in both periods
shared_participants = (
    participants_1.intersection(participants_2)
)

print("\n===== Participant Comparison =====")

print("Period 1 participants:", len(participants_1))
print("Period 2 participants:", len(participants_2))

print(
    "Participants in both periods:",
    len(shared_participants)
)

print(
    "Total unique participants:",
    len(participants_1.union(participants_2))
)

print("\nHeart rate coverage inspection completed!")

Heart Rate Dataset Coverage:

===== Period 1 =====
Total observations: 1154681
Unique participants: 14
Earliest timestamp: 2016-03-29 00:00:05
Latest timestamp: 2016-04-12 11:03:15
Unique calendar dates: 15

Heart Rate Summary Statistics:

count    1154681.0
mean         79.76
std          18.73
min           36.0
25%           66.0
50%           77.0
75%           90.0
max          185.0
Name: Value, dtype: Float64

Minimum heart rate: 36
Maximum heart rate: 185
Median heart rate: 77.0

Observations per Participant:

            Observations
Id
4020332650        283794
6962181067        125875
2347167796        120804
5553957443         97797
5577150313         87649
8877689391         85115
8792009665         70087
4558609924         69339
7007744171         64786
2022484408         56483
6117666160         53666
6775888955         35100
6391747486          3747
2026352035           439

===== Period 2 =====
Total observations: 2483658
Unique participants: 14
Earliest timestamp: 2016-04-12 00:00:00
Latest timestamp: 2016-05-12 16:20:00
Unique calendar dates: 31

Heart Rate Summary Statistics:

count    2483658.0
mean         77.33
std           19.4
min           36.0
25%           63.0
50%           73.0
75%           88.0
max          203.0
Name: Value, dtype: Float64

Minimum heart rate: 36
Maximum heart rate: 203
Median heart rate: 73.0

Observations per Participant:

            Observations
Id
4020332650        285461
6962181067        266326
5553957443        255174
4388161847        249748
5577150313        248560
8877689391        228841
4558609924        192168
6117666160        158899
2022484408        154104
2347167796        152683
7007744171        133592
8792009665        122841
6775888955         32771
2026352035          2490

===== Participant Comparison =====
Period 1 participants: 14
Period 2 participants: 14
Participants in both periods: 13
Total unique participants: 15

Heart rate coverage inspection completed!

In [86]:

# Step 7B.1: Inspect missing and invalid heart rate values

# ==========================================
# 1. Inspect each collection period
# ==========================================

for label, df in [
    ("Period 1", heart_1),
    ("Period 2", heart_2)
]:

    print(f"\n===== {label} =====")

    # Display total records
    print("Total observations:", len(df))

# ======================================
# 2. Check missing values
# ======================================

    print("\nMissing Values:")

    missing_counts = df.isna().sum()

    missing_percent = (
        missing_counts / len(df) * 100
    )

    # Create missing value summary table
    missing_summary = pd.DataFrame({
        "Missing Count": missing_counts,
        "Missing (%)": missing_percent
    })

    display(missing_summary.round(2))

    print(
        "Total missing values:",
        missing_counts.sum()
    )

# ======================================
# 3. Check invalid timestamps
# ======================================

    invalid_timestamps = df["Time"].isna().sum()

    print("\nTimestamp Validation:")

    print(
        "Invalid or missing timestamps:",
        invalid_timestamps
    )

    print(
        "Timestamp data type:",
        df["Time"].dtype
    )

# ======================================
# 4. Check heart rate measurements
# ======================================

    print("\nHeart Rate Value Checks:")

    # Missing heart rate observations
    missing_hr = df["Value"].isna().sum()

    # Nonpositive values are invalid as
    # recorded heart rates
    zero_hr = (df["Value"] == 0).sum()
    negative_hr = (df["Value"] < 0).sum()

    print("Missing heart rate values:", missing_hr)
    print("Zero heart rate values:", zero_hr)
    print("Negative heart rate values:", negative_hr)

# ======================================
# 5. Preview problematic records
# ======================================

    problem_mask = (
        df["Id"].isna()
        | df["Time"].isna()
        | df["Value"].isna()
        | (df["Value"] <= 0).fillna(False)
    )

    problem_records = df.loc[problem_mask]

    print("\nRecords requiring investigation:",
          len(problem_records))

    display(problem_records.head(10))

print("\nHeart rate missing-value inspection completed!")

===== Period 1 =====
Total observations: 1154681

Missing Values:

       Missing Count  Missing (%)
Id                 0          0.0
Time               0          0.0
Value              0          0.0

Total missing values: 0

Timestamp Validation:
Invalid or missing timestamps: 0
Timestamp data type: datetime64[ns]

Heart Rate Value Checks:
Missing heart rate values: 0
Zero heart rate values: 0
Negative heart rate values: 0

Records requiring investigation: 0

Empty DataFrame
Columns: [Id, Time, Value]
Index: []

===== Period 2 =====
Total observations: 2483658

Missing Values:

       Missing Count  Missing (%)
Id                 0          0.0
Time               0          0.0
Value              0          0.0

Total missing values: 0

Timestamp Validation:
Invalid or missing timestamps: 0
Timestamp data type: datetime64[ns]

Heart Rate Value Checks:
Missing heart rate values: 0
Zero heart rate values: 0
Negative heart rate values: 0

Records requiring investigation: 0

Empty DataFrame
Columns: [Id, Time, Value]
Index: []

Heart rate missing-value inspection completed!

In [87]:
# Step 7B.2: Inspect heart rate recording intervals

# ==========================================
# 1. Inspect each collection period
# ==========================================

for label, df in [
    ("Period 1", heart_1),
    ("Period 2", heart_2)
]:

    print(f"\n===== {label} =====")

    # Create a temporary copy with relevant columns
    intervals_df = df[
        ["Id", "Time"]
    ].copy()

    # Sort observations by participant and time
    intervals_df = intervals_df.sort_values(
        ["Id", "Time"]
    )

# ======================================
# 2. Calculate time between observations
# ======================================

    # Calculate intervals separately for each participant
    intervals_df["SecondsSincePrevious"] = (
        intervals_df
        .groupby("Id", observed=True)["Time"]
        .diff()
        .dt.total_seconds()
    )

    # Exclude the first observation per participant,
    # which has no previous timestamp
    intervals = (
        intervals_df["SecondsSincePrevious"]
        .dropna()
    )

# ======================================
# 3. Display interval statistics
# ======================================

    print("\nRecording Interval Statistics:")

    print("Total intervals:", len(intervals))

    display(intervals.describe().round(2))

# ======================================
# 4. Identify recording frequencies
# ======================================

    print("\nTop 10 Most Common Intervals (Seconds):")

    interval_frequency = (
        intervals.value_counts()
        .head(10)
        .to_frame(name="Observations")
    )

    display(interval_frequency)

# ======================================
# 5. Check irregular intervals
# ======================================

    print("\nRecording Interval Checks:")

    print(
        "Exactly 5 seconds:",
        (intervals == 5).sum()
    )

    print(
        "Less than 5 seconds (positive):",
        ((intervals > 0) & (intervals < 5)).sum()
    )

    print(
        "Zero-second intervals:",
        (intervals == 0).sum()
    )

    print(
        "Intervals greater than 5 seconds:",
        (intervals > 5).sum()
    )

    print(
        "Intervals greater than 60 seconds:",
        (intervals > 60).sum()
    )

    print(
        "Intervals greater than 1 hour:",
        (intervals > 3600).sum()
    )

# ======================================
# 6. Calculate recording consistency
# ======================================

    five_second_pct = (
        (intervals == 5).mean() * 100
    )

    print(
        "\nPercentage at 5-second intervals:",
        round(five_second_pct, 2),
        "%"
    )

# ======================================
# 7. Identify largest recording gap
# ======================================

    print(
        "\nLargest recording gap (hours):",
        round(intervals.max() / 3600, 2)
    )

print("\nHeart rate interval inspection completed!")

===== Period 1 =====

Recording Interval Statistics:
Total intervals: 1154667

count    1154667.00
mean          10.21
std          371.63
min            1.00
25%            3.00
50%            5.00
75%           10.00
max       159965.00
Name: SecondsSincePrevious, dtype: float64

Top 10 Most Common Intervals (Seconds):

                      Observations
SecondsSincePrevious
5.0                         350605
10.0                        249817
15.0                        229132
3.0                         179936
1.0                          92604
2.0                          51412
6.0                            239
45.0                            63
7.0                             56
35.0                            29

Recording Interval Checks:
Exactly 5 seconds: 350605
Less than 5 seconds (positive): 323977
Zero-second intervals: 0
Intervals greater than 5 seconds: 480085
Intervals greater than 60 seconds: 577
Intervals greater than 1 hour: 110

Percentage at 5-second intervals: 30.36 %

Largest recording gap (hours): 44.43

===== Period 2 =====

Recording Interval Statistics:
Total intervals: 2483644

count    2483644.00
mean          13.10
std         1227.06
min            1.00
25%            5.00
50%            5.00
75%           10.00
max      1295111.00
Name: SecondsSincePrevious, dtype: float64

Top 10 Most Common Intervals (Seconds):

                      Observations
SecondsSincePrevious
5.0                         868956
10.0                        622040
15.0                        557885
3.0                         245262
1.0                         120929
2.0                          65203
6.0                            697
7.0                            277
45.0                           213
4.0                            196

Recording Interval Checks:
Exactly 5 seconds: 868956
Less than 5 seconds (positive): 431590
Zero-second intervals: 0
Intervals greater than 5 seconds: 1183098
Intervals greater than 60 seconds: 1324
Intervals greater than 1 hour: 284

Percentage at 5-second intervals: 34.99 %

Largest recording gap (hours): 359.75

Heart rate interval inspection completed!

In [88]:

# Step 7C.1: Identify duplicate heart rate records

# ==========================================
# 1. Inspect each collection period
# ==========================================

for label, df in [
    ("Period 1", heart_1),
    ("Period 2", heart_2)
]:

    print(f"\n===== {label} =====")

# ======================================
# 2. Check exact duplicate records
# ======================================

    exact_duplicates = df.duplicated().sum()

    print("\nExact Duplicate Records:")
    print("Total:", exact_duplicates)

# ======================================
# 3. Check duplicate participant-times
# ======================================

    key_columns = ["Id", "Time"]

    duplicate_keys = df.duplicated(
        subset=key_columns
    ).sum()

    print("\nDuplicate Participant-Timestamp Records:")
    print("Total:", duplicate_keys)

# ======================================
# 4. Display duplicate observations
# ======================================

    duplicate_details = df.loc[
        df.duplicated(
            subset=key_columns,
            keep=False
        ),
        ["Id", "Time", "Value"]
    ].sort_values(key_columns)

    print("\nPreview of Duplicate Records:")
    display(duplicate_details.head(20))

# ======================================
# 5. Check conflicting measurements
# ======================================

    if duplicate_details.empty:
        conflicting_keys = 0

    else:
        # Count timestamp groups with
        # more than one heart rate value
        conflicting_keys = (
            duplicate_details
            .groupby(
                key_columns,
                observed=True
            )["Value"]
            .nunique()
            .gt(1)
            .sum()
        )

    print("\nConflicting Participant-Timestamps:")
    print("Total:", conflicting_keys)

# ======================================
# 6. Display duplicate summary
# ======================================

    print("\nDuplicate Summary:")

    print("Total observations:", len(df))
    print("Exact duplicates:", exact_duplicates)
    print("Duplicate participant-times:", duplicate_keys)
    print("Conflicting timestamp groups:", conflicting_keys)

print("\nHeart rate duplicate inspection completed!")

===== Period 1 =====

Exact Duplicate Records:
Total: 0

Duplicate Participant-Timestamp Records:
Total: 0

Preview of Duplicate Records:

Empty DataFrame
Columns: [Id, Time, Value]
Index: []

Conflicting Participant-Timestamps:
Total: 0

Duplicate Summary:
Total observations: 1154681
Exact duplicates: 0
Duplicate participant-times: 0
Conflicting timestamp groups: 0

===== Period 2 =====

Exact Duplicate Records:
Total: 0

Duplicate Participant-Timestamp Records:
Total: 0

Preview of Duplicate Records:

Empty DataFrame
Columns: [Id, Time, Value]
Index: []

Conflicting Participant-Timestamps:
Total: 0

Duplicate Summary:
Total observations: 2483658
Exact duplicates: 0
Duplicate participant-times: 0
Conflicting timestamp groups: 0

Heart rate duplicate inspection completed!

In [89]:

# Step 7D.1: Identify overlapping heart rate records

# ==========================================
# 1. Define the overlapping calendar date
# ==========================================

overlap_date = pd.Timestamp("2016-04-12")

# ==========================================
# 2. Extract records from the overlapping date
# ==========================================

heart_overlap_1 = heart_1.loc[
    heart_1["Time"].dt.normalize() == overlap_date,
    ["Id", "Time", "Value"]
].copy()

heart_overlap_2 = heart_2.loc[
    heart_2["Time"].dt.normalize() == overlap_date,
    ["Id", "Time", "Value"]
].copy()

# Standardize participant IDs for comparison
heart_overlap_1["Id"] = (
    heart_overlap_1["Id"].astype("string")
)

heart_overlap_2["Id"] = (
    heart_overlap_2["Id"].astype("string")
)

# ==========================================
# 3. Display records on April 12
# ==========================================

print("Heart Rate Overlap Inspection:")

print("\nRecords on April 12, 2016:")

print("Period 1:", len(heart_overlap_1))
print("Period 2:", len(heart_overlap_2))

print("\nUnique participants on April 12:")

print("Period 1:", heart_overlap_1["Id"].nunique())
print("Period 2:", heart_overlap_2["Id"].nunique())

# ==========================================
# 4. Match participant-timestamp observations
# ==========================================

heart_overlap = heart_overlap_1.merge(
    heart_overlap_2,
    on=["Id", "Time"],
    how="inner",
    suffixes=("_p1", "_p2"),
    validate="one_to_one"
)

print("\nTotal overlapping participant-timestamp records:")
print(len(heart_overlap))

# ==========================================
# 5. Compare heart rate measurements
# ==========================================

heart_overlap["HeartRateMatch"] = (
    heart_overlap["Value_p1"] ==
    heart_overlap["Value_p2"]
)

matching_records = (
    heart_overlap["HeartRateMatch"].sum()
)

different_records = (
    (~heart_overlap["HeartRateMatch"]).sum()
)

print("\nHeart Rate Measurement Comparison:")

print("Matching measurements:", matching_records)
print("Different measurements:", different_records)

# ==========================================
# 6. Display overlapping records
# ==========================================

print("\nPreview of Overlapping Records:")

display(heart_overlap.head(15))

# ==========================================
# 7. Identify conflicting measurements
# ==========================================

conflicting_records = heart_overlap.loc[
    ~heart_overlap["HeartRateMatch"]
]

print("\nPreview of Conflicting Records:")

display(conflicting_records.head(15))

# ==========================================
# 8. Summarize overlap
# ==========================================

print("\nOverlap Summary:")

print(
    "Total matching participant-timestamps:",
    len(heart_overlap)
)

print(
    "Identical heart rate measurements:",
    matching_records
)

print(
    "Conflicting heart rate measurements:",
    different_records
)

print("\nHeart rate overlap inspection completed!")

Heart Rate Overlap Inspection:

Records on April 12, 2016:
Period 1: 23424
Period 2: 99149

Unique participants on April 12:
Period 1: 8
Period 2: 10

Total overlapping participant-timestamp records:
23424

Heart Rate Measurement Comparison:
Matching measurements: 23424
Different measurements: 0

Preview of Overlapping Records:

            Id                Time  Value_p1  Value_p2  HeartRateMatch
0   2022484408 2016-04-12 07:21:00        97        97            True
1   2022484408 2016-04-12 07:21:05       102       102            True
2   2022484408 2016-04-12 07:21:10       105       105            True
3   2022484408 2016-04-12 07:21:20       103       103            True
4   2022484408 2016-04-12 07:21:25       101       101            True
5   2022484408 2016-04-12 07:22:05        95        95            True
6   2022484408 2016-04-12 07:22:10        91        91            True
7   2022484408 2016-04-12 07:22:15        93        93            True
8   2022484408 2016-04-12 07:22:20        94        94            True
9   2022484408 2016-04-12 07:22:25        93        93            True
10  2022484408 2016-04-12 07:22:35        92        92            True
11  2022484408 2016-04-12 07:22:40        89        89            True
12  2022484408 2016-04-12 07:22:50        83        83            True
13  2022484408 2016-04-12 07:22:55        61        61            True
14  2022484408 2016-04-12 07:23:00        60        60            True

Preview of Conflicting Records:

Empty DataFrame
Columns: [Id, Time, Value_p1, Value_p2, HeartRateMatch]
Index: []

Overlap Summary:
Total matching participant-timestamps: 23424
Identical heart rate measurements: 23424
Conflicting heart rate measurements: 0

Heart rate overlap inspection completed!

In [90]:
# Step 7D.2: Consolidate heart rate datasets

# ==========================================
# 1. Prepare both collection periods
# ==========================================

# Create copies to preserve original datasets
heart_period1 = heart_1.copy()
heart_period2 = heart_2.copy()

# Label each record by its collection period
heart_period1["SourcePeriod"] = "Period 1"
heart_period2["SourcePeriod"] = "Period 2"

# ==========================================
# 2. Combine the datasets
# ==========================================

# Append Period 2 after Period 1
heart_combined = pd.concat(
    [heart_period1, heart_period2],
    ignore_index=True
)

# Record the original number of observations
rows_before = len(heart_combined)

# ==========================================
# 3. Resolve overlapping records
# ==========================================

# Keep Period 2 when a participant and timestamp
# appear in both collection periods
heart_combined = heart_combined.drop_duplicates(
    subset=["Id", "Time"],
    keep="last"
)

# Sort observations chronologically by participant
heart_combined = heart_combined.sort_values(
    ["Id", "Time"]
).reset_index(drop=True)

# ==========================================
# 4. Calculate consolidation results
# ==========================================

rows_after = len(heart_combined)

records_removed = rows_before - rows_after

remaining_duplicates = heart_combined.duplicated(
    subset=["Id", "Time"]
).sum()

print("Heart Rate Consolidation Summary:")

print("Records before consolidation:", rows_before)
print("Records after consolidation:", rows_after)
print("Overlapping records removed:", records_removed)

print(
    "Remaining participant-timestamp duplicates:",
    remaining_duplicates
)

# ==========================================
# 5. Verify retained source periods
# ==========================================

print("\nRecords by Source Period:")

print(heart_combined["SourcePeriod"].value_counts())

# Verify all April 12 observations
# were retained from Period 2
april12_records = heart_combined.loc[
    heart_combined["Time"].dt.normalize()
    == pd.Timestamp("2016-04-12")
]

print("\nApril 12 Records by Source Period:")

print(april12_records["SourcePeriod"].value_counts())

# ==========================================
# 6. Validate consolidation
# ==========================================

assert rows_before == 3638339
assert rows_after == 3614915
assert records_removed == 23424
assert remaining_duplicates == 0

assert (
    april12_records["SourcePeriod"] == "Period 2"
).all()

print("\nHeart rate consolidation successful!")

# ==========================================
# 7. Preview consolidated dataset
# ==========================================

print("\nConsolidated Dataset Preview:")

display(heart_combined.head(10))

print("\nConsolidated Dataset Shape:")
print(heart_combined.shape)

Heart Rate Consolidation Summary:
Records before consolidation: 3638339
Records after consolidation: 3614915
Overlapping records removed: 23424
Remaining participant-timestamp duplicates: 0

Records by Source Period:
SourcePeriod
Period 2    2483658
Period 1    1131257
Name: count, dtype: int64

April 12 Records by Source Period:
SourcePeriod
Period 2    99149
Name: count, dtype: int64

Heart rate consolidation successful!

Consolidated Dataset Preview:

           Id                Time  Value SourcePeriod
0  2022484408 2016-04-01 07:54:00     93     Period 1
1  2022484408 2016-04-01 07:54:05     91     Period 1
2  2022484408 2016-04-01 07:54:10     96     Period 1
3  2022484408 2016-04-01 07:54:15     98     Period 1
4  2022484408 2016-04-01 07:54:20    100     Period 1
5  2022484408 2016-04-01 07:54:25    101     Period 1
6  2022484408 2016-04-01 07:54:30    104     Period 1
7  2022484408 2016-04-01 07:54:35    105     Period 1
8  2022484408 2016-04-01 07:54:45    102     Period 1
9  2022484408 2016-04-01 07:54:55    106     Period 1

Consolidated Dataset Shape:
(3614915, 4)

**Overlapping Records — Heart Rate**

The two heart rate datasets initially contained 3,638,339 observations across both collection periods. Data-quality inspections identified 23,424 overlapping participant-timestamp observations on April 12, 2016. All overlapping observations contained identical heart rate measurements.

To prevent duplicate counting, Period 2 was prioritized when consolidating the datasets. One copy of each overlapping participant-timestamp observation was retained, while all nonoverlapping observations were preserved.

This procedure reduced the combined dataset to 3,614,915 unique participant-timestamp observations. The original source datasets remained unchanged.

In [91]:
# Step 7E.1: Inspect unusual heart rate measurements

# ==========================================
# 1. Display consolidated dataset information
# ==========================================

print("Heart Rate Measurement Quality Inspection:")

print("\nTotal observations:", len(heart_combined))

print(
    "Unique participants:",
    heart_combined["Id"].nunique()
)

# ==========================================
# 2. Calculate descriptive statistics
# ==========================================

print("\nHeart Rate Summary Statistics:")

display(
    heart_combined["Value"].describe().round(2)
)

# ==========================================
# 3. Inspect heart rates by source period
# ==========================================

print("\nHeart Rate Statistics by Source Period:")

period_summary = (
    heart_combined
    .groupby("SourcePeriod")["Value"]
    .agg(["count", "mean", "median", "std", "min", "max"])
    .round(2)
)

display(period_summary)

# ==========================================
# 4. Identify unusual heart rate values
# ==========================================

# Define screening conditions
below_40 = heart_combined["Value"] < 40

between_40_49 = heart_combined["Value"].between(
    40, 49
)

above_180 = heart_combined["Value"] > 180

above_200 = heart_combined["Value"] > 200

print("\nHeart Rate Screening Results:")

print("Below 40 BPM:", below_40.sum())
print("Between 40 and 49 BPM:", between_40_49.sum())
print("Above 180 BPM:", above_180.sum())
print("Above 200 BPM:", above_200.sum())

# ==========================================
# 5. Summarize unusual values by period
# ==========================================

print("\nUnusual Heart Rates by Source Period:")

flag_summary = pd.DataFrame({
    "SourcePeriod": heart_combined["SourcePeriod"],
    "Below40": below_40,
    "Between40And49": between_40_49,
    "Above180": above_180,
    "Above200": above_200
})

display(
    flag_summary
    .groupby("SourcePeriod")
    .sum()
)

# ==========================================
# 6. Examine the lowest heart rates
# ==========================================

print("\n20 Lowest Heart Rate Observations:")

lowest_heart_rates = heart_combined.nsmallest(
    20, "Value"
)

display(
    lowest_heart_rates[
        ["Id", "Time", "Value", "SourcePeriod"]
    ]
)

# ==========================================
# 7. Examine the highest heart rates
# ==========================================

print("\n20 Highest Heart Rate Observations:")

highest_heart_rates = heart_combined.nlargest(
    20, "Value"
)

display(
    highest_heart_rates[
        ["Id", "Time", "Value", "SourcePeriod"]
    ]
)

# ==========================================
# 8. Count participants with extreme values
# ==========================================

print("\nParticipants with Extreme Heart Rates:")

low_participants = heart_combined.loc[
    below_40, "Id"
].nunique()

high_participants = heart_combined.loc[
    above_180, "Id"
].nunique()

print(
    "Participants with readings below 40 BPM:",
    low_participants
)

print(
    "Participants with readings above 180 BPM:",
    high_participants
)

print("\nHeart rate quality inspection completed!")

Heart Rate Measurement Quality Inspection:

Total observations: 3614915
Unique participants: 15

Heart Rate Summary Statistics:

count    3614915.0
mean         78.14
std          19.22
min           36.0
25%           64.0
50%           74.0
75%           89.0
max          203.0
Name: Value, dtype: Float64

Heart Rate Statistics by Source Period:

                count   mean  median    std  min  max
SourcePeriod
Period 1      1131257  79.92    77.0  18.68   36  185
Period 2      2483658  77.33    73.0   19.4   36  203

Heart Rate Screening Results:
Below 40 BPM: 37
Between 40 and 49 BPM: 52977
Above 180 BPM: 250
Above 200 BPM: 13

Unusual Heart Rates by Source Period:

              Below40  Between40And49  Above180  Above200
SourcePeriod
Period 1           14           13866         6         0
Period 2           23           39111       244        13

20 Lowest Heart Rate Observations:

                 Id                Time  Value SourcePeriod
1984064  5577150313 2016-04-10 06:23:30     36     Period 1
1984065  5577150313 2016-04-10 06:23:45     36     Period 1
2206898  5577150313 2016-05-04 02:00:10     36     Period 2
2206899  5577150313 2016-05-04 02:00:20     36     Period 2
1908151  5577150313 2016-04-01 03:58:55     37     Period 1
1908152  5577150313 2016-04-01 03:59:00     37     Period 1
1908153  5577150313 2016-04-01 03:59:15     37     Period 1
1984063  5577150313 2016-04-10 06:23:20     37     Period 1
1984066  5577150313 2016-04-10 06:23:55     37     Period 1
2206900  5577150313 2016-05-04 02:00:35     37     Period 2
2206901  5577150313 2016-05-04 02:00:50     37     Period 2
131279   2022484408 2016-04-27 13:47:00     38     Period 2
131280   2022484408 2016-04-27 13:47:15     38     Period 2
1908149  5577150313 2016-04-01 03:58:30     38     Period 1
1908150  5577150313 2016-04-01 03:58:45     38     Period 1
1984062  5577150313 2016-04-10 06:23:10     38     Period 1
1984067  5577150313 2016-04-10 06:24:00     38     Period 1
2206897  5577150313 2016-05-04 02:00:00     38     Period 2
2208981  5577150313 2016-05-04 07:41:20     38     Period 2
131281   2022484408 2016-04-27 13:47:20     39     Period 2

20 Highest Heart Rate Observations:

                Id                Time  Value SourcePeriod
104213  2022484408 2016-04-21 16:31:40    203     Period 2
104215  2022484408 2016-04-21 16:32:00    203     Period 2
104216  2022484408 2016-04-21 16:32:10    203     Period 2
104217  2022484408 2016-04-21 16:32:20    203     Period 2
104218  2022484408 2016-04-21 16:32:35    203     Period 2
104373  2022484408 2016-04-21 17:05:50    203     Period 2
104374  2022484408 2016-04-21 17:06:05    203     Period 2
104375  2022484408 2016-04-21 17:06:20    203     Period 2
104212  2022484408 2016-04-21 16:31:30    202     Period 2
104214  2022484408 2016-04-21 16:31:50    202     Period 2
104372  2022484408 2016-04-21 17:05:40    202     Period 2
104376  2022484408 2016-04-21 17:06:30    202     Period 2
104219  2022484408 2016-04-21 16:32:40    201     Period 2
104211  2022484408 2016-04-21 16:31:20    200     Period 2
104220  2022484408 2016-04-21 16:32:50    200     Period 2
104221  2022484408 2016-04-21 16:33:05    200     Period 2
104377  2022484408 2016-04-21 17:06:40    200     Period 2
104222  2022484408 2016-04-21 16:33:10    199     Period 2
104223  2022484408 2016-04-21 16:33:25    199     Period 2
104224  2022484408 2016-04-21 16:33:40    199     Period 2

Participants with Extreme Heart Rates:
Participants with readings below 40 BPM: 3
Participants with readings above 180 BPM: 7

Heart rate quality inspection completed!

In [92]:
# Step 7E.2: Investigate extreme heart rate patterns

# ==========================================
# 1. Identify extreme heart rate observations
# ==========================================

extreme_heart = heart_combined.loc[
    (heart_combined["Value"] < 40) |
    (heart_combined["Value"] > 180)
].copy()

print("Extreme Heart Rate Investigation:")

print("\nTotal extreme observations:", len(extreme_heart))

print(
    "Unique participants:",
    extreme_heart["Id"].nunique()
)

# ==========================================
# 2. Summarize extreme values by participant
# ==========================================

extreme_heart["Below40"] = (
    extreme_heart["Value"] < 40
)

extreme_heart["Above180"] = (
    extreme_heart["Value"] > 180
)

participant_summary = (
    extreme_heart
    .groupby("Id", observed=True)
    .agg(
        TotalExtreme=("Value", "size"),
        Below40=("Below40", "sum"),
        Above180=("Above180", "sum"),
        MinimumBPM=("Value", "min"),
        MaximumBPM=("Value", "max")
    )
    .sort_values(
        "TotalExtreme",
        ascending=False
    )
)

print("\nExtreme Measurements by Participant:")
display(participant_summary)

# ==========================================
# 3. Investigate surrounding measurements
# ==========================================

# Identify examples of the lowest and highest values
lowest_record = heart_combined.loc[
    heart_combined["Value"].idxmin()
]

highest_record = heart_combined.loc[
    heart_combined["Value"].idxmax()
]

# Display readings within three minutes
# before and after each extreme observation
def inspect_heart_context(record, label):

    participant = record["Id"]
    timestamp = record["Time"]

    start = timestamp - pd.Timedelta(minutes=3)
    end = timestamp + pd.Timedelta(minutes=3)

    context = heart_combined.loc[
        (heart_combined["Id"] == participant) &
        (heart_combined["Time"].between(start, end))
    ].copy()

    context = context.sort_values("Time")

    print(f"\n{label}:")

    print("Participant:", participant)
    print("Extreme timestamp:", timestamp)
    print("Extreme heart rate:", record["Value"])

    print("\nSurrounding Measurements:")
    display(
        context[
            ["Id", "Time", "Value", "SourcePeriod"]
        ]
    )

# ==========================================
# 4. Examine lowest recorded heart rate
# ==========================================

inspect_heart_context(
    lowest_record,
    "Lowest Heart Rate Context"
)

# ==========================================
# 5. Examine highest recorded heart rate
# ==========================================

inspect_heart_context(
    highest_record,
    "Highest Heart Rate Context"
)

# ==========================================
# 6. Summarize extreme readings by date
# ==========================================

extreme_heart["ActivityDate"] = (
    extreme_heart["Time"].dt.normalize()
)

print("\nTop 15 Dates with Extreme Measurements:")

date_summary = (
    extreme_heart
    .groupby("ActivityDate")
    .agg(
        ExtremeRecords=("Value", "size"),
        Participants=("Id", "nunique"),
        MinimumBPM=("Value", "min"),
        MaximumBPM=("Value", "max")
    )
    .sort_values(
        "ExtremeRecords",
        ascending=False
    )
)

display(date_summary.head(15))

print("\nExtreme heart rate investigation completed!")

Extreme Heart Rate Investigation:

Total extreme observations: 287
Unique participants: 9

Extreme Measurements by Participant:

            TotalExtreme  Below40  Above180  MinimumBPM  MaximumBPM
Id
4020332650            79        0        79         181         191
4558609924            76        0        76         181         199
2022484408            73        6        67          38         203
5577150313            30       30         0          36          39
2347167796            10        0        10         182         195
6962181067             8        0         8         181         184
6117666160             6        0         6         181         189
6775888955             4        0         4         183         185
4388161847             1        1         0          39          39

Lowest Heart Rate Context:
Participant: 5577150313
Extreme timestamp: 2016-04-10 06:23:30
Extreme heart rate: 36

Surrounding Measurements:

                 Id                Time  Value SourcePeriod
1984047  5577150313 2016-04-10 06:20:30     50     Period 1
1984048  5577150313 2016-04-10 06:20:40     50     Period 1
1984049  5577150313 2016-04-10 06:20:50     46     Period 1
1984050  5577150313 2016-04-10 06:21:00     47     Period 1
1984051  5577150313 2016-04-10 06:21:10     46     Period 1
1984052  5577150313 2016-04-10 06:21:25     47     Period 1
1984053  5577150313 2016-04-10 06:21:40     49     Period 1
1984054  5577150313 2016-04-10 06:21:50     50     Period 1
1984055  5577150313 2016-04-10 06:22:00     49     Period 1
1984056  5577150313 2016-04-10 06:22:10     49     Period 1
1984057  5577150313 2016-04-10 06:22:20     48     Period 1
1984058  5577150313 2016-04-10 06:22:30     46     Period 1
1984059  5577150313 2016-04-10 06:22:40     45     Period 1
1984060  5577150313 2016-04-10 06:22:50     41     Period 1
1984061  5577150313 2016-04-10 06:23:00     39     Period 1
1984062  5577150313 2016-04-10 06:23:10     38     Period 1
1984063  5577150313 2016-04-10 06:23:20     37     Period 1
1984064  5577150313 2016-04-10 06:23:30     36     Period 1
1984065  5577150313 2016-04-10 06:23:45     36     Period 1
1984066  5577150313 2016-04-10 06:23:55     37     Period 1
1984067  5577150313 2016-04-10 06:24:00     38     Period 1
1984068  5577150313 2016-04-10 06:24:05     39     Period 1
1984069  5577150313 2016-04-10 06:24:10     41     Period 1
1984070  5577150313 2016-04-10 06:24:20     44     Period 1
1984071  5577150313 2016-04-10 06:24:25     46     Period 1
1984072  5577150313 2016-04-10 06:24:35     56     Period 1
1984073  5577150313 2016-04-10 06:24:40     57     Period 1
1984074  5577150313 2016-04-10 06:24:45     57     Period 1
1984075  5577150313 2016-04-10 06:24:50     58     Period 1
1984076  5577150313 2016-04-10 06:24:55     59     Period 1
1984077  5577150313 2016-04-10 06:25:00     59     Period 1
1984078  5577150313 2016-04-10 06:25:10     60     Period 1
1984079  5577150313 2016-04-10 06:25:15     62     Period 1
1984080  5577150313 2016-04-10 06:25:20     64     Period 1
1984081  5577150313 2016-04-10 06:25:25     66     Period 1
1984082  5577150313 2016-04-10 06:25:30     67     Period 1
1984083  5577150313 2016-04-10 06:25:35     71     Period 1
1984084  5577150313 2016-04-10 06:25:45     74     Period 1
1984085  5577150313 2016-04-10 06:25:50     76     Period 1
1984086  5577150313 2016-04-10 06:25:55     81     Period 1
1984087  5577150313 2016-04-10 06:26:00     84     Period 1
1984088  5577150313 2016-04-10 06:26:05     88     Period 1
1984089  5577150313 2016-04-10 06:26:10     90     Period 1
1984090  5577150313 2016-04-10 06:26:15     96     Period 1
1984091  5577150313 2016-04-10 06:26:20    102     Period 1
1984092  5577150313 2016-04-10 06:26:25    108     Period 1
1984093  5577150313 2016-04-10 06:26:30    112     Period 1

Highest Heart Rate Context:
Participant: 2022484408
Extreme timestamp: 2016-04-21 16:31:40
Extreme heart rate: 203

Surrounding Measurements:

                Id                Time  Value SourcePeriod
104197  2022484408 2016-04-21 16:28:50     89     Period 2
104198  2022484408 2016-04-21 16:29:05     89     Period 2
104199  2022484408 2016-04-21 16:29:20     89     Period 2
104200  2022484408 2016-04-21 16:29:35     89     Period 2
104201  2022484408 2016-04-21 16:29:40     92     Period 2
104202  2022484408 2016-04-21 16:29:45     94     Period 2
104203  2022484408 2016-04-21 16:30:00     94     Period 2
104204  2022484408 2016-04-21 16:30:10     93     Period 2
104205  2022484408 2016-04-21 16:30:15     93     Period 2
104206  2022484408 2016-04-21 16:30:25     91     Period 2
104207  2022484408 2016-04-21 16:30:30     90     Period 2
104208  2022484408 2016-04-21 16:30:35     90     Period 2
104209  2022484408 2016-04-21 16:30:50     90     Period 2
104210  2022484408 2016-04-21 16:31:05     92     Period 2
104211  2022484408 2016-04-21 16:31:20    200     Period 2
104212  2022484408 2016-04-21 16:31:30    202     Period 2
104213  2022484408 2016-04-21 16:31:40    203     Period 2
104214  2022484408 2016-04-21 16:31:50    202     Period 2
104215  2022484408 2016-04-21 16:32:00    203     Period 2
104216  2022484408 2016-04-21 16:32:10    203     Period 2
104217  2022484408 2016-04-21 16:32:20    203     Period 2
104218  2022484408 2016-04-21 16:32:35    203     Period 2
104219  2022484408 2016-04-21 16:32:40    201     Period 2
104220  2022484408 2016-04-21 16:32:50    200     Period 2
104221  2022484408 2016-04-21 16:33:05    200     Period 2
104222  2022484408 2016-04-21 16:33:10    199     Period 2
104223  2022484408 2016-04-21 16:33:25    199     Period 2
104224  2022484408 2016-04-21 16:33:40    199     Period 2
104225  2022484408 2016-04-21 16:33:50    198     Period 2
104226  2022484408 2016-04-21 16:34:00    197     Period 2
104227  2022484408 2016-04-21 16:34:15    197     Period 2
104228  2022484408 2016-04-21 16:34:30    197     Period 2

Top 15 Dates with Extreme Measurements:

              ExtremeRecords  Participants  MinimumBPM  MaximumBPM
ActivityDate
2016-04-15                91             3          39         191
2016-05-08                76             1         181         199
2016-04-21                60             1         181         203
2016-05-04                10             1          36          39
2016-04-19                 9             1         183         195
2016-04-10                 8             1          36          39
2016-04-01                 7             2          37         182
2016-04-27                 6             1          38          39
2016-05-10                 6             1         181         184
2016-04-05                 5             2         182         185
2016-04-30                 4             1         187         189
2016-04-20                 2             1         181         181
2016-05-09                 2             1         181         181
2016-05-01                 1             1          39          39

Extreme heart rate investigation completed!

In [93]:
# Step 7E.3: Create heart rate quality flags

# ==========================================
# 1. Create a working copy of the dataset
# ==========================================

heart_final = heart_combined.copy()

# Sort observations by participant and time
heart_final = (
    heart_final
    .sort_values(["Id", "Time"])
    .reset_index(drop=True)
)

# ==========================================
# 2. Create heart rate threshold flags
# ==========================================

# Very low heart rate
heart_final["FlagBelow40"] = (
    heart_final["Value"] < 40
)

# Low heart rate screening category
heart_final["Flag40to49"] = (
    heart_final["Value"].between(40, 49)
)

# High heart rate
heart_final["FlagAbove180"] = (
    heart_final["Value"] > 180
)

# Very high heart rate
heart_final["FlagAbove200"] = (
    heart_final["Value"] > 200
)

# ==========================================
# 3. Calculate time between consecutive readings
# ==========================================

heart_final["SecondsSincePrevious"] = (
    heart_final
    .groupby("Id", observed=True)["Time"]
    .diff()
    .dt.total_seconds()
)

# ==========================================
# 4. Calculate change in heart rate
# ==========================================

heart_final["BPMChange"] = (
    heart_final
    .groupby("Id", observed=True)["Value"]
    .diff()
)

# ==========================================
# 5. Flag unusually rapid changes
# ==========================================

# Screening rule:
# Change greater than 40 BPM within 30 seconds
# compared with the immediately previous reading

heart_final["FlagRapidChange"] = (
    heart_final["SecondsSincePrevious"].between(
        0, 30,
        inclusive="right"
    )
    &
    (heart_final["BPMChange"].abs() > 40)
)

# ==========================================
# 6. Summarize quality flags
# ==========================================

flag_columns = [
    "FlagBelow40",
    "Flag40to49",
    "FlagAbove180",
    "FlagAbove200",
    "FlagRapidChange"
]

print("Heart Rate Quality Flag Summary:")

display(
    heart_final[flag_columns]
    .sum()
    .to_frame(name="Flagged Records")
)

# ==========================================
# 7. Summarize flags by source period
# ==========================================

print("\nQuality Flags by Source Period:")

display(
    heart_final
    .groupby("SourcePeriod", observed=True)[flag_columns]
    .sum()
)

# ==========================================
# 8. Inspect the largest rapid changes
# ==========================================

print("\nTop 20 Largest Flagged Rapid Changes:")

rapid_changes = heart_final.loc[
    heart_final["FlagRapidChange"]
].copy()

rapid_changes["AbsoluteBPMChange"] = (
    rapid_changes["BPMChange"].abs()
)

display(
    rapid_changes
    .sort_values(
        "AbsoluteBPMChange",
        ascending=False
    )
    [
        [
            "Id",
            "Time",
            "Value",
            "BPMChange",
            "SecondsSincePrevious",
            "SourcePeriod"
        ]
    ]
    .head(20)
)

# ==========================================
# 9. Validate original records and flags
# ==========================================

# Ensure no observations were removed
assert len(heart_final) == 3614915

# Ensure participant-timestamp uniqueness
assert not heart_final.duplicated(
    subset=["Id", "Time"]
).any()

# Verify the original extreme measurement counts
assert heart_final["FlagBelow40"].sum() == 37
assert heart_final["Flag40to49"].sum() == 52977
assert heart_final["FlagAbove180"].sum() == 250
assert heart_final["FlagAbove200"].sum() == 13

# Verify that all above-200 readings are also above 180
assert (
    ~heart_final["FlagAbove200"]
    | heart_final["FlagAbove180"]
).all()

print("\nOriginal records preserved:", len(heart_final))
print("Final dataset shape:", heart_final.shape)

print("\nHeart rate quality flag preparation completed!")

Heart Rate Quality Flag Summary:

                 Flagged Records
FlagBelow40                   37
Flag40to49                 52977
FlagAbove180                 250
FlagAbove200                  13
FlagRapidChange              168

Quality Flags by Source Period:

,FlagBelow40,Flag40to49,FlagAbove180,FlagAbove200,FlagRapidChange
SourcePeriod,,,,,
Period 1,14,13866,6,0,44
Period 2,23,39111,244,13,124

Top 20 Largest Flagged Rapid Changes:

,Id,Time,Value,BPMChange,SecondsSincePrevious,SourcePeriod
104211,2022484408,2016-04-21 16:31:20,200,108,15.0,Period 2
2409025,6117666160,2016-04-30 21:57:05,189,99,5.0,Period 2
2121194,5577150313,2016-04-23 19:06:10,59,-96,10.0,Period 2
3162382,8792009665,2016-04-07 17:55:35,70,-93,15.0,Period 1
2890837,6962181067,2016-05-09 20:04:50,89,-83,5.0,Period 2
288367,2347167796,2016-04-06 12:05:20,140,77,5.0,Period 1
401306,2347167796,2016-04-19 18:22:45,183,77,5.0,Period 2
1945592,5577150313,2016-04-05 10:57:30,79,-76,5.0,Period 1
281053,2347167796,2016-04-05 17:35:00,142,74,15.0,Period 1
1619773,5553957443,2016-04-08 11:07:30,136,74,10.0,Period 1
2088063,5577150313,2016-04-19 20:13:10,78,-73,5.0,Period 2
3162437,8792009665,2016-04-07 18:08:20,70,-72,15.0,Period 1
1546294,4558609924,2016-05-11 01:00:20,128,71,5.0,Period 2
1952394,5577150313,2016-04-06 05:51:05,75,-69,10.0,Period 1
805838,4020332650,2016-04-15 22:08:06,70,-68,22.0,Period 2
1952344,5577150313,2016-04-06 05:45:30,62,-66,5.0,Period 1
2103763,5577150313,2016-04-21 17:40:20,69,-64,15.0,Period 2
2495002,6775888955,2016-04-13 04:19:50,70,-64,5.0,Period 2
1619783,5553957443,2016-04-08 11:09:10,81,-64,10.0,Period 1
3606164,8877689391,2016-05-11 12:39:06,87,-64,5.0,Period 2

Original records preserved: 3614915
Final dataset shape: (3614915, 11)

Heart rate quality flag preparation completed!

In [94]:
# Step 7E.4: Validate final heart rate dataset

# ==========================================
# 1. Verify dataset dimensions
# ==========================================

print("Final Heart Rate Dataset Validation:")

print("\nDataset Shape:", heart_final.shape)

assert heart_final.shape == (3614915, 11)

print("Unique Participants:", heart_final["Id"].nunique())

assert heart_final["Id"].nunique() == 15

# ==========================================
# 2. Verify essential columns
# ==========================================

essential_columns = [
    "Id",
    "Time",
    "Value",
    "SourcePeriod"
]

print("\nMissing Essential Values:")

print(
    heart_final[essential_columns]
    .isna()
    .sum()
)

assert heart_final[essential_columns].notna().all().all()

# ==========================================
# 3. Verify participant-timestamp uniqueness
# ==========================================

duplicate_records = heart_final.duplicated(
    subset=["Id", "Time"]
).sum()

print("\nRemaining Participant-Timestamp Duplicates:",
      duplicate_records)

assert duplicate_records == 0

# ==========================================
# 4. Verify heart rate measurements
# ==========================================

print("\nHeart Rate Measurement Checks:")

print("Minimum BPM:", heart_final["Value"].min())
print("Maximum BPM:", heart_final["Value"].max())

print(
    "Zero or Negative BPM:",
    (heart_final["Value"] <= 0).sum()
)

assert (heart_final["Value"] > 0).all()

# ==========================================
# 5. Verify calculated time intervals
# ==========================================

print("\nRecording Interval Checks:")

print(
    "Missing First-Observation Intervals:",
    heart_final["SecondsSincePrevious"].isna().sum()
)

print(
    "Nonpositive Recorded Intervals:",
    (heart_final["SecondsSincePrevious"].dropna() <= 0).sum()
)

# One missing interval is expected per participant
assert (
    heart_final["SecondsSincePrevious"].isna().sum()
    == heart_final["Id"].nunique()
)

assert (
    heart_final["SecondsSincePrevious"].dropna() > 0
).all()

# ==========================================
# 6. Validate quality flag totals
# ==========================================

expected_flags = {
    "FlagBelow40": 37,
    "Flag40to49": 52977,
    "FlagAbove180": 250,
    "FlagAbove200": 13,
    "FlagRapidChange": 168
}

print("\nQuality Flag Validation:")

for flag, expected in expected_flags.items():

    actual = int(heart_final[flag].sum())

    print(f"{flag}: {actual}")

    assert actual == expected

# ==========================================
# 7. Verify rapid-change flag logic
# ==========================================

expected_rapid_change = (
    (heart_final["SecondsSincePrevious"] > 0)
    &
    (heart_final["SecondsSincePrevious"] <= 30)
    &
    (heart_final["BPMChange"].abs() > 40)
)

assert (
    heart_final["FlagRapidChange"]
    == expected_rapid_change
).all()

print("\nRapid-Change Flag Logic: Validated")

# ==========================================
# 8. Summarize final dataset by source period
# ==========================================

print("\nFinal Records by Source Period:")

print(heart_final["SourcePeriod"].value_counts())

# ==========================================
# 9. Confirm successful validation
# ==========================================

print("\nAll heart rate validation checks passed!")

print("Final Dataset Shape:", heart_final.shape)

print("Dataset ready for export!")

Final Heart Rate Dataset Validation:

Dataset Shape: (3614915, 11)
Unique Participants: 15

Missing Essential Values:
Id              0
Time            0
Value           0
SourcePeriod    0
dtype: int64

Remaining Participant-Timestamp Duplicates: 0

Heart Rate Measurement Checks:
Minimum BPM: 36
Maximum BPM: 203
Zero or Negative BPM: 0

Recording Interval Checks:
Missing First-Observation Intervals: 15
Nonpositive Recorded Intervals: 0

Quality Flag Validation:
FlagBelow40: 37
Flag40to49: 52977
FlagAbove180: 250
FlagAbove200: 13
FlagRapidChange: 168

Rapid-Change Flag Logic: Validated

Final Records by Source Period:
SourcePeriod
Period 2    2483658
Period 1    1131257
Name: count, dtype: int64

All heart rate validation checks passed!
Final Dataset Shape: (3614915, 11)
Dataset ready for export!

In [95]:
# Step 7H.1: Export cleaned heart rate dataset

# ==========================================
# 1. Create a copy for exporting
# ==========================================

heart_export = heart_final.copy()

# Sort observations by participant and timestamp
heart_export = (
    heart_export
    .sort_values(["Id", "Time"])
    .reset_index(drop=True)
)

# ==========================================
# 2. Define the output file path
# ==========================================

heart_output = cleaned_path / "heartRate_clean.csv"

# ==========================================
# 3. Export the dataset as a CSV file
# ==========================================

heart_export.to_csv(
    heart_output,
    index=False
)

# ==========================================
# 4. Confirm the export
# ==========================================

assert heart_output.is_file()

print("Heart Rate Dataset Exported Successfully!")

print("\nFile Location:")
print(heart_output)

print("\nExported Dataset Dimensions:")
print("Rows:", len(heart_export))
print("Columns:", heart_export.shape[1])

print("\nFile Size (MB):")
print(round(heart_output.stat().st_size / (1024**2), 2))

Heart Rate Dataset Exported Successfully!

File Location:
/Users/isandoval/Desktop/Bellabeat_Case_Study/Cleaned_Data/heartRate_clean.csv

Exported Dataset Dimensions:
Rows: 3614915
Columns: 11

File Size (MB):
275.43

In [96]:
# Step 7H.2: Verify exported heart rate dataset

# ==========================================
# 1. Reload the exported CSV
# ==========================================

# Use memory-efficient data types
heart_dtypes = {
    "Id": "category",
    "Value": "int16",
    "SourcePeriod": "category",
    "FlagBelow40": "bool",
    "Flag40to49": "bool",
    "FlagAbove180": "bool",
    "FlagAbove200": "bool",
    "SecondsSincePrevious": "float32",
    "BPMChange": "float32",
    "FlagRapidChange": "bool"
}

verify_heart = pd.read_csv(
    heart_output,
    dtype=heart_dtypes,
    parse_dates=["Time"]
)

# ==========================================
# 2. Verify dataset dimensions
# ==========================================

print("Exported Heart Rate Dataset Shape:")
print(verify_heart.shape)

assert verify_heart.shape == (3614915, 11)

# ==========================================
# 3. Verify essential values
# ==========================================

essential_columns = [
    "Id",
    "Time",
    "Value",
    "SourcePeriod"
]

print("\nMissing Essential Values:")

print(
    verify_heart[essential_columns]
    .isna()
    .sum()
)

assert verify_heart[essential_columns].notna().all().all()

# ==========================================
# 4. Verify participant-timestamp uniqueness
# ==========================================

duplicates = verify_heart.duplicated(
    subset=["Id", "Time"]
).sum()

print("\nRemaining Participant-Timestamp Duplicates:")
print(duplicates)

assert duplicates == 0

# ==========================================
# 5. Verify heart rate measurements
# ==========================================

print("\nHeart Rate Measurement Checks:")

print("Minimum BPM:", verify_heart["Value"].min())
print("Maximum BPM:", verify_heart["Value"].max())

assert verify_heart["Value"].min() == 36
assert verify_heart["Value"].max() == 203

# ==========================================
# 6. Verify calculated recording intervals
# ==========================================

print("\nMissing Calculated Values:")

print(
    verify_heart[
        ["SecondsSincePrevious", "BPMChange"]
    ]
    .isna()
    .sum()
)

# One missing interval and BPM change per participant
assert verify_heart["SecondsSincePrevious"].isna().sum() == 15
assert verify_heart["BPMChange"].isna().sum() == 15

# ==========================================
# 7. Verify quality flag totals
# ==========================================

expected_flags = {
    "FlagBelow40": 37,
    "Flag40to49": 52977,
    "FlagAbove180": 250,
    "FlagAbove200": 13,
    "FlagRapidChange": 168
}

print("\nQuality Flag Summary:")

flag_columns = list(expected_flags.keys())

print(
    verify_heart[flag_columns]
    .sum()
)

for flag, expected in expected_flags.items():
    assert verify_heart[flag].sum() == expected

# ==========================================
# 8. Verify rapid-change flag calculations
# ==========================================

expected_rapid = (
    (verify_heart["SecondsSincePrevious"] > 0)
    &
    (verify_heart["SecondsSincePrevious"] <= 30)
    &
    (verify_heart["BPMChange"].abs() > 40)
)

assert (
    verify_heart["FlagRapidChange"] == expected_rapid
).all()

print("\nRapid-Change Flag Logic: Validated")

# ==========================================
# 9. Verify source period records
# ==========================================

print("\nRecords by Source Period:")

period_counts = verify_heart["SourcePeriod"].value_counts()

print(period_counts)

assert period_counts["Period 1"] == 1131257
assert period_counts["Period 2"] == 2483658

# ==========================================
# 10. Verify participant count
# ==========================================

print("\nUnique Participants:")
print(verify_heart["Id"].nunique())

assert verify_heart["Id"].nunique() == 15

# ==========================================
# 11. Check memory usage
# ==========================================

memory_mb = (
    verify_heart.memory_usage(deep=True).sum()
    / (1024 ** 2)
)

print("\nMemory Usage (MB):")
print(round(memory_mb, 2))

# ==========================================
# 12. Confirm successful verification
# ==========================================

print("\nExport Verification Successful!")

print("Final Dataset Shape:", verify_heart.shape)

print("All heart rate export verification checks passed!")

Exported Heart Rate Dataset Shape:
(3614915, 11)

Missing Essential Values:
Id              0
Time            0
Value           0
SourcePeriod    0
dtype: int64

Remaining Participant-Timestamp Duplicates:
0

Heart Rate Measurement Checks:
Minimum BPM: 36
Maximum BPM: 203

Missing Calculated Values:
SecondsSincePrevious    15
BPMChange               15
dtype: int64

Quality Flag Summary:
FlagBelow40           37
Flag40to49         52977
FlagAbove180         250
FlagAbove200          13
FlagRapidChange      168
dtype: int64

Rapid-Change Flag Logic: Validated

Records by Source Period:
SourcePeriod
Period 2    2483658
Period 1    1131257
Name: count, dtype: int64

Unique Participants:
15

Memory Usage (MB):
86.19

Export Verification Successful!
Final Dataset Shape: (3614915, 11)
All heart rate export verification checks passed!

**Data Cleaning and Validation — Heart Rate**

The two heart rate datasets initially contained 3,638,339 observations across both collection periods. Data-quality inspections identified 23,424 overlapping participant-timestamp records on April 12, 2016. All overlapping records contained identical heart rate measurements. To prevent duplicate counting, Period 2 was prioritized during consolidation, resulting in 3,614,915 unique participant-timestamp observations across 15 participants.

The consolidated dataset contained no missing essential values, duplicate participant-timestamp combinations, or zero and negative heart rate measurements. Recorded heart rates ranged from 36 to 203 beats per minute (BPM).

Additional quality checks identified 37 observations below 40 BPM, 52,977 observations between 40 and 49 BPM, 250 observations above 180 BPM, and 13 observations above 200 BPM. An additional 168 observations were flagged for rapid heart rate changes. These measurements were retained because unusual readings alone do not establish that a record is invalid.

Recording intervals were also examined because heart rate measurements were collected at varying frequencies. The first observation for each of the 15 participants had no preceding measurement, resulting in 15 expected missing values in the calculated interval and BPM-change columns.

Quality flags were created to identify potentially unusual heart rate measurements without permanently removing observations. The processed dataset was validated for duplicate records, missing essential values, invalid measurements, calculated intervals, and quality-flag consistency.

The final dataset was exported as heartRate_clean.csv and successfully reloaded and verified for further analysis.